.env-dist, README.md, server.js
Based on https://github.com/mozilla/blurts-server/pull/13 so that should merge first. Just putting this up to get first comments.
=> WIP: Update readme 17

.eslintrc.js, package-lock.json, package.json, public/main.js, routes/user.js
Fixes #40 
Fixes #41 
Fixes #43
=> Add more ESLint rules

package-lock.json, package.json
=> Add nsp to check for possibly sketchy dependencies

db-utils.js, public/js/test.js, public/test.html, routes/oauth.js, routes/user.js, subscribers.js, tests/test-subscribers.js
Fixes #59 
Fixes #68 
Fixes #69
Fixes #65
=> Use database for email verification, use real response codes, some refactoring.

db/models/subscriber.js, routes/oauth.js, views/confirm.hbs, views/home.hbs, views/scan.hbs
See https://drive.google.com/file/d/1AuhQCFHOsNduMF_Sne32mCMfMeaTFuVJ/view for mock-ups.
=> for #31 #34 views for home, scan, and confirm

routes/oauth.js
I changed the redirect URL on the dashboard too.
=> Fix #76: rename /oauth/redirect to /oauth/confirmed

.eslintrc.js, email-utils.js, hibp.js, routes/oauth.js, routes/user.js, scripts/get-hashsets.js, server.js
Supersedes https://github.com/mozilla/blurts-server/pull/109 with rebase an change to still lint `test/` files.
=> Tweak eslint scripts

.env-dist, README.md, package-lock.json
Updates based on helping Lesley get it running on her machine.
=> setup updates

.sequelizerc
=> Remove unused .sequelizerc config file

package-lock.json, package.json, routes/dockerflow.js, server.js
Using @pdehaan's suggestions in #21.
=> fix #21: serve Dockerflow responses

package-lock.json, package.json
This should fix the error on heroku.
=> add uuid to package.json

.stylelintrc, package-lock.json, package.json, public/css/app.css
Fixes #85 
fixed `public/css/app.css` after `npm run lint`
=> Add css lint support

LICENSE, package.json
=> Add LICENSE file and update package.json license

public/css/app.css, public/js/monitor.js, views/partials/banner_breach.hbs, views/partials/compromised_accounts.hbs
quick fixes : 
-updates false door blurb
-fixes sign up button triggering 
-removes jquery/foundation reference error #165
=> Sign up button fix + Errors Fix + Alignment Fix

views/partials/scan_form.hbs
=> Make email address field required on scan form

.dockerignore, circle.yml
=> Fixes version.json

README.md
=> Add blurts-addon link to README

views/partials/scan_form.hbs
Disables the autocomplete dropdown menu on the scan email form.
=> disable autocomplete

public/js/monitor.js
Emails are not case sensitive so the service shouldn't be either.
=> toLowerCase the email before hashing

views/partials/banner_breach.hbs, views/partials/compromised_accounts.hbs
Updating templates to correctly display 'Have I Been Pwned'
=> Uppercase B

public/css/app.css, views/partials/banner_breach.hbs, views/partials/compromised_accounts.hbs, views/partials/hipb_attribution.hbs
References to HIBP without the "?" and with links to the HIBP website.
=> branding updates

hibp.js, public/css/app.css, public/js/monitor.js
-Filters out unverified breaches that are classified as spam, retired, and/or sensitive. 
-Disables input while email scan form is processing.
=> Ui updates

public/css/app.css, public/js/monitor.js, views/partials/scan_form.hbs, views/partials/subscribe_modal.hbs
more front end clean up // prep for forthcoming ui specs.
=> more front end clean up

views/partials/breach_listing.hbs, views/partials/compromised_accounts.hbs, views/partials/confirm_account.hbs, views/partials/featured_breach.hbs, views/partials/featured_compromised_account_headline.hbs, views/partials/hibp_attribution.hbs, views/partials/password_tip_svg.hbs, views/partials/scan_another_email.hbs, views/partials/scan_form.hbs, views/partials/scan_results_headline.hbs, views/partials/sign_up_banner.hbs, views/partials/sign_up_ffxm.hbs, views/partials/subscribe_modal.hbs, views/partials/tips.hbs, views/partials/what_to_do.hbs, views/partials/what_to_do_svg.hbs
Fixes nothing, changes everything!!1!
=> Reformat views/ directory and give images absolute path

controllers/ses.js, controllers/user.js, db/DB.js, email-utils.js, public/js/monitor.js, routes/user.js, tests/db.test.js, tests/email.test.js, views/email/email_verify.hbs, views/layouts/email.hbs, views/unsubscribe.hbs
This is a very ugly start but I'd like to get a review.
=> WIP: User unsubscribe 286

public/js/monitor.js
=> Stash scan email in sessionStorage, auto-populate subscribe modal email input with it

public/js/monitor.js
=> Trim email input before validating

public/css/app.css, views/email/report.hbs
Corrects a few other remaining inconsistencies between the spec and the build and fixes #400 ( - radio buttons positioned too closely to labels on windows herokuapp).
=> more UI Tweaks

controllers/user.js
I ran OWASP ZAP at my localhost and also found another error trace when email was left off.
=> throw friendly errors in /user/add

views/email/email_partials/email_footer.hbs, views/layouts/default.hbs, views/partials/subscribe_modal/subscribe_to_ffxm.hbs
See https://bugzilla.mozilla.org/show_bug.cgi?id=1491440
=> update to "Terms and Privacy" everywhere with url

views/partials/what_to_do.hbs
Minor change to What To Do copy.
=> Final "What To Do" copy

public/css/app.css
=> UI Nit Fix // Changes text sizing in Confirmation page. 

public/css/app.css, views/error-429.html, views/error.hbs
Adds new static HTML 429 error page and restyles all error pages to match spec.
=> New error pages

public/css/app.css, views/partials/subscribe_modal/confirm_your_account.hbs
Updates modal with 24 hour confirmation email expiration copy and prevents "Resend email" blurb from getting cut off on mobile.
=> Updates confirmation modal screen. 

hibp.js, views/email/email_partials/breach_alert.hbs, views/email/email_partials/email_button.hbs, views/email/email_partials/email_footer.hbs, views/email/email_partials/email_logo.hbs, views/email/email_partials/email_single_breach.hbs, views/email/email_partials/report_header_details.hbs, views/email/email_partials/report_list_headline.hbs, views/email/email_partials/report_password_tips.hbs, views/email/email_verify.hbs, views/email/layouts/default_email.hbs, views/email/report.hbs
Based on #504  // Last two commits new here. 
Removes spam list from partials and filters .isSpamList breaches out of reports.
=> Remove spam lists from breach reports.

db/migrations/20181007085241_add_sha1_index.js
When we deploy this, we will need ops to run the included SQL statement directly on stage & prod environments.
=> bug #1496859: knex migration for sha1 index

scripts/quickest-breach-alerts.js
A quick utility script I wrote to calculate the fastest response time for HIBP breach alerts.
=> script to calculate quickest breach alert

controllers/hibp.js, views/email/email_partials/breach_alert.hbs, views/email/email_partials/email_footer.hbs, views/email/email_partials/email_hibp_attribution.hbs, views/email/email_partials/email_logo.hbs, views/email/email_partials/email_single_breach.hbs, views/email/email_partials/report_header_details.hbs, views/email/email_partials/report_list_headline.hbs, views/email/email_partials/report_what_to_do_next.hbs, views/email/layouts/default_email.hbs, views/email/report.hbs
- Removes 'Website Breaches' from new breach alerts and removes the 'Website Breaches' heading from breach reports. 
- Adds What To Do Next copy to new breach alerts and breach reports.
=> Email content updates

views/email/email_partials/email_footer.hbs, views/email/email_verify.hbs, views/email/layouts/default_email.hbs
- Moves 'this is an automated email' copy down into footer so that it appears on each page.
- Updates copy and button copy in the verification email.
=> Verification email updates

CODEOWNERS, l10n.toml
CODEOWNERS will ping me for review whenever FTL files in /en are changed
l10n.toml can be used for automation, i.e. install `compare-locales` 
```
pip install compare-locales
```
Then run from the root
```
compare-locales l10n.toml . it
```
You can also get JSON and use it for automation (level of completion, errors).
=> Add CODEOWNERS and l10n.toml

hbs-helpers.js, locales/en/app.ftl, tests/hbs-helpers.test.js, views/confirm.hbs, views/email/email_partials/email_single_breach.hbs, views/layouts/default.hbs, views/monitor.hbs, views/partials/banners/download_firefox_banner.hbs, views/partials/banners/download_firefox_bar.hbs, views/partials/banners/sign_up_banner.hbs, views/partials/breach_listing.hbs, views/partials/compromised_accounts.hbs, views/partials/featured_breach.hbs, views/partials/hibp_attribution.hbs, views/partials/password_tips.hbs, views/partials/scan_another_email.hbs, views/partials/scan_form.hbs, views/partials/sign_up_button.hbs, views/partials/social_media_sharing_buttons.hbs, views/partials/subscribe_modal/confirm_your_account.hbs, views/partials/subscribe_modal/subscribe_to_ffxm.hbs, views/partials/what_to_do.hbs, views/scan.hbs, views/unsubscribe.hbs, views/unsubscribe_survey.hbs
- Updates templates and helpers to send/accept req.supportedLocales instead of req.
- Adds additional logic to scan.hbs for scans coming from featured breach pages.
- Adds strings to ftl file.
=> I20n updates

locales/en/app.ftl, views/layouts/default.hbs
Adds site description, and "Sent!" (in modal, after resend) to ftl strings.
=> Add strings for l10n

public/css/app.css, views/partials/subscribe_modal/confirm_your_account.hbs, views/partials/subscribe_modal/subscribe_to_ffxm.hbs
Better handling of unknown/varied text lengths in buttons, sign up modal, and footer links.
=> Fix l10n related UI bugs

locales/en/email-strings.ftl, views/email/email_partials/email_footer.hbs
=> Add period to unsubscribe-link string and create new string ID.

views/partials/subscribe_modal/subscribe_to_ffxm.hbs
=> Update modal form placeholder with ftl string.

locales/es-MX/app.ftl
=> Close span surrounding Firefox Monitor string in es-MX.

views/partials/password_tips.hbs
Fixes password tip looping so that the password tips appear again.
=> Fix Password Tips looping in template

locales/en/app.ftl
=> Update Alerts in Footer

public/css/app.css
Last little baby nits from UI/UX for the new sensitive featured breach pages.
=> Tweaks per final UI/UX review of sensitive featured breach page.

public/css/app.css
Fixes text issues just spotted in stage.
=> Adjust font sizes

locales/en-CA/app.ftl
=> Update en-CA about-firefox-alerts

locales/en/app.ftl, locales/en/email-strings.ftl
Adds copy for new site-description, new email message, and social media share posts/tweets. 
@flodolo some of the previously added strings will become obsolete once we implement the strings in this PR. Should the obsolete strings remain in the FTL file or is it safe to delete them?
=> Adds new strings for sharing by email and social media.

server.js
I can't think of any reason these really need to be on stage/production.
Fixes #612
=> Serve email-l10n routes on env=dev only. 

controllers/home.js
=> Throw error/404 on unknown breaches.

public/css/app.css, public/css/fxa.css
=> Remove text-transform:capitalize from CSS (#744)

hbs-helpers.js, locales/en/app.ftl, modified-strings.js, public/css/app.css, views/partials/footer.hbs, views/partials/legacy/legacy_footer.hbs
- Punctuation updates requested by content. 
- Fixes #741 
- Fixes #725
=> String fixes. 

controllers/oauth.js
=> Fix #756  ("Scan Another Email..." button noop)

public/css/fxa.css, views/partials/fxa_enabled/fxa_monitor.hbs, views/partials/fxa_enabled/scan_results/fxa_compromised_accounts.hbs, views/partials/fxa_enabled/scan_results/single_breach.hbs, views/partials/hibp_attribution.hbs
- Adds attribution to breach detail pages (isn't in spec, but should be there).
- Updates HIBP styling/positioning to match spec.
=> HIBP attribution updates.

package-lock.json, package.json, server.js
=> remove unnecessary hbs module that has vulnerability

server.js
Add Google Analytics related URLs to CSP.
Fixes #728
=> Fix CSP errors.

hbs-helpers.js, views/partials/fxa_enabled/scan_results/result_headline.hbs, views/partials/fxa_enabled/scan_results/result_subhead.hbs
=> Bold out number of breached accounts in scan results.

controllers/ses.js, db/DB.js, db/migrations/20190219154519_add_fxa_uid_column.js, tests/controllers/ses.test.js, tests/controllers/sns-fxa-delete.json
Store fxa uid when adding subscribers; handle SNS callback messages from
FXA delete events, and delete the corresponding Monitor subscriber.
=> fix #710 fix #721: delete subscriber on fxa delete

controllers/user.js, locales/en/app.ftl, public/css/fxa.css, views/partials/banners/sign_up_banner.hbs, views/partials/fxa_enabled/fxa_sign_up_banner.hbs, views/partials/fxa_enabled/scan_results/result_subhead.hbs, views/partials/sign_up_button.hbs, views/partials/subpages/unsubscribe_survey.hbs, views/subpage.hbs
- Adds legally sanctioned, latest copy.
- Updates partials to use new strings.
- Changes sign up button text when foundBreaches "===" 0.
- Changes sign up banner text and removes sign up button from the sign up banner on sensitive breach detail pages.
-Fixes #773
=> Add new strings and update partials.

locales/en/app.ftl, views/partials/footer.hbs
=> Add "Frequently Asked Questions" link to footer (#820)

views/layouts/default.hbs
Use Twitter card with larger image. 
-Fixes #839
=> Update Twitter card

controllers/oauth.js, controllers/user.js, db/DB.js, db/migrations/20190328111900_add_email_addresses_table.js, public/js/analytics_dnt-helper.js, public/js/monitor.js, routes/user.js, scan-results.js, server.js, views/partials/subpages/preferences.hbs
update DB code to match email_addresses table
start preferences page and POST /user/email
=> DRAFT/WIP: migration for email_addresses table

controllers/user.js, db/DB.js, db/migrations/20190422140308_add_subscriber_breaches_shown.js, db/seeds/test_subscribers.js, package.json, tests/db.test.js, tests/resetDB.js
=> wip for #863: add breaches_last_shown to DB

.travis.yml, l10n.toml
=> Update l10n linter to moz-l10n-lint

locales/en/app.ftl
After talking to @flodolo, the plan is to add the new strings to the existing .ftl file and clean out the old strings after the V2 launch. This will likely be less problematic than attempting to merge separate .ftl files later.
=> Adds new strings for V2 website.

controllers/hibp.js, controllers/user.js, db/DB.js, db/migrations/20190512170106_add_all_emails_to_primary_column.js, db/seeds/test_subscribers.js, tests/controllers/hibp.test.js, tests/controllers/user.test.js, tests/db.test.js, views/partials/dashboards/preferences.hbs
Still TODO:
Update the user preference UI to flip the new `all_emails_to_primary` field to `true`.
=> all_emails_to_primary sends all emails to primary

template-helpers/breach-detail.js
=> Update '5 Myths..' anchor.

public/css/email-card.css, views/partials/dashboards/breaches-dash.hbs
Adds HIBP attribution to dashboard when/if one of the user's emails has breaches.
=> Add HIBP attribution to dashboard.

public/css/forms.css
Observe said dot in upper left corner of image.
=> Fixes the strange "." that appears on invalid form submits.

views/partials/forms/scan-email-form.hbs
=> Fix button values on scan email form.

public/js/all-breaches.js
=> Use "Breach Reported" string in /breaches cards.

public/css/header.css, template-helpers/dashboard.js, template-helpers/hbs-helpers.js, template-helpers/scan-results.js, views/partials/dashboards/breaches-dash.hbs
Fixes #978, #980, #940, and #981.
=> UI issue fixes

locales/en-CA/app.ftl, locales/en-GB/app.ftl, locales/en/app.ftl
=> Title case Sign In button for en locales.

locales/en/app.ftl, template-helpers/dashboard.js
=> Update communication options.

views/partials/sign-up-banners/login-link.hbs
Establishes `Log In >` links as FxA entrypoints.
=> Add ga/fxa entrypoint attributes to log in links.

public/css/breach-detail.css, template-helpers/breach-detail.js, views/breach-detail.hbs
Removes the "What is a website breach" copy on sensitive breach detail pages and fixes #1012.
=> Update breach details page

locales/en/app.ftl
This adds the strings that will appear in the new "Join Firefox" top bar.
=> Add new "Join Firefox" top banner strings.

views/breach-detail.hbs
=> Hide sign up banner on breach detail page for signed in users.

template-helpers/breach-detail.js
Fixes #950 /cc @betsymi 
Not a fan of hardcoding a list in one of the files, but I'm not sure it's any better in the AppConstants or package.json or server.js file.
=> Update list of data-aggregator-breaches

public/css/header.css, public/js/monitor.js, views/partials/header/nav-links.hbs
Prevents the active link underline from being wider or narrower than the active link text.
=> Make active link underline equal to the text length.

controllers/hibp.js, controllers/oauth.js, controllers/user.js, views/partials/email_partials/email_footer.hbs
Fixes #1068 (despite the branch name claiming otherwise).
=> Show $userEmail in footer.

public/css/security-tips.css
=> Fix 404 on /background-noodle-top3.svg.

locales/en/app.ftl, locales/en/email-strings.ftl
This removes unused strings from `app.ftl` and `email-strings.ftl`. There will be some additional cleanup once #1093 has pushed to production.
=> Remove unused strings.

locales/en/app.ftl, template-helpers/footer.js
Closes #924 
Hopefully this will make it easier for people to find the repo. 
Maybe we also want to consider #125?
=> Footer updates: Add a link to the repo.

email-utils.js
Noticed this holdover while working on #1094.
=> Remove unused "getShareByEmail()".

controllers/hibp.js
=> Reinstate /hibp/breaches endpoint.

controllers/home.js, controllers/scan.js, controllers/user.js, db/DB.js, lib/fxa.js, routes/user.js, scan-results.js, template-helpers/breach-stats.js, tests/controllers/home.test.js
For #1110, I want to get this up for review ASAP.
Still TODO:
=>  fix #1110: add /user/breach-stats endpoint 

locales/en/app.ftl, template-helpers/articles.js
=> Localize security tip descriptions.

locales/en-CA/app.ftl, locales/en-GB/app.ftl, locales/en/app.ftl, template-helpers/breach-detail.js
Addressing more of the issues in #1034
=> Copy refinements.

template-helpers/emails.js, views/layouts/default_email.hbs
Fixes broken logo and fixes incorrect breach alert FAQ links.
Closes #1125 #1132
=> Post QA Email UI Updates.

locales/en/data-classes.ftl
=> Add 'taxation-records' data class

package.json
Noticed this while working on #844 .
=> Watch all JS files.

template-helpers/scan-results.js
=> Fix ".hasMessage" error.

views/partials/email_partials/email_single_breach.hbs
=> Hard code breach card logo img src for breach alert emails.

locales/en-CA/email-strings.ftl, locales/en-GB/email-strings.ftl, locales/en/email-strings.ftl
Fixes #567
Small grammar issue (log into > log in to) in email-strings.ftl
=> Updated email-strings.ftl

controllers/user.js, db/DB.js, scripts/lowercase-all-records.js, tests/controllers/hibp.test.js, tests/controllers/user.test.js, tests/db.test.js
Superseding https://github.com/mozilla/blurts-server/pull/1188 with this WIP more extensive fix.
=> WIP: lowercase emails #1182

locales/en/app.ftl, locales/en/bento.ftl
Updates `app.ftl` and adds `bento.ftl` so that we can start localizing these strings while work on the Bento wraps up.
=> Add bento strings

.env-dist
=> fix 1135: default SENTRY_DSN to blank

public/js/monitor.js
This reverts commit c74a67b53fc8ca74ab354591aab3613f305693ad.
=> Revert "Accepts emails on internationalized domain names"

views/breach-detail.hbs, views/partials/email-card.hbs, views/partials/email_partials/email_disclaimers.hbs, views/partials/email_partials/email_single_breach.hbs
Ah, I was confused with the https://github.com/mozilla-services/private-network/pull/116 PR which fixed the typo.
=> Fix noreferer typo

views/partials/fuzzy-find.hbs
This should fix #1293 and fix #1294 part of #1295 :)
=> Added data-no-csrf to indicate no anti csrf token is required

hibp.js
=> No rated R breaches on the landing page / latest breach card.

public/css/app.css, public/css/breach-detail.css, template-helpers/breach-detail.js
=> Add breach overview title to template.

views/partials/forms/remove-email-form.hbs
=> Send ga event ping when a user removes a secondary email.

db/DB.js, package-lock.json, package.json, scripts/send-email-to-pre-fxa-subscribers.js
Run like so:
```
PAGE_SIZE=5 node scripts/send-email-to-pre-fxa-subscribers.js
```
=> use knex-paginate to paginate pre-FXA query

controllers/hibp.js, email-utils.js, lib/fxa.js, middleware.js, server.js, template-helpers/emails.js, views/partials/email_partials/email_disclaimers.hbs, views/partials/email_partials/email_single_breach.hbs, views/partials/email_partials/report.hbs
Still need to add the actual ping the FXA, but here's the skeleton of the functionality.
@lesleyjanenorton - can you help me consider how we can get the `subscriberId` into ALL of the email links?
@pdehaan - is this crazy? 😄
=> fix #1191: ping fxa on email visits

public/js/fxa-analytics.js, scan-results.js, views/scan.hbs
Will follow up with another PR to clean out any old templates/CSS/etc.
=> Remove old scan page.

package-lock.json, package.json
=> update full-icu to 1.3.0

public/js/monitor.js
=> Fix scan form event listeners on mobile.

locales/en/app.ftl
This adds the new strings needed for the upcoming breach resolution feature.
=> Add strings for breach resolution feature.

package-lock.json, package.json
Per https://github.com/mozilla/blurts-server/pull/1470#issuecomment-573363384
=> Update onchange devDependency to fix CI

template-helpers/breach-detail.js
Fixes #1476
Additional data classes with more personal space:
=> Fix additional,data,class,spacing

controllers/user.js
=> Fix false negative breach report emails

template-helpers/breach-detail.js, template-helpers/dashboard.js, views/partials/recommendation.hbs
=> Add utm parameters to recommendation links

locales/en/data-classes.ftl
Ref: https://github.com/mozilla/blurts-server/issues/1514#issuecomment-578874307
See https://monitor.firefox.com/breach-details/EuropaJobs
=> Add job-applications data class

controllers/email-l10n.js, controllers/hibp.js, controllers/oauth.js, controllers/user.js, locales/en/email-strings.ftl, middleware.js, template-helpers/emails.js, views/layouts/email_l10n_mockups.hbs, views/partials/email_partials/email_single_breach.hbs
=> Update breach alert and report emails -  #1395

public/contribute.json
=> Remove IRC references from contribute.json

.travis.yml
=> Updated travis CI to use previous version of LTS

tests/integration/tests/test-securityTips-page.js
Increased tolerance for Security Tips page to account for font renderng issues
=> Update Integration Test - OS Differences 

controllers/home.js, controllers/oauth.js, controllers/user.js, controllers/utils.js, public/css/scan-results.css, public/js/fxa-analytics.js, public/js/monitor.js, scan-results.js, tests/controllers/home.test.js, views/scan.hbs
Note – I'm leaving some remnants of experiment code for future experiment usage. I'll comment on specific code that should be retained.
=> Fixed #1687 - Removed Growth Experiment 3 Code

controllers/home.js, controllers/oauth.js, controllers/user.js, controllers/utils.js, public/css/forms.css, public/css/monitor.css, public/js/fxa-analytics.js, public/js/monitor.js, scan-results.js, template-helpers/homepage.js, tests/controllers/home.test.js, views/monitor.hbs, views/partials/analytics/experiment.hbs, views/partials/forms/scan-email-form.hbs
**Note: When testing locally, add the variable `EXPERIMENT_ACTIVE=1` to your `.ENV` file.**
1. Go to https://monitor-v2.herokuapp.com/?experimentBranch=vb
1. Click "Get Started" Button
1. Go through FxA Flow 
1. Once completed, user should be on the `/user/dashboard/` page
**Control:** 
**Treatment:** 
_Note - The text is still being worked on._
=> Relaunch: Homepage FxA Experiment (Growth Exp 2)

public/css/scan-results.css, views/scan.hbs
Fixed #1710 - Added button design to FxA sign-in/up link on breach results page
=> Update Breach Results Page FxA Signup/in Button 

controllers/home.js, controllers/oauth.js, controllers/user.js, public/css/forms.css, public/css/monitor.css, public/js/fxa-analytics.js, public/js/monitor.js, scan-results.js, template-helpers/homepage.js, views/layouts/default.hbs, views/monitor.hbs, views/partials/analytics/experiment.hbs, views/partials/forms/scan-email-form.hbs
Fixes #1711
This PR roles back the Homepage FxA Experiment (#1638)
=> Remove Homepage FxA Experiment code

controllers/home.js, controllers/oauth.js, controllers/user.js, controllers/utils.js, public/js/fxa-analytics.js, public/js/monitor.js, scan-results.js, tests/controllers/home.test.js, views/layouts/default.hbs, views/partials/analytics/experiment.hbs
- Control: https://monitor-v2.herokuapp.com/?experimentBranch=va 
- Treatment: https://monitor-v2.herokuapp.com/?experimentBranch=vb
Verify you are enrolled in the experiment by looking at the `data-experiment` attribute on `<body>` tag. 
**Treatment:**
- Go to website (with FR or DE set as the language)
- Click the checkbox
- It should open FxA flow.
- When you land on the /user-dashboard after completing the flow, it should still have the same meta data as mentioned above. 
- The user MUST have either German or French variant as the primary/top language. Any other deviation will be excluded from the experiment. If the first language is NOT English, then they should not get the checkbox. If English (any variant), the default state is now to HAVE a checkbox. 
**French Homepage**
**French …
=> Growth Experiment #4 - i10n Homepage FxA Experiment

controllers/home.js, controllers/oauth.js, controllers/user.js, public/js/fxa-analytics.js, public/js/monitor.js, scan-results.js, views/layouts/default.hbs, views/partials/analytics/experiment.hbs
- Fixes #1747 
- Test with ENV variable `EXPERIMENT_ACTIVE` set to both `0` and `1`
- Test in both English and French/German.
=> Remove I10N Homepage FxA Experiment

template-helpers/articles.js
Updates Security Tips copy.
Fixes #1568
=> Update security tips copy

controllers/home.js, controllers/oauth.js, controllers/user.js, public/js/fxa-analytics.js, public/js/monitor.js, scan-results.js, views/layouts/default.hbs, views/partials/analytics/experiment.hbs
Removes active homepage FxA experiment
=> Fixed #1779 - Removed Homepage FxA Experiment

db/migrations/20200810144851_add_signup_language_index.js.js, scripts/collect-unresolved-breaches-addresses.js
See [Bug #1651817](https://bugzilla.mozilla.org/show_bug.cgi?id=1651817) for more information.
=> Unresolved Braches Cohort Selection Script

public/css/forms.css, public/js/monitor.js, views/partials/forms/scan-email-form.hbs
Fixed #1842 - Revised show/hide logic for FxA Homepage checkbox to show in English, German or French.
=> Gradaute FxA Homepage Checkbox to German/French Languages 

public/js/monitor.js
English (Checkbox visible) 
Spanish (Checkbox hidden)
=> Fixed #1919 - Revised logic to use some() method

locales/en/app.ftl
Fixes #1915 
Adding this string ahead of implementing it for L10N.
=> Add new string #1915

locales/en/data-classes.ftl
=> Add partial-dates-of-birth data class string to en locale

.circleci/config.yml
=> Change Circle Configuration to use main branch.

template-helpers/recommendations.js
We're going to go ahead and remove the FPN links completely.
=> remove fpn link and replace with VPN

locales/en/app.ftl
Adding finalized strings for #2089
=> Fix #2090 - Add strings for VPN Promo Banner

controllers/home.js, controllers/user.js, controllers/utils.js, public/css/remove-data.css, public/img/svg/data-removal-large.svg, public/img/svg/data-removal-small.svg, public/js/monitor.js, routes/home.js, views/partials/dashboards/breaches-dash.hbs, views/partials/imports.hbs, views/remove-data.hbs
This re-uses a bunch of old Relay waitlist page experiment code in pretty dumb ways, so we probably want to re-name at least a bunch of elements and styles before we would merge and launch this.
=> remove data waitlist page experiment

views/remove-data.hbs
=> Fix spelling mistake on /remove-my-data

views/remove-data.hbs
Minor update on page to fix typo. Changed "blick" to "click".
=> Fixed typo on line 23: "blick" updated to "click"

public/css/vpn-promo-banner.css, public/js/monitor.js, views/partials/vpn-promo.hbs
Note – These strings are intentionally not being translated. It is only for the next few weeks and will revert back to the previous text.
=> Fix #2193 - Add new pricing copy to the VPN promo banner

locales/en/data-classes.ftl
See https://monitor.firefox.com/breach-details/ParkMobile
=> Adding licence-plates from recent breach

views/partials/email_partials/email_footer.hbs
=> update email footer mailing address

public/js/dashboard.js
oops, need the check on `relayLink` too.
=> also check for relayLink before accessing

README.md
- remove outdated instructions
- add clearer instructions including Mailinator steps
=> update README for email triggering instructions

js-constants.js, locales/en/app.ftl, public/scss/includes/variables.scss, public/scss/partials/main.scss, public/scss/partials/remove-data.scss, template-helpers/dashboard.js, views/partials/removal/removal-result.hbs
localize the status from kanary to language of our choosing
trim trailing comma of the info found
add a separate blocked filter
=> filter and status changes

controllers/user.js, js-constants.js, locales/en/app.ftl, public/scss/partials/data-removal/remove-data.scss, views/partials/dashboards/remove-delete-confirmation.hbs
... in constants file
new language and design for cancelation page to match figma
=> add ability to add a cancelation survey link when present

controllers/user.js, js-constants.js, locales/en/app.ftl, views/partials/dashboards/remove-enroll-full.hbs, views/partials/dashboards/remove-pilot-ended.hbs
add waitlist check to account update
fix payment logic
fix pilot ended redirect check
change foxfooding start date in config
=> Mh/kanary fix ended / pmt / full scenarios

locales/en/app.ftl, views/partials/dashboards/remove-form.hbs, views/partials/data-removal/modal-birth-year.hbs
adds a modal around why we ask for DOB
=> add a modal explaining why we collect DOB

controllers/user.js, removal-constants.js
=> fix signup errors still calling old fluent method

controllers/user.js, public/scss/partials/data-removal/remove-data.scss, public/scss/partials/data-removal/remove-result.scss, removal-constants.js, remove_en/remove.ftl, views/partials/dashboards/remove-dashboard.hbs, views/partials/data-removal/modal-remove-risk.hbs, views/partials/removal/removal-result.hbs, views/partials/removal/removal-results-header.hbs
new risk level modal and modal trigger
move risk out of header and into details view
change sort order of items to complete / active / blocked
=> risk level updates

public/scss/includes/_vars.scss, remove_en/remove.ftl, views/partials/data-removal/modal-info-needed.hbs, views/partials/data-removal/modal-remove-info-found.hbs, views/partials/data-removal/modal-remove-link.hbs, views/partials/data-removal/modal-remove-optout.hbs, views/partials/data-removal/modal-remove-risk.hbs, views/partials/data-removal/modal-remove-status.hbs, views/partials/data-removal/remove-faq-title.hbs, views/partials/imports.hbs, views/partials/removal/removal-result.hbs, views/partials/top-level/remove-faq.hbs
Implement some lighthouse accessibility improvements
=> accessibility fixes from lighthouse

controllers/user.js, views/partials/dashboards/remove-form-confirm.hbs, views/partials/dashboards/remove-form.hbs
plus
fix a layout issue on the modal trigger for birth year
move the "cancel service" button to the form confirm screen and out of the form itself.
=> fix the backend validation requirement for middle name to not be empty

public/scss/includes/_vars.scss, public/scss/partials/data-removal/modal.scss
Z index for modal that prevents overlap by nav on small screens
=> give modals a z index that can sit above nav

views/partials/removal/removal-result.hbs
Fixes [https://mozilla-hub.atlassian.net/browse/FPRDS-182](https://mozilla-hub.atlassian.net/browse/FPRDS-182).
=> only display detail information if the data actually comes back from the API

views/partials/data-removal/modal-remove-info-found.hbs, views/partials/data-removal/modal-remove-link.hbs, views/partials/data-removal/modal-remove-manual.hbs
https://mozilla-hub.atlassian.net/jira/software/c/projects/FPRDS/boards/419?modal=detail&selectedIssue=FPRDS-217&quickFilter=1976
=> addresses FPRDS-217

public/js/fxa-analytics.js, public/js/remove-data.js, views/partials/dashboards/remove-dashboard.hbs, views/partials/data-removal/modal-leaving-monitor.hbs, views/partials/removal/removal-result.hbs
Implements the custom data removal analytics pings to ga.
=> add custom data removal analytics metrics

controllers/user.js
adjust edit logic so edit can't be repeated on successive attempts without param
=> adjust edit logic

package-lock.json
=> resolve `node-fetch` alert

controllers/user.js
even if kanary acct has been removed
=> allow continuation of local member cancelation from pilot mgmt 

controllers/user.js, db/DB.js, public/js/remove-data.js
add max users to getCounts function
better logic for users in DB with no KID
better output messaging
=> Admin Tool Changes:

locales/en/data-classes.ftl
See https://monitor.firefox.com/breach-details/CYberServe
=> Adding hiv-statuses data class

public/js/monitor.js, public/scss/partials/header.scss, template-helpers/hbs-helpers.js
- hide by default to avoid flash while checking cookie
- use new colors
=> update recruitment banner

.github/linter_config.yml, .github/requirements.txt, .github/workflows/reference_linter.yaml, locales/en/app.ftl, locales/en/bento.ftl, locales/en/data-classes.ftl
Not sure if this should be done against localization, or another branch.
P.S. this also checks for an empty line at the end of the files
=> Add linter for reference strings

locales/en/email-strings.ftl
=> add en strings for updated emails

src/controllers/breach-details.js, src/controllers/breach/breach-details.js, src/controllers/dashboard.js, src/routes/index.js, src/views/partials/breach-details.js, src/views/partials/dashboard.js
=> feat: add breach details page skeleton

src/client/css/global.css, src/client/css/variables.css, src/client/js/index.js, src/client/js/resize-observer.js, src/views/layouts/main.js, src/views/partials/landing.js
=> make initial template responsive

src/app.js
Safari browser requests `upgrade-insecure-requests`.  Helmet provides this secure-upgrade response by default.  This PR disables that functionality for dev environment, to allow (insecure) localhost on Safari.
=> relax forced https for localhost on Safari

locales/en/landing.ftl, src/client/css/global.css, src/client/css/landing.css, src/client/css/variables.css, src/client/images/icon-plus.svg, src/views/partials/landing.js
=> add faq details to landing page

src/app.js, src/client/js/breaches.js, src/esbuild.js, src/middleware/error.js, src/routes/api/v1/user.js, src/routes/index.js, src/utils/error.js
Added basic error handling:
* middleware to handle errors in one place
* 404 response for all the page routes
* 405 response for all the API routes
* extended error classes for better err throwing
=> Mntor-989: Error Handling

src/controllers/auth.js
Post login, the user will be forced to re-enter their password
Reference FxA fix: FXA-6155
=> MNTOR-974: force relogin after logout

src/middleware/error.js
Quick patch: error stack logging format
=> error stack fix

src/app.js, src/controllers/hibp.js, src/middleware/util.js, src/routes/api/v1/hibp.js, src/routes/index.js
* Middleware to replace `express-bearer-token`
* `notify` call for new breaches without the email notification (completed with the email epic)
=> MNTOR-976: notify

locales/en/breaches.ftl, src/app-constants.js, src/controllers/breaches.js, src/views/partials/breaches.js
Add localized count/total emails monitored to the header on breaches page
TO-DO:
- link CTA to add new email flow
=> Mntor 802/breaches email cta

locales/en/breaches.ftl, src/client/css/partials/breaches.css, src/client/css/variables.css, src/client/js/partials/breaches.js, src/views/main.js, src/views/partials/breaches.js
**Unresolved/resolved filter bar**
- display amount of resolved/unresolved breaches above table
- update the amount dynamically based on email or resolved status
- allow user to select either option and update the table with respective data
Not included:
- zero-breach results design state (under separate PR)
=> Mntor 1061/resolved filter

.circleci/config.yml, package-lock.json
Heroku is displaying the wrong version of the app. It's possible that it's due to the difference in Node version used by the build system
=> heroku fix

db/DB.js, tests/controllers/ses.test.js, tests/controllers/user.test.js
Add code from hotfixes for issue #2744:
* https://github.com/mozilla/blurts-server/pull/2745, [v15.3.2.1](https://github.com/mozilla/blurts-server/releases/tag/v15.3.2.1)
* https://github.com/mozilla/blurts-server/pull/2752, [v15.3.2.3](https://github.com/mozilla/blurts-server/releases/tag/v15.3.2.3)
Also fix remaining `eslint` issues in `db/DB.js`.
Additional work will be needed, but this ensures that `main` has the fixes in production.
=> Handle deleting a subscriber with related emails

src/utils/breach-summary.js, src/utils/breach-summary.test.js
Breach summary utility function. Returns a JSON in the following format:
```
{
monitoredEmails: {
count: 0
},
numBreaches: {
count: 0,
numResolved: 0,
numUnresolved: 0
}
}
```
breachedDataTypes utility function: returns a JSON in the following format
```
{
'test@test.com': { passwords: 1, 'email-addresses': 1, 'ip-addresses': 1, other: 0 },
'test2@test.com': { passwords: 1, 'email-addresses': 2, 'ip-addresses': 0, other: 1 }
}
```
=> MNTOR-1079: Breach summary utility funcs

docs/adr/0000-use-es-compatible-unit-test-frameworks.md, docs/adr/template.md
Jira: MNTOR-1103
Proposal on how we should use ES-compatible unit test frameworks
=> MNTOR-1103 - ADR 0000 use es compatible unit test frameworks

locales/en/app.ftl, src/views/main.js
GitHub: PR #2755
This PR addresses some accessibility improvements to the user menu list that has been introduced by PR #2755 as discussed in the PR [#2755 review comments](https://github.com/mozilla/blurts-server/pull/2755#pullrequestreview-1261141840).
=> Add accessible label to user menu

src/scripts/recencyToBreachId.js, src/utils/hibp.js
Jira: MNTOR-978
Figma: n/a
Migrating breach resolution from v1 to v2. This one-off script changes all recency indices to breach IDs 
- Resolve a few breaches in v1
- Run the syncBreaches.js script to make sure breaches are present in your db
- Run the deprecateBreachResolve script (part 1) to translate those breaches from v1 to v2
- Run this script to see the recency indices changed to breach IDs that match the breach table
=> MNTOR-978: Migrate breach resolution (part 2)

Dockerfile
Jira: MNTOR-1109
- update docker file to copy the Refresh package file `src/package.json`
- remove redundant `npm run build` command
- move permissions command before npm install
=> copy src/package.json via dockerfile

is-v2.js, package.json
Jira: MNTOR-1109
This PR updates the `npm start` script to point to the Refresh site
=> update `npm start` now points to Refresh site

src/controllers/dockerflow.js, src/routes/dockerflow.js, src/routes/index.js
Jira: MNTOR-1116
Figma: n/a
Adding docker heartbeat endpoints to root.
`/__heartbeat__` should return `OK`
`/__lbheartbeat__` should return `OK`
=> add dockerflow

src/app.js
Jira: MNTOR-1117
Figma: n/a
Auth state isn't being persisted because stage/prod also has nginx set up and we need to pass a flag to node to trust the proxy
=> MNTOR-1117: Fix auth state issue

locales/en/data-classes.ftl
Jira: MNTOR-
Figma: 
Fixes #2808
=> Add vehicle-identification-numbers-vins data class

src/utils/hibp.js
Jira: MNTOR-1144
Figma: n/a
Fixing subscription fetch call. 
* Should be able to verify emails now
=> MNTOR-1144: fixing sub calls

src/views/email-2022.js
Jira: [MNTOR-1150](https://mozilla-hub.atlassian.net/browse/MNTOR-1150)
Only some of the email gods might know why, but for some reason, the logo header style got stripped by all email clients I checked. This also leads to the rest of the header having a layout shift in Outlook. This PR fixes both of those issues.
=> MNTOR-1150: Fix email template header style

locales/en/breaches.ftl, src/client/css/partials/breaches.css, src/client/css/variables.css, src/views/partials/breaches.js
Jira: MNTOR-1063
Figma: https://www.figma.com/file/gvyyqS9egsGjsH0LUDqT1m/Breach-Resolution-Flow-Design?node-id=718%3A17412&t=ATIHyZinZSEWEuOn-4
Adds a badge indication a breach's resolution status. Tried to comply with all conventions I saw, but let me know if there are more - for example, possibly some guidance on how to add a unit test for the function detecting whether a breach has been resolved?
View the breaches dashboard. Every listed breach should have a badge - if all steps have been completed, it should be "Resolved", otherwise it's "Active".
=> Add a badge indication a breach's resolution status

locales/en/data-classes.ftl
See https://monitor.firefox.com/breach-details/Weee
Jira: MNTOR-
Figma: 
=> Add delivery-instructions data class

docs/adr/0002-test-and-release-process.md
Jira: MNTOR-1162
A proposal intended to balance the desire to keep a high quality bar for features in Monitor V2, while reducing the amount of new manual process required of individuals.
=> MNTOR-1162 - proposal for test+release process for Monitor V2

src/client/css/partials/breaches.css
See https://github.com/mozilla/blurts-server/pull/2817#discussion_r1100549633.
=> Use relative unit for font size

.gitignore, .vscode/extensions.json, .vscode/settings.json, README.md, package-lock.json, src/package.json
Jira: MNTOR-1113
Follow up from https://github.com/mozilla/blurts-server/pull/2772#issuecomment-1399158668
This is an example of how to have a shared set of recommended extensions and settings for VSCode - personally I'd prefer this to having to follow instructions in the readme, and it helps us to be able to make sure the settings and extensions aren't stale.
=> MNTOR-1113 Shared VSCode settings

.eslintrc.json, package-lock.json, src/client/js/partials/add-email.js, src/client/js/user-menu.js, src/controllers/dockerflow.js, src/package.json, src/routes/admin.js, src/routes/dockerflow.js, src/scripts/convertBreachResolutions.js, src/scripts/recencyToBreachId.js, src/utils/breaches.js, src/views/dialog.js, src/views/partials/email-breach-card.js, src/views/partials/email-signup-report.js
In response to https://github.com/mozilla/blurts-server/pull/2832#discussion_r1106318187.
=> Add ESLint plugin to enforce the licence header

src/client/css/nav.css, src/client/css/variables.css
=> Incorporate UX feedback for navigation design update

public/css/app.css
I accidentally added this import in the wrong file while I was still figuring out the codebase.
=> Remove unused import

src/controllers/settings.js
Jira: MNTOR-1199
Figma: n/a
Additional settings fix
=> MNTOR-1199: settings fix

.eslintrc.json, package-lock.json, src/package.json
Putting this up as a draft in response to https://github.com/mozilla/blurts-server/pull/2838#discussion_r1108802218 for discussion.
This enables all the “recommended” rules by `eslint-plugin-jsdoc`. Are we all in favor of adding these rules, just a subset — or not at all?
=> Add eslint-plugin-jsdoc

src/utils/email.js, src/utils/email.test.js
Jira: [MNTOR-1259](https://mozilla-hub.atlassian.net/browse/MNTOR-1259)
Updates the email CTAs to link directly to the dashboard.
Send an email via the email previewer and follow a CTA that links back to the dashboard.
=> Update email CTAs to directly link to the dashboard

src/client/js/components/toast-alert.js
Jira: MNTOR-1276
The toast alert component disables the auto-hide feature after a user has interacted with the toast – by `mouseover`, for example.  This can be confused for a bug if the user inadvertently hovers over the toast and it's left on screen indefinitely.
This PR enhances the functionality to pause the auto-hide feature on mouse-over, and resume auto-hide on mouse-out.
1. trigger a toast alert (on Settings page by clicking "Resend verification" multiple times, for example)
2. hover over a toast for at least 6 seconds, confirming it does not disappear
3. remove your mouse from the toast area, confirming it auto-hides
=> refactor to auto-hide toast after interaction

locales/en/breaches.ftl, src/views/partials/breaches.js
Jira: MNTOR-1319
Figma: N/A
I don't have to do anything else to make a string available for localisation, correct?
=> Localise "Resolve this breach" heading

locales/en/data-classes.ftl
```sh
npx pdehaan/blurts-server-data-classes
Missing "loan-information" data class from HDBFinancialServices breach
Missing "loan-information" data class from MyFHA breach
```
Jira: MNTOR-
Figma: 
=> Add "loan-information" string to data-classes.ftl

src/controllers/notFound.js
=> Actually mark a 404 page as a 404

src/routes/user.js
=> MNTOR-1327: explicit temp redirect

locales/en/breaches.ftl
Spaces in between { and }, and updating an outdated comment, as per https://github.com/mozilla/blurts-server/pull/2900#pullrequestreview-1339727027
=> Clean up some l10n strings

src/scripts/prod-experiments/benchmarkNoUpsert.js, src/scripts/prod-experiments/pullExperiment100.js, src/scripts/prod-experiments/pullExperiment1000.js
We need to benchmark the migration script's performance in order to estimate how long they will run against a large dataset
=> MNTOR-1395: Some benchmark tests for prod migration

src/scripts/prod-experiments/benchmarkNoUpsert.js, src/scripts/prod-experiments/pullExperiment1000.js
=> Mntor 1395

src/scripts/prod-experiments/benchmarkWithUpsert.js
Do updates in batches, should increase the speed of the write to db
=> MNTOR-1395: batch update

db/migrations/20230322233844_add-db-migration-processing.js, src/scripts/kube-jobs/convertBreachResolutions.js, src/scripts/prod-experiments/benchmarkWithUpsert.js
This modified version of the resolution conversion script is meant to be run in parallel as a kube job. It modifies a temp column acting as a row lock, so other kube jobs can bypass those rows.
=> MNTOR-1395: kube job convert breach resolution script

src/scripts/kube-jobs/recencyToBreachId.js
Figma: 
Switch recencyToBreachId to async mode so it can be ran as a kube job
=> MNTOR-1395: add async script for recencyToBreachId

src/views/guestLayout.js, src/views/partials/breach-detail.js, src/views/partials/breaches.js, src/views/partials/landing.js
=> MNTOR-1437 Instrument CTAs in authenticated pages for GA

src/client/js/components/toast-alert.js, src/client/js/dialog.js, src/client/js/partials/breaches.js, src/client/js/partials/notFound.js, src/client/js/partials/settings.js, src/client/js/partials/unsubscribe.js, src/client/js/user-menu.js
https://support.google.com/analytics/answer/13316687
I also went over and instrumented a few more success/fail cases, they are sent in a `result` parameter.
=> MNTOR-1437 Do not use spaces in event names, per GA4's event naming rules

src/scripts/kube-jobs/convertBreachResolutions.js, src/scripts/kube-jobs/recencyToBreachId.js
Figma: 
HIBP sometimes returns error for fetching breaches. We will log the incident and skips over the subscriber
=> MNTOR-1395: logs err if hibp fetch ever errs out

src/client/js/dialog.js, src/client/js/partials/add-email.js, src/client/js/partials/breaches.js, src/client/js/partials/notFound.js, src/client/js/partials/settings.js, src/client/js/partials/unsubscribe.js, src/client/js/user-menu.js, src/views/guestLayout.js
Jira: MNTOR-1437
Updated event names to match S&P products taxonomy
=> MNTOR-1437 fixup: use names from S&P taxonomy

src/scripts/kube-jobs/convertBreachResolutions.js, src/scripts/kube-jobs/recencyToBreachId.js
Testing the performance of script when we up the limit to 2000 records / job
=> MNTOR-1395: up the limit to 2000

src/scripts/kube-jobs/convertBreachResolutions.js, src/scripts/kube-jobs/recencyToBreachId.js
Limit with 2000 took longer to run, reverting back to 1000
=> MNTOR-1395: reverting to 1000

src/client/css/partials/breachDetails.css, src/views/partials/breach-detail.js
Jira: MNTOR-1494
Figma: N/A
The icon is now inline wit the company title, and smaller. It's still larger than a regular favicon and so might still be a little bit blurry, but less obvious than it was.
Blurry:
Sharp:
Fallback:
Open a public breach page.
=> Make the logo on the breach detail page smaller

src/scripts/migrationCleanup.js
Jira: MNTOR-1492
After the migration, we had ~30k records that were migrated properly due to a database connection issue. This script fixes those records
=> MNTOR-1492: migration cleanup script

src/client/css/partials/breachDetails.css
Jira: [MNTOR-1533](https://mozilla-hub.atlassian.net/browse/MNTOR-1533)
Minor adjustments to the layout for the breach detail header.
| Before (390px) | Before (900px) |
| --- | --- |
| <img width="387" alt="mntor-1533-before-390" src="https://user-images.githubusercontent.com/13835474/231141740-24c94fa9-8f7d-4477-8154-d1f1f55fce95.png"> | <img width="680" alt="mntor-1533-before-900" src="https://user-images.githubusercontent.com/13835474/231141758-2609c36e-e721-4e2b-b0b8-0e48afce71a0.png"> |
| After (390px) | After (900px) |
| --- | --- |
| <img width="387" alt="mntor-1533-after-390" src="https://user-images.githubusercontent.com/13835474/231141870-a4bc01a1-0fc1-4616-9478-aa4a24f09faa.png"> | <img width="681" alt="mntor-1533-after-900" …
=> chore: Adjust breach detail header layout

README.md, docs/monitor-emails.md, src/app.js
=> Update ReadMe: legacy cleanup

.circleci/config.yml
Circle CI deployment pipeline seems to be broken, the changes aren't getting picked up by Jenkins to deploy to stage. 
* Add a tag
* Watch circle CI
=> Fix Circle CI Deploy

.circleci/config.yml
Jira: MNTOR-1591
Tagged deploy isn't working, causing staged deploy from not being able to be kicked off
=> MNTOR-1591: fix circle ci config

src/views/partials/breachDetail.js
Jira: MNTOR-
Figma: 
Fixes #2986 
=> Add missing size+alt attributes to more.svg img

docs/adr/0004-framework.md
Jira: [MNTOR-1588](https://mozilla-hub.atlassian.net/browse/MNTOR-1588)
Add ADR for proposed migration to React front-end framework
=> ADR Proposal: Add React Framework

src/controllers/fxaRpEvents.js
Jira: MNTOR-981
Better debugging for an unknown stage issue
=> better debugging for sentry

README.md, package-lock.json, package.json, src/functions/index.js, src/functions/index.test.js, tsconfig.json
Jira: MNTOR-1539
Split the `hibp` controller out of the main Monitor app and into a standalone GCP Cloud Function. This controller handles the `/api/v1/hibp/notify` route and is responsible for:
1. receiving webhook notifications from HIBP
2. checking the auth token and looking in Postgres (using k-anon) for any impacted users
3. creating a localized email template and emailing any impacted users
Prereq: local Postgres DB with breaches and an impacted email address
```sh
npm run functions
curl \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer unsafe-default-token-for-dev' \
-X POST \
-d '{"breachName": "Gravatar", "hashPrefix": "...", "hashSuffixes": ["..."]}' \
localhost:8080/api/v1/hibp/notify
```
This API is expected to be called via a webhook from HIBP.
=> Mntor 1539/separate data ingestion

src/cloud-functions/index.js
Jira: MNTOR-1539
Use new error classes from refactoring in PR #3010
=> fix: use new error classes from cloud function

src/client/js/partials/breaches.js, src/views/partials/breaches.js
Jira: MNTOR-1659
Instrument the user opening/closing the breach details card for GA.
1. open and close the breach details card
2. look for a ping to GA with a payload containing the following:
```
en: toggled_breach_card
ep.debug_mode: true
ep.action: opened
ep.company_name: Gravatar
```
You can also confirm using the "DebugView" feature in the GA dashboard that pings are coming in and contain the correct data.
=> MNTOR-1659 - instrument breach card open/close for GA

src/app/api/v1/user/breaches/route.ts
Jira: MNTOR-1630, MNTOR-1627
* Get breaches for user
* Modify breach resolution for user
Porting the following endpoints to NextJS
`GET http://localhost:6060/api/v1/user/breaches`
`PUT http://localhost:6060/api/v1/user/breaches`
1. Before login, test redirect. If you go to `http://localhost:6060/api/v1/user/breaches` without logging in, you will be redirected to home
2. Login
3. Use the `GET` call to get the list of breaches for your account
4. Test `PUT` by sending the following body:
```json
{
"affectedEmail": "your@email.com",
"breachId": "your breach id",
"resolutionsChecked": ["...", "..."]
}
```
=> Mntor-1630: Breaches GET/PUT

src/app/[slug]/route.ts, src/controllers/dockerflow.js
Jira: MNTOR-1818
Adding a route to display current version being deployed
https://.../__version__
=> MNTOR-1818: adding /__version__

Dockerfile
Fix stage build by adding build step in docker
=> add build step in dockerfile

.storybook/main.ts, package-lock.json, package.json
This will make it easier to detect and debug accessibility issues inside Storybook. It adds an accessibility tab to the UI underneath a story, outlining potential issues. AFAIK this also uses Axe, so it should be helpful in visually debugging test failures once we add axe failures to our unit test suite.
Try it out here: https://deploy-preview-3129--fx-monitor-storybook.netlify.app
=> Add accessibility add-on for Storybook

.git-blame-ignore-revs, .prettierignore, src/app/(nextjs_migration)/(authenticated)/user/breaches/page.tsx, src/app/(nextjs_migration)/(guest)/breach-details/[breachName]/page.tsx, src/app/(nextjs_migration)/(guest)/page.tsx, src/app/(nextjs_migration)/layout.tsx, src/app/(proper_react)/MobileShell.module.scss, src/app/(proper_react)/Shell.stories.tsx, src/app/(proper_react)/Shell.tsx, src/app/[slug]/route.ts, src/app/api/utils/auth.ts, src/app/api/utils/email.ts, src/app/api/v1/fxa-rp-events/route.ts, src/app/api/v1/premium/route.ts, src/app/api/v1/scan/route.ts, src/app/api/v1/user/email/route.ts, src/app/api/v1/user/resend-email/route.ts, src/app/components/client/Modal.tsx, src/app/components/client/ProgressCard.module.scss, src/app/components/client/ProgressCard.tsx, src/app/components/client/stories/ProgressCard.stories.ts, src/app/fonts/Metropolis/metropolis.ts, src/app/functions/server/breachResolution.ts, src/app/functions/server/getBreaches.ts, src/app/functions/server/getUserBreaches.ts, src/app/functions/server/l10n.ts, src/app/globals.css, src/app/hooks/l10n.ts, src/app/tokens.scss
~There are a couple of formatting inconsistencies that we do not lint and enforce. These rules in this PR are just a proposal and the intention is to start a conversation around additional rules we would like to follow.~
Edit: There are a couple of formatting inconsistencies that we do not enforce for `src/app`.
=> Do not ignore formatting in src/app

src/app/functions/server/getBreaches.ts
OK, so I haven't been able to properly set up performance monitoring myself yet, which means I'm shooting in the dark, which I don't like. Also, this code keeps getting iffier and iffier.
That said, [this trace](https://mozilla.sentry.io/performance/summary/?project=4504612374052864&query=&referrer=performance-transaction-summary&statsPeriod=14d&transaction=Page+Server+Component+%28%2Fbreaches%29&unselectedSeries=p100%28%29) seems to suggest that fetching icons can take a looong time, _and_ is delaying returning a response. So in this PR, I wrapped the whole thing in an async function, and then simply return an empty map while that function is executing. Once it's done, future function calls can get a non-empty map with initialised icons - but until then, at least the server should …
=> Don't block responses while downloading images

package.json
This reverts commit 6d11d7d86bbab53f79b00b5ac804a3e7daddfca6.
=> Revert "Start local built server on same port as dev one"

src/client/css/nav.css
Jira: [MNTOR-1872](https://mozilla-hub.atlassian.net/browse/MNTOR-1872)
| Before | After |
| --- | --- |
| <img width="388" alt="mobile-icon-before" src="https://github.com/mozilla/blurts-server/assets/13835474/bdbb56e3-1061-4d4b-b668-f134113278d1"> | <img width="389" alt="mobile-icon-after" src="https://github.com/mozilla/blurts-server/assets/13835474/fabb325d-9bc1-4316-b2c9-276df06a8a9e"> |
=> Mobile nav icon alignment

src/scripts/syncBreaches.js
Jira: MNTOR-1882
Adding monitoring of cronjob in Sentry. 
See the monitor details in sentry below (screenshot) 
* Merge code into stage
* wait for cronjob to execute
* Make sure checkins show up
* If no check in, make sure an email alert is received
=> MNTOR-1882: add sentry monitoring

src/views/emails/email2022.js
Jira: MNTOR-1881
Change co address
=> MNTOR-1881: change company address

public/nextjs_migration/client/js/welcome-details.js, public/nextjs_migration/client/js/welcome.js, src/app/(nextjs_migration)/(authenticated)/user/breaches/page.tsx, src/app/(proper_react)/redesign/(authenticated)/user/welcome/details/page.tsx, src/app/(proper_react)/redesign/(authenticated)/user/welcome/page.tsx, src/app/(proper_react)/redesign/(authenticated)/user/welcome/remove/page.tsx, src/app/(proper_react)/redesign/(authenticated)/user/welcome/results/page.tsx, src/app/(proper_react)/redesign/(authenticated)/user/welcome/scanning/page.tsx, src/app/api/v1/user/welcome/route.ts, src/app/functions/server/isUserSubscribed.ts, src/app/functions/server/onerep.ts, src/db/migrations/20230623072741_add_unique_constraint_onerep_profile_id.js, src/db/migrations/20230623152940_add_onerep_scans_table.js, src/db/migrations/20230703010356_add-onerep-profiles-table.js, src/db/tables/onerep_profiles.ts, src/db/tables/onerep_scans.ts, src/db/tables/subscribers.js, src/knex-tables.d.ts
Jira: MNTOR-1403
Basic UI for testing broker scanning and removal.
Using the sandbox key (which always returns fabricated results):
1. Make sure to run DB migrations to add new tables and columns (`npm run db:migrate`)
2. Visit the "Welcome" flow at /redesign/user/welcome/
3. Proceed through free scan steps, and verify that screens defined in Figma appear
4. Verify that (fabricated) scan results are shown, and offer to subscribe to premium is offered
5. Subscribe to premium and verify that removal can be requested
6. Verify that removal succeeds
7. Unsuscribe from Premium and verify that data remains, but no new scans are performed and data removal cannot be requested for new scans
7a. NOTE: to set up this test, we need to figure out how to avoid waiting for a month for the cancellation …
=> MNTOR-1403/data removal action and scan

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/page.tsx
Fixes the dashboard route protection and redirect url.
=> fix: Dashboard route protection

locales-pending/premium.ftl
=> Fixing l10n linter errors/warnings

src/app/(nextjs_migration)/components/client/SignInButton.tsx
Redirect back to the URL that initiated authentication if not explicitly set otherwise.
=> Redirect to auth trigger URL

docs/adr/0000-use-es-compatible-unit-test-frameworks.md, docs/adr/0007-unit-testing-framework.md
- Jira Ticket: [MNTOR-1823](https://mozilla-hub.atlassian.net/browse/MNTOR-1823)
=> ADR: Unit Testing Framework

.storybook/preview.tsx
It would result in the following error:
> invariant expected app router to be mounted
=> Fix stories for components using useRouter

.github/workflows/playwright.yml
Jira: MNTOR-1937
Shorten the time for playwright test github action from **~13** minutes to **~4** minutes
=> MNTOR-1937: caching playwright browser

Dockerfile
Revert shared volume (for Nimbus/Cirrus) until SRE finishes debugging.
=> revert sharing volume with Cirrus container

config/nimbus.yaml
Small correction to channel names, and update to description to match Monitor.
=> fix: update channels per Nimbus team

src/db/tables/featureFlags.ts
Jira: MNTOR-2059
Feature flags add/update should guard against some edge cases:
* allow/wait lists should ignore whitespaces
* allow/wait lists should not accept empty strings
* allow/wait lists should not accept extra commas between/before/after array elements
`/redesign/admin/feature-flags`
=> MNTOR-2059: Feature flags add/update edge cases

src/app/api/v1/fxa-rp-events/route.ts
Jira: MNTOR-1923, MNTOR-1948
Adding webhook functions on top of MNTOR-1948
Replacing #3293
=> Mntor-1923: Monitor premium sub fxa event handler

src/e2e/pages/authPage.js, src/e2e/pages/landingPage.js, src/e2e/specs/landing.spec.js, src/e2e/utils/helpers.js
Jira: [MNTOR-2066](https://mozilla-hub.atlassian.net/browse/MNTOR-2066)
Add automation to verify landing page footer redirect links [ref URL](https://testrail.stage.mozaws.net/index.php?/cases/view/2095095)
=> add automation to verify landing page footer redirect links

src/app/components/client/ExposuresFilter.tsx, src/app/components/client/ExposuresFilterExplainer.tsx, src/app/components/client/ProgressCard.tsx
With <Button> [now using the `useButton` API](https://github.com/mozilla/blurts-server/pull/3314/commits/f8f7a9cde024713ef78a5cc4152e1e6f1be44c23#diff-9cac64450b7906746c3e4059bce8f1030b99978efacdcea138ee5a8acb3da150), onClick is deprecated and replaced by onPress.
=> Use onPress for <Button>s

src/app/components/server/Icons.tsx
This would've saved @codemist a lot of time debugging a failing test :sweat_smile:
=> Ensure we don't forget to pass alt text for icons

src/e2e/pages/settingsPage.js, src/e2e/specs/settings.spec.js, src/e2e/utils/helpers.js
Automation to verify breach alert notification preference selectors
=> automate breach alert preference select behavior

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/high-risk-data-breaches/HighRiskBreachContent.tsx
=> Remove alt titles for breach resolution imgs

locales-pending/fix.ftl
=> MNTOR-2035: moz brand

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/security-recommendations/securityRecommendationsData.tsx
Jira: [MNTOR-1718](https://mozilla-hub.atlassian.net/browse/MNTOR-1718) & [MNTOR-1720](https://mozilla-hub.atlassian.net/browse/MNTOR-1720)
Adds UTM params to Relay links in security recommendations.
[MNTOR-1718]: https://mozilla-hub.atlassian.net/browse/MNTOR-1718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MNTOR-1720]: https://mozilla-hub.atlassian.net/browse/MNTOR-1720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add UTM params to Relay link in security recommendations

src/app/(proper_react)/redesign/(authenticated)/user/welcome/FindExposures.tsx
Increases the exposure scan duration to `60s`.
=> Increase exposure scan duration

src/app/api/v1/stats/route.ts
Jira: MNTOR-
Figma: 
Fix return type to int
=> fix int type for stats

.circleci/config.yml, .gitignore, .prettierignore, Dockerfile, README.md, package-lock.json, package.json, src/app/(nextjs_migration)/(guest)/page.tsx, src/app/(nextjs_migration)/components/client/PageLoadEvent.tsx, src/app/hooks/useGlean.ts, src/middleware.ts, src/telemetry/metrics.yaml
Re-land Glean.js integration, with working Docker and Heroku builds.
=> MNTOR-2022/re-land glean.js

src/apiMocks/mockData.ts, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.stories.tsx, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.test.tsx, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.tsx, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/ManualRemoveView.tsx, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/page.tsx, src/app/components/server/StatusPill.tsx, src/app/functions/server/dashboard.ts
Jira: MNTOR-2015
Figma: N/A
Note: this builds on https://github.com/mozilla/blurts-server/pull/3405. Also, 100% coverage should be fixed by https://github.com/mozilla/blurts-server/pull/3407.
This allows us to view (and test) all relevant permutations of user data on the dashboard. Specifically:
- Is the user in the US or outside of it?
- Do they have Premium or not?
- Have they run a data broker scan yet? If yes, did they get results, and if yes, did they resolve them all?
- Did they have breaches and, if yes, did they resolve them all?
There should be a story for every possible combination. And because those permutations can be controlled through the `<DashboardWrapper>`'s props, it should be easier to write unit tests that verify a particular property, and that it holds under every …
=> Bring structure to our dashboard Storybook stories

src/app/api/v1/hibp/notify/route.ts, src/app/functions/server/featureFlags.ts
Jira: MNTOR-2194
- implement code changes suggested in https://cloud.google.com/pubsub/docs/troubleshooting#admin
- handle any exceptions while connecting to PubSub, to prevent unhandled exceptions
- add feature flag for HIBP so we can control when it goes live
=> MNTOR-2194 hibp notify quota fix

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/automatic-remove/page.tsx, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/view-data-brokers/AboutBrokersIcon.tsx, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/high-risk-data-breaches/HighRiskBreachLayout.tsx, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/leaked-passwords/LeakedPasswordsLayout.tsx, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/security-recommendations/SecurityRecommendationsLayout.tsx, src/app/(proper_react)/redesign/(authenticated)/user/welcome/EnterInfo.tsx, src/app/(proper_react)/redesign/(authenticated)/user/welcome/GetStarted.tsx, src/app/(proper_react)/redesign/(authenticated)/user/welcome/Onboarding.test.tsx, src/app/components/client/Chart.tsx, src/app/components/server/Button.tsx
Otherwise, you can't activate the button using the keyboard.
=> Use onPress for every <Button> instance

src/app/(nextjs_migration)/(authenticated)/user/layout.tsx
Jira: [MNTOR-2231](https://mozilla-hub.atlassian.net/browse/MNTOR-2231)
The env variable name has been changed from `FXA_SETTINGS_URL` to `NEXT_PUBLIC_FXA_SETTINGS_URL`.
[MNTOR-2231]: https://mozilla-hub.atlassian.net/browse/MNTOR-2231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix FxA user menu link

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/subscribed/page.tsx, src/app/api/v1/onerep-events/route.ts, src/app/api/v1/user/welcome-scan/create/route.ts, src/app/api/v1/user/welcome-scan/progress/route.ts, src/db/migrations/20230921132056_add_status_column.js, src/db/tables/onerep_scans.ts
The website has to display different content (https://github.com/mozilla/blurts-server/pull/3431) depending on whether the scan is already finished, or still in progress, so we need to keep track of that too.
Jira: MNTOR-2009
=> Store scan status in our database

locales-pending/fix.ftl, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.tsx, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/FixView.tsx, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/ManualRemoveView.module.scss, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/ManualRemoveView.tsx, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/RemovalCard.tsx, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/fix.module.scss, src/app/components/client/ExposureCard.tsx, src/app/components/server/StatusPill.tsx
(Sorry @flodolo, I removed trailing whitespace in the `.ftl` and now you got tagged.)
Jira: MNTOR-2084
Figma: https://www.figma.com/file/CaEKIhvSJqf6KNIMzSkt40/Concepts-for-Monitor-MVP-Redesign?type=design&node-id=1290-62939&mode=dev
This builds on https://github.com/mozilla/blurts-server/pull/3469, ~~but I also needed some stuff from `main`, so since that hasn't been reviewed yet I merged `main` in here, so I don't think the full diff here is relevant.~~ _All caught up, diff should be fine now._ Once the other PRs get merged in I can rebase, unless someone calls out that they've already started reviewing here.
This adds the list of scan results to the guided experience when someone chooses to manually deal with them, and allows marking them as resolved.
Visit …
=> Manually resolve exposures

locales/en/settings.ftl, src/app/(nextjs_migration)/(authenticated)/user/settings/page.tsx
With apologies to the localisers - I missed a word :(
Jira: MNTOR-1852
=> Refer to Mozilla *account* settings

.storybook/preview.tsx
PR #3643
This adds a session provider to Storybook which should also fix the unit test failures.
=> Fix: Add session provider to Storybook

src/scripts/emailBreachAlerts.js
Jira: MNTOR-2327
hot fix for stage
=> MNTOR-2327: fixed breachId

src/db/tables/breaches.js
=> use console instead of logger

src/db/tables/emailAddresses.js
=> remove winston from emailAddresses.js

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/DashboardTopBanner/DashboardTopBanner.module.scss, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/DashboardTopBanner/DashboardTopBannerContent.module.scss, src/app/components/client/Chart.module.scss, src/app/components/server/button.module.scss
Jira: [MNTOR-2300](https://mozilla-hub.atlassian.net/browse/MNTOR-2300)
Handle dashboard layout for smaller viewports more gracefully.
[MNTOR-2300]: https://mozilla-hub.atlassian.net/browse/MNTOR-2300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MNTOR-2300: Handle dashboard layout for smaller viewports more gracefully

src/db/tables/email_notifications.js
Jira: MNTOR-2327
Figma: 
Fix a typo in table name
=> MNTOR-2327: fix typo

src/app/components/client/PremiumButton.tsx
=> MNTOR-2382 - Add getPremiumSubscription links to premium upsell dialog

src/scripts/syncBreaches.js
Jira: MNTOR-2421
Handle unhandled errors when logo output to directory failed (harmless)
It's totally ok / expected that some logos already exist in the local cache
=> MNTOR-2421: handling errors via err log with tmp output await

next.config.js
=> sourcemap for next

src/db/tables/email_notifications.js, src/scripts/emailBreachAlerts.js
Jira: MNTOR-2281
* Added forUpdate for insert/update functions for `email_notifications` table
* Instead of throwing error, logs and quits the script when `add` fails
=> MNTOR-2281: Prevent race condtions for insert/update

src/db/connect.js
=> fix: knexfile.js

package-lock.json, package.json, src/app/(proper_react)/redesign/(authenticated)/user/welcome/EnterInfo.tsx, src/app/components/client/ComboBox.tsx, src/app/components/client/InputField.tsx, src/app/components/client/ListBox.tsx, src/app/components/client/LocationAutocompleteInput.tsx, src/app/components/client/TabList.tsx
This reverts PR #3744 due to a regression with the city/state dialog in the free scan welcome page.
=> Revert PR #3744

locales-pending/landing-all.ftl, locales-pending/landing-premium.ftl, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/page.tsx, src/app/(proper_react)/redesign/(public)/HeroImage.tsx, src/app/(proper_react)/redesign/(public)/LandingView.module.scss, src/app/(proper_react)/redesign/(public)/LandingView.stories.tsx, src/app/(proper_react)/redesign/(public)/LandingView.test.tsx, src/app/(proper_react)/redesign/(public)/LandingView.tsx, src/app/(proper_react)/redesign/(public)/SignUpForm.tsx, src/app/(proper_react)/redesign/(public)/page.tsx, src/app/functions/server/onerep.ts
Jira: MNTOR-2471
Figma: https://www.figma.com/file/YqpVpUbSTzZMj9Jbp2po8Q/Mozilla-Monitor-Premium-LP?node-id=1942%3A12635&mode=dev
This is the first part of the landing page - the hero image and the top navbar (without the in-page links in there), and starting signup with the email address you enter.
See Storybook.
Run the app, then visit `/redesign`. If you enter an email address and click "Get free scan", it will take you to FxA and prefill that email address.
=> MVP landing page for international users

playwright.config.js, src/e2e/pages/dashBoardPage.ts, src/e2e/specs/dashboard.spec.ts
Jira: [MNTOR-2389](https://mozilla-hub.atlassian.net/browse/MNTOR-2389)
verifying correct message is displayed in the action needed tag tab when all the exposures are fixed
[MNTOR-2389]: https://mozilla-hub.atlassian.net/browse/MNTOR-2389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> verifying correct message is displayed in the action needed tag tab

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.test.tsx, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/automatic-remove/AutomaticRemove.test.tsx, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/ManualRemove.test.tsx, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/high-risk-data-breaches/[type]/HighRiskBreachLayout.test.tsx, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/leaked-passwords/[type]/LeakedPasswordsLayout.test.tsx, src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/security-recommendations/[type]/SecurityRecommendations.test.tsx, src/app/components/client/PremiumUpsellDialog.tsx, src/app/components/server/Button.tsx, src/app/hooks/__mocks__/useTelemetry.ts, src/app/hooks/useTelemetry.ts
Jira: MNTOR-2343
Figma: https://www.figma.com/file/LGjPMlfA7Li3xkS5YZ6VLY/Attribution-Documentation?type=whiteboard&node-id=156-31792&t=6qaaSpfRCWMPPiHA-4
The instrumentation for the "Get yearly plan" link doesn't work yet, because that's a link, and the page navigates away (and unloads the JavaScript) before the event could be sent. (Edit: [this should get dealt with in upstream Glean](https://matrix.to/#/!SCdsJdSTaQHjzEVrAE:mozilla.org/$muLULIgsOMaLwe3HR6HI_oJbMkyD5gZBoRN3GmDL8Ko).) I figured I'd submit the rest for review already to catch potential other issues.
Some other things of note are:
- The Figma refers to `clicked_cta`, but for things other than the actual purchase button, I used `button`, since they're not actually CTAs.
- I also stuck to the available parameters from …
=> Instrument Premium purchase dialog

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/start-free-scan/StartFreeScan.stories.tsx
Clearly _some guy_ did a slopy copy-paste job here :unamused:
=> Align story variable with name and filename

src/telemetry/metrics.yaml
Figma: 
Adding `popup_id` to `popup.exit`
`npm run build`
=> add popup_id to exit action

locales-pending/dashboard-premium.ftl
[As per Mel](https://mozilla.slack.com/archives/CEV7MGSQH/p1704385768435909?thread_ts=1704359607.505119&cid=CEV7MGSQH), followup to https://github.com/mozilla/blurts-server/pull/3953#discussion_r1441456416.
=> No dash in "in progress"

locales/en/app.ftl
Jira: MNTOR-2702
Figma: https://www.figma.com/file/51jgudmkBoMMU9twT7UOKB/Monitor-Plus-Launch?type=design&node-id=310-6816&mode=design&t=PAVHr1PiURqF4TxK-0
=> Add strings for the rebrand announcement banner

src/app/(proper_react)/redesign/(public)/LandingView.module.scss, src/app/(proper_react)/redesign/(public)/LandingView.test.tsx, src/app/(proper_react)/redesign/(public)/LandingView.tsx, src/app/(proper_react)/redesign/(public)/page.tsx, src/app/components/client/SignInButton.tsx
=> Add a "sign in" button to the landing page

catalog-info.yaml
Jira: MNTOR-2733
Catalog info file for Backstage Pilot
=> MNTOR-2733: catalog info for Backstage

src/e2e/specs/auth.spec.ts
fixing e2e smoke test suite affected by recent redesign changes
Jira: [MNTOR-2732](https://mozilla-hub.atlassian.net/browse/MNTOR-2732)
[MNTOR-2732]: https://mozilla-hub.atlassian.net/browse/MNTOR-2732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix e2e smoke tests

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/start-free-scan/StartFreeScanView.tsx
Jira: [MNTOR-2731](https://mozilla-hub.atlassian.net/browse/MNTOR-2731)
Fix the “Skip free scan” link to point to the next guided step.
[MNTOR-2731]: https://mozilla-hub.atlassian.net/browse/MNTOR-2731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Skip free scan link (MNTOR-2731)

.vscode/extensions.json, .vscode/settings.json
This primarily ensures that people automatically remove trailing whitespaces for Fluent files, which fail the linter.
Additionally, it adds two relevant recommended extensions, and aligned settings for different languages.
=> Refine setup for VSCode users

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/EmailAddressAdder.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/EmailListing.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/SettingsPage.test.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/View.tsx, src/app/(proper_react)/(redesign)/(public)/LandingView.tsx, src/app/components/client/TelemetryLink.tsx
Jira: MNTOR-2345
Figma: https://www.figma.com/file/LGjPMlfA7Li3xkS5YZ6VLY/Attribution-Documentation?type=whiteboard&node-id=135-15497&t=ieTQmKUaVFwqkWI1-4
(Based on #4033 to avoid potential conflicts.)
Add an email address, click the links to FxA, close the add email dialog, delete an email address - you should see events showing up [in the event stream](https://debug-ping-preview.firebaseapp.com/stream/fx-monitor-local-dev). Make sure to disable DoNotTrack.
=> Count interactions with the settings page

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/automatic-remove/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/manual-remove/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/start-free-scan/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/view-data-brokers/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-premium/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/[type]/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/[type]/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/[type]/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/page.tsx, src/app/api/v1/admin/users/[primarySha1]/route.ts, src/app/api/v1/fxa-rp-events/route.ts, src/app/api/v1/user/welcome-scan/progress/route.ts, src/app/api/v1/user/welcome-scan/result/route.ts, src/app/functions/server/onerep.ts, src/db/tables/subscribers.js
Jira: MNTOR-2874
Refactor `getOnerepProfileId` to return a number
=> MNTOR-2874: refactor getOnerepProfileId

src/app/components/client/ExposureCard.tsx
Jira: [MNTOR-2895](https://mozilla-hub.atlassian.net/browse/MNTOR-2895)
Open breach card links in a new tab or window.
[MNTOR-2895]: https://mozilla-hub.atlassian.net/browse/MNTOR-2895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add target _blank to links in breach card (MNTOR-2895)

src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/automatic-remove/AutomaticRemove.stories.tsx, src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/automatic-remove/AutomaticRemoveView.tsx, src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/page.tsx, src/app/(proper_react)/redesign/(public)/LandingView.test.tsx, src/app/(proper_react)/redesign/(public)/PlansTable.tsx, src/app/(proper_react)/redesign/(public)/SignUpForm.tsx, src/app/components/client/PageLoadEvent.tsx, src/app/components/client/UpsellDialog.tsx, src/app/functions/universal/attributions.ts
Figma: 
Adding Subplat / Signup UTM work on top of existing release branch.. unfortunately cherry picking isn't an option.
Taken out a set of code related to pricing (billing)
=> 2024.01.17 release branch with UTM work replayed on top

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/automatic-remove/AutomaticRemoveView.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/automatic-remove/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/page.tsx, src/app/functions/server/attributions.ts, src/db/tables/attributions.ts
Jira: MNTOR-2899
Consolidate additional utm params logic into a server util function. 
Add logic to both guided experience and settings upsell
=> MNTOR-2899: rework the UTM for guided experience and settings

src/app/api/utils/auth.ts
Jira: MNTOR-2925 
Cover all branches in account creation, and log and unexpected `else` conditions.
=> MNTOR-2925 - log account creation fallthrough

src/app/api/utils/auth.ts
Jira: MNTOR-2925 
Further clarify account logging.
=> MNTOR-2925 - clarify account logging

src/app/functions/server/getSubscriberEmails.ts
Jira: MNTOR-2929
Same bug as we say on the dashboard, same temporary workaround while we work on it.
=> Fallback behavior for case continued

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/actions.ts
Jira: MNTOR-2951
This is the same underlying cause as #4205
=> MNTOR-2951 - fix another case of missing authOptions to getServerSession

src/app/api/v1/fxa-rp-events/route.ts
Jira: MNTOR-2973
guard against empty profile change obj from fxa
=> MNTOR-2973: guard against empty profile change obj from fxa

src/apiMocks/mockData.ts, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/automatic-remove/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/manual-remove/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/start-free-scan/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/view-data-brokers/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/[type]/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/[type]/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/[type]/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/page.tsx, src/app/api/v1/user/breaches/bulk-resolve/route.ts, src/app/api/v1/user/breaches/route.ts, src/app/deprecated/(authenticated)/user/breaches/breaches.d.ts, src/app/functions/server/getUserBreaches.ts, src/app/functions/universal/breach.ts, src/db/tables/subscribers.js, src/knex-tables.d.ts, src/utils/subscriberBreaches.test.ts, src/utils/subscriberBreaches.ts
Reverts mozilla/blurts-server#4212
=> Revert "Derive isResolved dynamically from subscribers resolved breach data classes (MNTOR-2871)"

.github/workflows/e2e_cron.yml
=> fix: increase the time out for cron e2e

src/apiMocks/mockData.ts, src/app/(proper_react)/(redesign)/(public)/breach-details/[breachName]/BreachDetailView.stories.tsx, src/app/(proper_react)/(redesign)/(public)/breach-details/[breachName]/BreachDetailView.tsx, src/app/(proper_react)/(redesign)/(public)/breach-details/[breachName]/BreachDetailsView.test.tsx, src/app/(proper_react)/(redesign)/(public)/breaches/BreachIndexView.stories.tsx, src/utils/recommendations.js
Jira: MNTOR-2996
Figma: N/A
BVD requested that we emphasise in English that the leak was at one of their customers.
Visit `breach-details/BVD`, or set the breach name to `BVD` in the Controls panel in Storybook.
=> Update description for the BVD breach

locales/en/data-classes.ftl
This is a new type of data leak that was recently added.
(I can't quite remember how I found out - I was working on something else I think, and then saw a message about this string missing.)
=> Add citizenship-statuses data breach label

.github/workflows/preview_deploy_gcp.yml, .github/workflows/preview_deploy_gcp_cleanup.yml
=> MNTOR-3179: cleanup script on close/merge

.github/workflows/preview_deploy_gcp_cleanup.yml
=> MNTOR-3179: 3rd attempt default answer for delete deploy

src/scripts/cronjobs/monthlyActivity.tsx
I'd forgotten to remove this in
d4b200fac07b9811947dcf243e0c90d4a3573d9f.
=> Remove dangling reference to deleted string

.github/workflows/preview_deploy_gcp.yml
Jira: MNTOR-3221
Avoid recommenting the Preview URL on the same PR
Should skip the comment step if a comment about the preview url already exists
=> MNTOR-3221: avoid recomment on the same PR

.github/workflows/release.yaml
Jira: MNTOR-3243
Tag and push an image for GH release
=> MNTOR-3243: release gha

src/app/api/utils/auth.ts, src/db/migrations/20240606111238_add_subscriber_sign_in_count.js, src/db/tables/subscribers.js, src/knex-tables.d.ts
Jira: MNTOR-3273
Backend function to keep track of # of sign-ins
=> MNTOR-3273: increment sign in counter for subscriber

src/scripts/cronjobs/firstDataBrokerRemovalFixed.tsx
Jira: [MNTOR-2700](https://mozilla-hub.atlassian.net/browse/MNTOR-2700)
Fix the condition for selecting the first removed data broker.
[MNTOR-2700]: https://mozilla-hub.atlassian.net/browse/MNTOR-2700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix first data broker email condition

locales-pending/how-it-works.ftl, src/app/(proper_react)/(redesign)/(public)/how-it-works/HowItWorksView.module.scss, src/app/(proper_react)/(redesign)/(public)/how-it-works/components/FooterSection.tsx
Jira: MNTOR-3306
Reduced padding to match landing page.  Per PM request, removed "Breach data provided by Have I Been Pwned" message
- [X - removed] Localization strings (if needed) have been added.
=> updated padding in footer to align more with landing page footer

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/Dashboard.stories.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/DashboardTopBanner/DashboardTopBannerContent.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/DashboardTopBanner/index.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/View.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/automatic-remove/AutomaticRemove.stories.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/manual-remove/ManualRemove.stories.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/start-free-scan/StartFreeScan.stories.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/view-data-brokers/ViewDataBrokers.stories.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/WelcomeToPlus.stories.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/WelcomeToPlusView.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/[type]/HighRiskDataBreach.stories.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/[type]/LeakedPasswords.stories.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/[type]/SecurityRecommendations.stories.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/layout.tsx, src/app/(proper_react)/(redesign)/(public)/PublicShell.tsx, src/app/(proper_react)/(redesign)/(public)/how-it-works/HowItWorksView.module.scss, src/app/(proper_react)/(redesign)/(public)/how-it-works/page.tsx, src/app/(proper_react)/(redesign)/Footer.tsx, src/app/(proper_react)/(redesign)/MobileShell.tsx, src/app/(proper_react)/(redesign)/Shell.tsx, src/db/tables/featureFlags.ts
Feature flag for How it works page added.  When disabled, user is sent to landing page.
This is an update to mntor-2317, which has already been approved but reverted pending this flag
https://github.com/mozilla/blurts-server/pull/4632
=> feature flag added

src/app/components/client/ExposuresFilter.tsx, src/app/components/client/ExposuresFilterExplainer.tsx, src/app/components/server/StatusPill.tsx
Reverts mozilla/blurts-server#4694 for release
=> Revert "Show fixed status for Plus users (MNTOR-3201)"

src/app/components/client/ExposuresFilterExplainer.tsx
Reverts mozilla/blurts-server#4688 for release
=> Revert "Fixed status label info string (MNTOR-3322)"

src/app/functions/server/applyCoupon.ts
=> MNTOR-3272: return actual check

src/app/components/client/ExposuresFilterExplainer.tsx
Reverts mozilla/blurts-server#4703
=> Revert "Revert "Fixed status label info string (MNTOR-3322)""

src/app/components/client/ExposuresFilter.tsx, src/app/components/client/ExposuresFilterExplainer.tsx, src/app/components/server/StatusPill.tsx
Reverts mozilla/blurts-server#4702
=> Revert "Revert "Show fixed status for Plus users (MNTOR-3201)""

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/CancelFlow.tsx
…n iOS
Jira: MNTOR-3318
Figma:
=> mntor-3318 (wanting to test on stage)

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/[type]/page.tsx
Jira: MNTOR-3030
Added logging for `No subscriber found for the given user data.` error
=> mntor-3030: added logging

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/SettingsPage.test.tsx, src/db/migrations/20240702102931_add_fxa_expiry_to_subscribers.js, src/knex-tables.d.ts, src/utils/subscriberBreaches.test.ts
Jira: MNTOR-3353
Part 1: Add fxa session expiry column to subscribers table
=> MNTOR-3353: add expiry to subscribers table

src/app/(proper_react)/(redesign)/(public)/breaches/page.tsx
Jira: MNTOR-3240
Figma:
Sometimes breaches get added in a different order than when they happened, so we want to make it easy for users to know which breaches are new to Monitor.
First called out [here](https://github.com/mozilla/blurts-server/pull/4757#discussion_r1667778081), then verified [here](https://mozilla-hub.atlassian.net/browse/MNTOR-3240?focusedCommentId=906910).
Visit `/breaches`, note that e.g. ClickASnap and Flipkart's breaches are listed first.
=> Sort breaches by added date

config/nimbus.yaml
Fix invalid FML which is causing https://github.com/mozilla/experimenter/pull/11014.
=> Fix invalid FML in nimbus.yaml

src/app/functions/server/onerep.ts
Jira: MNTOR-
Figma:
One rep call that's taking down our server atm
=> Temp fix for one rep

locales-pending/dashboard-premium.ftl, locales-pending/fix-premium.ftl, locales-pending/landing-premium.ftl, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/Dashboard.stories.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/DashboardTopBanner/DashboardTopBannerContent.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/DashboardTopBanner/index.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/View.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/ResolutionContainer.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/WelcomeToPlus.stories.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/WelcomeToPlusView.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/HighRiskBreachLayout.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/[type]/HighRiskDataBreach.stories.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/[type]/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/LeakedPasswordsLayout.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/[type]/LeakedPasswords.stories.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/[type]/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/SecurityRecommendationsLayout.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/[type]/SecurityRecommendations.stories.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/[type]/page.tsx, src/app/(proper_react)/(redesign)/(public)/Faq.tsx, src/app/(proper_react)/(redesign)/(public)/LandingView.stories.tsx, src/app/(proper_react)/(redesign)/(public)/LandingView.tsx, src/app/components/client/ExposuresFilter.tsx, src/app/components/client/ExposuresFilterExplainer.tsx, src/app/components/client/PercentageChart.tsx, src/app/components/client/ProgressCard.tsx, src/app/components/client/stories/ProgressCard.stories.ts, src/db/tables/featureFlags.ts
Jira: MNTOR-3200
Figma: https://www.figma.com/design/DTbmXzCQCw2PxXpHQW8yfW/Monitor-MVP-Enhancements?node-id=1926-1291&t=yj8SkckZSeRi6GFg-4
We've had a number of people reach out, surprised that some data removals took more than 14 days. Thus, this removes mention of that time period.
Basically, there should be no more mentions of removals typically taking 7-14 days, but for the exact strings, see Figma. The changes are in these places:
- [Welcome to Monitor Plus](https://fx-monitor-storybook.netlify.app/?path=/story/pages-logged-in-guided-resolution-1e-welcome-to-plus--welcome-to-plus-view-in-progress-story), with scan results.
- [About exposure types dialog](https://fx-monitor-storybook.netlify.app/?path=/story/pages-logged-in-dashboard--dashboard-us-no-premium-unresolved-scan-unresolved …
=> Avoid people thinking 14 days fixes *all* scan results

src/db/tables/subscribers.js
=> MNTOR-null: fix 1 month sql

src/app/(proper_react)/(redesign)/(authenticated)/admin/qa-customs/page.tsx, src/app/api/v1/admin/qa-customs/hibp/route.ts, src/app/api/v1/admin/qa-customs/onerep/route.ts, src/app/api/v1/admin/qa-customs/route.ts, src/db/tables/onerep_scans.ts, src/db/tables/qa_customs.ts, src/utils/hibp.ts
Jira: 
Figma:
Made the QA tool unavailable in prod, and changed some defaults to trigger less db queries
=> QA-tool: made unavailable in prod

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/EmailAddressAdder.tsx
Reverts mozilla/blurts-server#4964
=> Revert "Align disabled state with email validation"

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/EmailAddressAdder.tsx
Reverts mozilla/blurts-server#4969
=> Revert "Revert "Align disabled state with email validation""

locales/en/app.ftl
=> Add new string for menu entry in the footer

src/app/api/v1/fxa-rp-events/route.ts
Jira: MNTOR-3584
Figma:
set monthly report to true when user subs to plus
=> MNTOR-3584: set monthly report to true when user subs to plus

src/e2e/pages/dashBoardPage.ts
Update the E2E test to check for the link label that has been updated in PR #4983.
=> Update footer link label for E2E test

src/emails/components/EmailDataPointCount.tsx, src/emails/components/EmailHero.tsx, src/emails/templates/EmailFooter.tsx, src/emails/templates/breachAlert/BreachAlertEmail.test.tsx, src/emails/templates/breachAlert/BreachAlertEmail.tsx
Followup to 9f99a0bfe7bf25a61c35cf753405f034dd58d6a2, where I'd missed a few.
=> More outdated UTM parameters

src/db/tables/subscriber_email_preferences.ts
Jira: MNTOR-3672
Figma:
Change log format to debug
=> MNTOR-3672: error log format

.github/workflows/e2e_cron.yml
Remove unknown option `--fully-parallel`.
=> Remove unknown E2E option

src/app/(proper_react)/(redesign)/(public)/unsubscribe-email/monthly-report-free/UnsubscribeMonthlyReportView.tsx
Jira: [MNTOR-3694](https://mozilla-hub.atlassian.net/browse/MNTOR-3694)
Auto close toast notification after 15 seconds.
1. Visit `/unsubscribe-email/monthly-report-free`
2. Click the “Unsubscribe” button
3. Wait for the notification to disappear
[MNTOR-3694]: https://mozilla-hub.atlassian.net/browse/MNTOR-3694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Auto close toast notification

src/app/api/v1/user/breaches/route.ts
Jira: MNTOR-3633
Remove obsolete `/api/v1/user/breaches` GET endpoint.
=> MNTOR-3633 - remove unused /user/breaches API GET endpoint

.github/workflows/docker_build_deploy.yml
Jira: MNTOR-3853
Get the public Sentry DSN from `secrets`, not `env`
=> Use GitHub secrets for public sentry dsn

src/e2e/specs/dashboard/dashboard-navigation.spec.ts
Update the expected URL schema for the settings E2E tests.
=> Fix expected settings E2E test URL

src/apiMocks/mockData.ts, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/removal-under-maintenance/RemovalUnderMaintenanceView.test.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/removal-under-maintenance/RemovalUnderMaintenanceView.tsx, src/app/components/server/StatusPill.tsx, src/app/functions/server/getRelevantGuidedSteps.ts, src/utils/fetchWithDelay.test.ts, src/utils/fetchWithDelay.ts
Add additional unit test coverage for PR #5366.
=> Additional unit test coverage for “Removal under maintenance”

package.json, src/scripts/cronjobs/monthlyActivityFree.tsx
Jira: MNTOR-3857
As a part of this "fix", we will also ask SRE to decrease the batch size `MONTHLY_ACTIVITY_FREE_EMAIL_BATCH_SIZE`
=> MNTOR-3857: heap size limit reached bug

src/app/api/v1/user/welcome-scan/create/route.ts
Jira: MNTOR-3656
We just want to log the error without throwing to sentry
=> MNTOR-3656: log not throw "User is not eligible for feature"

src/db/tables/onerep_scans.ts
Jira: MNTOR-3880
add sql filtering on "link"
=> MNTOR-3880: add distinct on link

src/db/tables/onerep_scans.ts
=> MNTOR-3888: add orderby for link

src/constants.ts, src/scripts/cronjobs/monthlyActivityFree.tsx
=> MNTOR-3857: hardcode batch size

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/SettingsPage.test.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/SettingsPageRedesign.test.tsx, src/db/migrations/20250109140803_add_churn_prevention_email_sent.js, src/knex-tables.d.ts, src/utils/subscriberBreaches.test.ts
Jira: MNTOR-3919
Table column added for churn email boolean
=> MNTOR-3919: db table changes for churn email column (Part 1)

src/app/layout.tsx
=> handle nimbus user id not set

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/[[...slug]]/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/[[...slug]]/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/welcome/[[...slug]]/page.tsx, src/app/(proper_react)/(redesign)/(public)/page.tsx, src/app/api/v1/user/welcome-scan/create/route.ts, src/app/functions/server/getExperiments.ts, src/app/hooks/useGlean.ts, src/app/layout.tsx, src/contextProviders/experiments.tsx, src/middleware.ts, src/telemetry/metrics.yaml
In preparation of actual fixes, undo the reverts made yesterday.
=> Undo reverts

.github/pull_request_template.md
This updates the PR template checklist with another reminder.
(Also: use the checklist! :slightly_smiling_face: )
=> Add reminder to check both flag states

src/app/(proper_react)/(redesign)/(authenticated)/user/plus-expiration/page.tsx
Jira: MNTOR-3917
Figma:
The relevant backend code was still in development when I set this up, and I forgot to update it in https://github.com/mozilla/blurts-server/pull/5559 🤦
Create a `.csv` file with the following contents:
```csv
userid,customer,created,nickname,intervl,intervl_count,plan_id,product_id,current_period_end
18b8ea3c9b12427893ded71fda0cb8aa,cus_custom,2/6/2024 10:57:57,Yearly Production Pricing ($8.99 per month: $107.88),year,1,price_1Nv4ODJNcmPzuWtRoYpoFHXd,prod_OiV9RSaatywSRy,2/2/2025 13:37:00
```
Replace `18b8ea3c9b12427893ded71fda0cb8aa` with the `fxa_uid` of the subscriber you want to email. Then upload that file via `/admin/churn-subscribers/`. It should say that there's one customer to email in the next cron run.
Then, visit …
=> Implement forgotten isOnExpirationList check

src/app/(proper_react)/(redesign)/(authenticated)/user/plus-expiration/PlusExpiration.test.tsx
Jira: MNTOR-3915
Figma:
Some of the UI updates in response to a Server Action response's Promise resolving. Some of these tests sometimes failed, and presumably the reason was that the Promises weren't resolved yet. So now the tests explicitly await those Promises as well, to make sure they are resolved by the time it's making assertions.
Flakiness is hard to reproduce, but I did manage to get the tests to fail relatively frequently before this change, and haven't seen them fail since.
Run the tests a couple of times; they should all succeed every time.
=> Fix flaky subscription renewal tests

config/nimbus.yaml
The Nimbus team has asked us to re-introduce the "example" feature to use for testing purposes.
We do not need to use this from the code, it just needs to be present in the `nimbus.yaml` (aka feature manifest list or FML)
=> re-add example Nimbus feature for testing

src/emails/renderEmail.ts
Jira: [MNTOR-4050](https://mozilla-hub.atlassian.net/browse/MNTOR-4050)
Adds a note to the mjml’s `renderToStaticMarkup` options.
[MNTOR-4050]: https://mozilla-hub.atlassian.net/browse/MNTOR-4050?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add comment to mjml renderToStaticMarkup options

.lintstagedrc.js, eslint.config.js, jest.config.cjs, next.config.js, package.json
Follow-up for PR #5599
Run ESLint also on the files in the root directory.
=> Run ESLint on root files

src/e2e/pages/purchasePage.ts, src/e2e/specs/purchase.spec.ts, src/e2e/utils/helpers.ts
Jira: MNTOR-4062
Figma:
We should mostly be able to assume that SubPlat works (/SubPlat has their own tests), and especially on stage, where we're just using mock plans, these tests will never really be actionable.
As [discussed on Slack](https://mozilla.slack.com/archives/C06LY5A3PJ6/p1739545906460209?thread_ts=1739522296.890519&cid=C06LY5A3PJ6).
Run the E2E tests.
=> Remove E2E tests of SubPlat functionality

src/app/api/v1/hibp/notify/route.ts, src/scripts/cronjobs/emailBreachAlerts.tsx
While debugging breach sending there was a bit of info that I would've wanted to have, so I added that here. I also saw some information that I'd rather not see, so I removed that.
=> Logging refinements

src/app/(proper_react)/(redesign)/(public)/PublicShell.module.scss
Jira: MNTOR-4060
Figma:
Although the margin was a bit too much on mobile, the shrinking we did in bd13a202b7c2cf2a627f43db9b43e53e185b18e4 (https://github.com/mozilla/blurts-server/pull/5646) made it misaligned on desktop.
Before this change:
After this change, and what it used to look like:
Visit the landing page, both with the redesign flag [on](https://deploy-preview-5663--fx-monitor-storybook.netlify.app/?path=/story/pages-public-landing-page-redesign--landing-redesign-us) and [off](https://deploy-preview-5663--fx-monitor-storybook.netlify.app/?path=/story/pages-public-landing-page-default--landing-us). On smaller screens (where the hero text isn't flush with the viewport edge), the padding should still be smaller.
=> Revert margin shrinking in desktop header

.github/workflows/preview_deploy_gcp_cleanup.yml
Only formatting changes; just want to test our CI :)
=> Remove trailing whitespace from workflow

.env.local.example
@codemist You'll probably also want to make these changes to the `.env.local` I sent you recently.
=> Add missing values to .env.local.example

next.config.js, sentry.client.config.ts, src/e2e/utils/helpers.ts, src/scripts/loadtest/hibp.js
Jira: [MNTOR-4235](https://mozilla-hub.atlassian.net/jira/software/c/projects/MNTOR/boards/447?selectedIssue=MNTOR-4235)
The Monitor `stage` URL has been updated.
[MNTOR-4235]: https://mozilla-hub.atlassian.net/browse/MNTOR-4235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Monitor stage URL

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/Dashboard.test.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/[[...slug]]/page.tsx
Jira: [MNTOR-4256](https://mozilla-hub.atlassian.net/browse/MNTOR-4256)
SubPlat 2.0 links already have at least one query param `?plan` appended.
[MNTOR-4256]: https://mozilla-hub.atlassian.net/browse/MNTOR-4256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix potential UTM query params breakage for SubPlat2 links

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/automatic-remove/page.tsx, src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/[[...slug]]/page.tsx
Follow-up for https://github.com/mozilla/blurts-server/pull/5733
SubPlat 2.0 links already have at least one query param with `?` appended.
=> Fix additional SubPlat params for SP3

.dockerignore
=> MNTOR-4294: ignore generated creds

src/db/tables/subscriber_email_preferences.ts
Jira: MNTOR-4345
See incident channel
* Have a pref table record for a subscriber
* Delete the subscriber record
* See the logs catching the error and updating the pref record
This simulates a subscriber in the same situation in prod
=> MNTOR-4345: capture the edge case of orphan subscriber pref entries

src/e2e/pages/authPage.ts, src/e2e/specs/landing/landing-new-account.spec.ts
https://github.com/mozilla/fxa/commit/2bd249cd1ce948a41944a75195eb832990c933a8
=> Fix e2e tests - Remove password confirmation field in signup

src/app/api/v1/user/unsubscribe-email/route.ts, src/app/functions/cronjobs/unsubscribeLinks.ts, src/db/tables/subscriber_email_preferences.ts
=> MNTOR-4326 - revert remaining debug logs

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/panels/SettingsPanelEditInfoRedesign.tsx
Fixes the formatting of the displayed DOB.
=> Fix edit info DOB formatting

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/panels/SettingsPanelEditInfoRedesign.tsx
Enforce timezone when reading the DOB from the DB.
=> Force UTC timezone for DOB

src/e2e/pages/landingPage.ts
=> fix(e2e) Update goToSignIn url to **/oauth**

config/nimbus.yaml, src/app/(proper_react)/(redesign)/(public)/LandingViewRedesign/components/PricingPlanListWithBundle.module.scss, src/app/(proper_react)/(redesign)/(public)/LandingViewRedesign/components/PricingPlanListWithBundle.tsx, src/app/(proper_react)/(redesign)/(public)/LandingViewRedesign/components/PricingPlansWithBundle.module.scss, src/app/(proper_react)/(redesign)/(public)/LandingViewRedesign/components/PrivacyProductBundleBanner.module.scss, src/app/components/client/BillingPeriod.module.scss
**Jira**
- Bundle pricing card: https://mozilla-hub.atlassian.net/browse/MNTOR-4288?focusedCommentId=1068413
- Bundle banner: https://mozilla-hub.atlassian.net/browse/MNTOR-4287?focusedCommentId=1068412
Applies the proposed layout adjustments for the landing page bundle component.
=> Apply landing page bundle layout changes

src/app/components/client/PromptNoneAuth.tsx
Jira: [MNTOR-4519](https://mozilla-hub.atlassian.net/browse/MNTOR-4519)
Updates the silent auth callback URL.
[MNTOR-4519]: https://mozilla-hub.atlassian.net/browse/MNTOR-4519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update silent auth callback URL

src/scripts/cronjobs/emailBreachAlerts.tsx
=> fix(cronjobs): Poll for messages until maxMessages have been pulled

src/app/api/v1/admin/users/[fxaUid]/route.ts
We need the route `/api/v1/admin/users/[fxaUid]` to process customer support requests. The route access was restricted too much from the intended behavior. The changes in this PR loosen these restrictions again to grant access for admins with a Mozilla email.
Follow instructions in the BLE runbook
=> Fix route `/admin/user/[fxaUid]`

src/db/tables/featureFlags.ts
Make feature flag `DisableLandingToDashboardRedirect` admin-only.
=> Add DisableLandingToDashboardRedirect to admin only feature flags

.github/workflows/docker_build_deploy_v2.yml, .github/workflows/production_deploy.yml, .github/workflows/release_cron_daily.yml, .github/workflows/release_retag_v2.yaml
https://mozilla-hub.atlassian.net/browse/SVCSE-3234
=> fix(ci): Use repository name for container tag

.github/workflows/functional_tests_cron.yml
Include environment in functional test failure Slack notification.
=> Add environment to test failure Slack notification

src/app/functions/server/getExperiments.test.ts, src/app/functions/server/getExperiments.ts
=> chore: support pathname prefix in NIMBUS_SIDECAR_URL

.github/workflows/production_deploy.yml
Jira: MNTOR-5023
Revert this change based on Frida's request: https://github.com/mozilla/blurts-server/pull/6150#discussion_r2387209655
=> refactor: use SAFE_ENVIRONMENT variable for tagging Docker images

README.md
Fix typo in load test npm command.
Try running `npm` command exactly as stated in README.
=> doc: fix typo in load test instructions

src/db/migrations/20251002092700_drop_coupon_subcriber_churn.js, src/knex-tables.d.ts
Jira: MNTOR-5015
Figma:
Remove subscriber_churns and subscriber_coupons tables and types. Tested by running the migration locally, plus unit tests and build success. I couldn't get the functional tests to work locally but I assume they'll be run in CI.
=> chore(plus): remove churn and coupon tables and types
