app-constants.js

Fixes #58 
Attempting to overwrite an `AppConstant.*` will now fail w/ the following:
```sh
$ npm start
> blurts-server@0.0.1 start /Users/pdehaan/dev/github/mozilla/blurts-server
> node server.js
/Users/pdehaan/dev/github/mozilla/blurts-server/server.js:13
AppConstants.PORT = 9096;
^
TypeError: Cannot assign to read only property 'PORT' of object '#<Object>'
at Object.<anonymous> (/Users/pdehaan/dev/github/mozilla/blurts-server/server.js:13:19)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
...
```

Freeze exported AppConstants

---

public/js/test.js
routes/user.js
views/add.hbs
views/layouts/default.hbs

This actually enables the "Subscribe with Email Account" button, and puts the user onto a verification page when they click it.
Note: you need to unset `DEBUG_DUMMY_SMTP` and working `SMTP_*` environment variables for the email verification to actually send. https://fx-breach-alerts.herokuapp.com/ is set up with a demo account of Mailgun that is only authorized to send emails to lcrouch at mozilla dot com and nhnt11 at gmail dot com.

fix #77: enable subscribe-email-input and button

---

hibp.js

Troy has moved the `range` query endpoint under `breachedaccount/` in his API.

update hibp api url path

---

.env-dist
app-constants.js
server.js

This should get us up to an A+ on https://observatory.mozilla.org/analyze/fx-breach-alerts.herokuapp.com

for #55: redirect non-dev environments to https

---

views/partials/scan_form.hbs

This is an indication to ZAP (and potentially other security tools) that an anti CSRF token has deliberately not been added to this form.
An attacker will be able to submit an email address on behalf of the user but it wont cause any problems for anyone.
The data-no-csrf attribute doesnt make this any more secure, but it does allow us to ignore it and therefore not report this as a potential problem.
This should help the server pass the baseline scan as referenced in #55

Add data-no-csrf attribute

---

public/css/app.css
public/js/monitor.js
views/partials/false_door.hbs

Fixes GA reference error that crops up when sign up button is clicked while tracking protection is enabled (in Nightly private window) and blocks the false-door from displaying. Also fixes UI issue on the What to Do list width.

GA reference error fix

---

routes/home.js
routes/scan.js
server.js
views/404.hbs

Redirect all unhandled GET paths to index; also do so for POSTs to /scan that don't supply an emailHash or supply the empty string's sha1.
Fixes #183.

Routing changes

---

hibp.js

- Fixes #204 
adds .toUpperCase() to sha1Prefix to correct mismatched hashes and breached emails returning as safe.

#204 - Wrongly Marked Emails Fix

---

server.js

Addresses CSP errors noted in safari and potentially the CSP violations previously noted by BobM in the logs (obviously can't test). 
- Adds 'self' to font-src directive since default-src is set to 'none'.
- Adds connect-src directive.

updates csp

---

.env-dist
README.md
package.json

and drop other things we don't need like AWS creds

fix #249: update README to match smaller DB

---

.env-dist
app-constants.js
server.js

Can now set `DISABLE_DOCKERFLOW` to disable the route that tries to access the git repository. This prevents an error log message in environments (like heroku) where the git repo is not available.

disable dockerflow routes on heroku

---

views/partials/featured_breach.hbs

Now, the only place `{{ Name }}` is used is in `<img src="">` attributes and an `<input type="hidden">` and nothing user facing.
```sh
$ git grep "Name }}"
views/partials/breach_listing.hbs:        <img alt="{{ Title }}" src="img/logos/{{ Name }}.{{ LogoType }}" />
views/partials/featured_breach.hbs:        <img alt="{{ featuredBreach.Title }}" src="img/logos/{{ featuredBreach.Name }}.{{ featuredBreach.LogoType }}">
views/partials/scan_form.hbs:      <input id="featured" type="hidden" name="featuredBreach" value="{{ featuredBreach.Name }}"/>
```
```sh
$ git grep "Title }}"
views/email/breach_notification.hbs:  Uh-oh, {{ email }} was involved in {{ breach.Title }} data breach.
views/monitor.hbs:          <p class="demi">See if your account was exposed in the <span class="bold">{{ …
```

Use Title instead of Name for breach

---

.env-dist
app-constants.js
controllers/hibp.js
hibp.js
routes/hibp.js

Client may send a GET request to `/hibp/breaches` with `If-Modified-Since` header value of its most recent breach DateTime.
If the server has a breach that is newer than the client's `If-Modified-Since` value, it will respond with the full breach JSON data and a new `Last-Modified` value for the client to store. Otherwise, it will respond with an empty `304` response.
After sending the response to the client, the server checks to see if it has loaded upstream breach data from HIBP within the last `HIBP_RELOAD_BREACHES_TIMER` milliseconds (Default 60000 or 10 min.). If not, it reloads upstream breach data and sets the appropriate state for `If-Modified-Since` checks and `Last-Modified` values.

fix #270 fix #245: serve breach data to clients

---

.circleci/config.yml
.travis.yml
package-lock.json
package.json

Ironically, the only vulnerability `npm audit` saw was in `lodash`, which was required by `nsp`. So when I removed `nsp` `npm audit` passed with 0 vulnerabilities.

fix #305: replace nsp with npm audit

---

controllers/hibp.js

Real email subject and template will come later. This is just to make sure the functionality works.

fix #103: send real email in hibp/notify

---

controllers/user.js
hbs-helpers.js
server.js
views/partials/breach_listing.hbs
views/partials/featured_breach.hbs

The refactor moves the handlebars helpers "up" into named functions in `HBSHelpers` so they can be re-used in controller code or in templates.

fix #329: check dataClasses before joining

---

controllers/user.js
email-utils.js
hbs-helpers.js
package-lock.json
package.json
server.js
views/email/email_partials/email_single_breach.hbs
views/partials/compromised_accounts.hbs
views/scan.hbs

Web templates were using express-hbs while email templates used
express-handlebars. Change both to use express-handlebars, which also
lets us share helpers between email + web templates.

consolidate on express-handlebars for web + email

---

controllers/home.js
public/css/app.css
tests/hibp.test.js
tests/home.test.js
views/404.hbs
views/error.hbs

Makes footer more visible on page load for error, 404, confirmation, and unsubscribe pages until we have other content for a less dead-endy error and/or 404.

Show more of footer on error and subs.

---

controllers/user.js
public/js/monitor.js
routes/user.js
tests/controllers/user.test.js
tests/hibp.test.js
views/unsubscribe.hbs
views/unsubscribe_survey.hbs

- Moves unsubscribe survey into separate template
- Allows user to refresh unanswered survey form without being redirected to ("/");
- Prevents multiple survey form submissions
- Throws "this email is not subscribed to Firefox Monitor" error when answered unsubscribe survey form page is refreshed (maybe it makes more sense to redirect to landing page?)

DNM yet: Handle unsubscribe flow refreshes/unsub form resubmits

---

public/js/monitor.js

Use custom dimension -  'dimension1' - for storing event location information on all event categories (except Errors) where event label is already in use and location information is necessary.

Use dimension1 any time we are logging event location.

---

public/js/monitor.js

GA events are firing correctly, but not arriving correctly in the google analytics dashboard. We think the custom dimensions and custom metric might be an aggravating issue. This removes the values currently being sent in custom dimensions and metrics and appends them to the event label where necessary.

Analytics bandaid

---

server.js

This should let nginx start serving `304` responses for static assets on stage & prod.

for #264: set Cache-Control on statics

---

package-lock.json
package.json

Don't need 'em! Transforming the css variables into static values was causing layout issues (particularly on mobile) and not delivering any performance gain.

Drop postcss-css-variables

---

controllers/user.js
db/DB.js
db/migrations/20180930071926_add_signup_language.js
package.json
tests/controllers/user.test.js

So we can send the right translated emails to subscribers, we need to start saving their `Accept-Language` value when they sign up.
We should merge and deploy this ASAP - the longer we run without this, the more users are going to have to set their language later. 😢

start saving signup language for future emails

---

public/css/app.css

Prevents input backgrounds from turning yellow after auto-filling in mobile safari.

Remove yellow background / white text on mobile autofill

---

public/css/app.css

Prevents Firefox logomark in the download banner from getting clipped on small Safari and Chrome screens.
fixes #514

Fixes #514  - clipped Firefox mark in download banner

---

public/css/app.css
views/partials/subscribe_modal/confirm_your_account.hbs

Use localized "Sent!" string in templates instead of generating en-us-only "Sent!" with CSS.

Add "Sent!" string in signup modal.

---

locale-utils.js
public/css/app.css

This disables Unicode isolation and gets rid of "PDI" and "FSI" boxes all over the place in Edge. What are the potential negative ramifications of setting { useIsolating: false } for all browsers?
Our current situation in Edge:

Disable Unicode isolation

---

controllers/email-l10n.js
public/css/email_l10n_testing.css
views/layouts/email_l10n_mockups.hbs

Adds the subject of emails to /email-l10n views and fixes #580

Add email subject to /email-l10n

---

locales/es-AR/app.ftl

Adds { $featuredBreach } back in and closes `<span>` tag.

Fixes "featured-breach-results" in es-AR

---

public/css/app.css

Fix paragraph width / wrapping issue in Download Firefox top bar.

---

hibp.js
views/partials/breach_listing.hbs
views/partials/featured_breach.hbs

Clips down breach.LogoPath when we load in breaches and uses new LogoPath in templates.

Use LogoPath instead of LogoType.

---

controllers/hibp.js
controllers/user.js
hibp.js
tests/controllers/hibp.test.js
tests/hibp.test.js
tests/test-breaches.js

There was a lot of confusion about the "You've Been Scraped" breach alert we sent out on 12/6. Earlier today a decision was made to hide non-website breaches until new content has been created to explain them.
This hides breaches in website scan results, email reports, and prevents the sending of new breach alerts when  `breach.IsFabricated`, `breach.IsSpamList`, and when `breach.Domain === ""`.

Additional breach filtering / Hide non-website breaches everywhere. 

---

.travis.yml
basket.js
controllers/oauth.js
controllers/user.js
db/DB.js
db/migrations/20181227100332_add_fxa_columns.js
email-utils.js
locales/en/app.ftl
public/css/app.css
public/js/monitor.js
tests/controllers/oauth.test.js
tests/db.test.js
views/partials/subscribe_modal/subscribe_modal_wrapper.hbs
views/partials/subscribe_modal/subscribe_to_ffxm.hbs

start FxA fixes for new templates

---

views/partials/hibp_attribution.hbs

Sends a ping anytime a user clicks on the HIBP attribution link. I'm sure we were collecting these clicks at one point but I think the analytics attributes were mistakenly left out during localization.

Send analytics ping on HIBP clicks.

---

locales/ru/app.ftl
package-lock.json
package.json

Please update to the newest version of `fluent`. It supports the new features of the Fluent Syntax, introduced in [versions 0.7 and 0.8](https://github.com/projectfluent/fluent/releases) of the spec. The `fluent` package on npm is [versioned independently](https://github.com/projectfluent/fluent.js/blob/master/fluent/CHANGELOG.md) of the spec versions, but the gist is that `fluent` 0.10 supports the most recent syntax spec.
This is important to us because we'd like to roll out the support for these new features in Pontoon soon. Once available, localizers will be free to use them in their translations. I'd like to make sure `blurts-server` is ready for any such updated translations.
I tested this locally briefly, i.e. without creating a DB nor connecting to HIBP. The landing page and some …

Update to fluent 0.10

---

controllers/hibp.js
controllers/oauth.js
controllers/user.js
email-utils.js
public/js/analytics_tracking_protection.js
public/js/monitor.js
tests/controllers/hibp.test.js
tests/controllers/user.test.js
views/partials/email_partials/email_button.hbs
views/partials/email_partials/email_verify.hbs
views/partials/email_partials/report.hbs

- Adds utm parameters to the CTA buttons and unsubscribe links in emails.
- Moves and updates the function responsible for clipping out utm parameters from the url to prevent`hash=` and `token=` in unsubscribe routes from also getting clipped.
Fixes #636, fixes #650, closes #439

Add utm parameters to CTA buttons and unsubscribe links in emails.

---

server.js

Ops sets HSTS for stage & prod, so the helmet header is redundant and may cause agents to incorrectly apply the HSTS policy.

fix bug 1521724 - disable default helmet hsts

---

.env-dist
app-constants.js
controllers/home.js
controllers/scan.js
locales/en/app.ftl
package-lock.json
package.json
routes/home.js
routes/scan.js
server.js
tests/controllers/home.test.js
tests/controllers/scan.test.js
views/partials/scan_form.hbs

Note: This breaks the "Scan another email" form at the bottom of the `/scan` results. Not sure yet how to un-break it, but I need some other eyes on this ASAP.

fix #688: add csrf & encrypted page tokens for scans

---

public/css/fxa.css
public/js/monitor.js

To bring us into greater accord with the spec without imposing capitalization on other locales.

Capitalize the sign in button in en locales.

---

controllers/home.js
controllers/oauth.js
controllers/scan.js
controllers/utils.js
public/css/fxa.css
routes/scan.js
scan-results.js
sha1-utils.js
tests/controllers/home.test.js
tests/controllers/oauth.test.js
tests/controllers/scan.test.js
views/partials/fxa_enabled/fxa_new_user_bar.hbs
views/partials/fxa_enabled/fxa_scan.hbs
views/partials/fxa_enabled/scan_results/fxa_compromised_accounts.hbs
views/partials/fxa_enabled/scan_results/result_headline.hbs
views/partials/fxa_enabled/scan_results/result_page_right.hbs
views/partials/fxa_enabled/scan_results/result_subhead.hbs
views/partials/fxa_enabled/scan_results/single_breach.hbs
views/partials/fxa_enabled/see_full_report_button.hbs
views/partials/legacy/compromised_accounts.hbs
views/partials/legacy/scan.hbs

- Moves scan logic that was living in various/multiple controllers into standalone `scan-results.js` that returns one big object for sending to the templates.
- Updates templates with new/renamed vars.
- `latestBreaches` is now `userDash`
- `authenticatedUser` is now `selfScan`
- `featuredBreach` is now `specificBreach`  (in `scan-results.js` and various result partials)
- Fixes some logic in the templates unearthed while working on this. Specifically:
- Single breach results not showing up on `fullReport` and `userDash` pages.
- Some incorrect response headlines/subheads when signed in users scan emails other than their own from featured breach pages.
- Fixes rder and appearance of the sign up banner, the download banner, and the what to do tips on result pages.
- See Full Report …

Consolidate scan result logic for easier current/future templating. 

---

public/js/monitor.js

Prevents line 501 from throwing an error when a user is signed in and `#login-btn` doesn't exist.

Check if login-btn exists before adding class.

---

hbs-helpers.js

This grabs the localized copy before wrapping `{$ breachCount }` in `<span class="medium"></span>`.
Fluent doesn't interpret `{ $breachCount }` when it's wrapped in markup and the default `*[other]` string is currently being returned no matter the actual `{ $breachCount }`.

fix #799: Add markup to { $breachCount } after grabbing localized strings.

---

hbs-helpers.js

-Fixes #806 
Updates the `fluentNestedBold` helper so that it doesn't incorrectly overwrite `{ $userEmail }`
and `{ $breachName }`.
Now, `fluentNestedBold`:
- Makes copy of `args.hash`
- Sets any non-`breachCount` value in args.hash equal to its key. "000webhost" would become "breachName", for instance.
- Grabs translated string with correct `breachCount` value and any other placeholder args. 
- Checks returned strings for the `breachCount` numeral (looks for digit(s) surrounded by whitespace) and adds markup.
- Replaces placeholder vars with saved values, adds markup, and sends to template.
To check this, I created a new mailinator account (123monitor_testing_number_1-@mailinator.com) and gave myself some breaches locally.

Update fluentNestedBold helper.

---

controllers/oauth.js
package-lock.json
package.json
public/js/fxa-analytics.js
public/js/monitor.js
server.js
views/partials/analytics/default_dataset.hbs
views/partials/analytics/fxa.hbs
views/partials/sign_up_button.hbs

- Sends "top of funnel" pings to FxA `/metrics-flow` on page load for each FxA entrypoint (Sign In button in header, Sign Up button, Sign in Link, etc). 
- Stores `flowId` and `flowBeginTime` for each entrypoint element in that element's dataset.
- When a user clicks on a given entrypoint, the `entrypoint`, `flowId`, and `flowBeginTime` values are picked out and bundled up with `utm_source` and `utm_campaign` before being sent off to the /oauth flow.
Fixes #711 
Fixes #819 
Fixes #807

FxA Top of Funnel pings

---

public/js/analytics_tracking_protection.js

Fixes #822
I created a test event locally and it turned up in the GA dashboard as expected. None of the other events appear to have been altered/negatively impacted.

Set GA transport mechanism to "beacon".

---

public/js/fxa-analytics.js
views/partials/analytics/default_dataset.hbs

- Moves the `let fxaUrl` assignment into the following `.forEach` loop. The current implementation repeatedly appends the `entrypoint` param and results in only the first request firing correctly.
- Also cleans out some punctation muckying up the `default_dataset` helper.
To test locally, use PORT 8000 and make sure FXA_SETTINGS_URL is set to `https://stable.dev.lcip.org`

Fix top of funnel FxA pings.

---

views/partials/breach-card.hbs

Fixes #959. Changes "latest breach" link href to `/?breach={{ Name }}` instead of `/breach-details/{{ Name }}`.

Update latest-breach link.

---

controllers/user.js
db/seeds/test_subscribers.js
tests/controllers/user.test.js

I couldn't catch this until https://github.com/mozilla/blurts-server/pull/982 landed on https://fx-breach-alerts.herokuapp.com/ where we have pre-FxA subscribers.
I dug up one of those old pre-FxA subscriber emails and clicked its "unsubscribe" link. It incorrectly tried to redirect to `/users/preferences`.
So I updated a localhost user to match that old pre-FxA record and updated the `getUnsubscribe` code to fix that.

fix pre-FxA unsubscribe links

---

public/js/monitor.js

Remove the check for `en-US` and stop adding the `"capitalize"` class to `sign-in-btn`.  We don't need to do this now that we've updated this string.

Remove check for en-us.

---

public/css/dashboard.css
public/css/forms.css
views/partials/subpages/remove_fxm.hbs
views/partials/subpages/unsubscribe.hbs

- Vertically centers unsubscribe button text
- Adds more spacing between the Add Another Email form and Remove Firefox Monitor button on the preferences dashboard.
- Related letter-spacing/font-size tweaks.
Waiting to hear from Ryan and Betsy about what should happen as far as a visual "You've been unsubscribed" cue after clicking "Remove Firefox Monitor".

Unsubscribe flow UI updates

---

controllers/user.js
public/js/dashboard.js
routes/user.js
template-helpers/dashboard.js
tests/controllers/user.test.js
views/partials/dashboards/preferences.hbs
views/partials/email-card.hbs
views/partials/forms/add-another-email-form.hbs
views/partials/forms/remove-email-form.hbs
views/partials/subpages/remove_fxm.hbs

I need some help figuring out how to render the `csrfToken` in all the right places in the various handlebars tempaltes/helpers/subpages. Making inline comments for @lesleyjanenorton to help me here.

fix #961: add csrf tokens to all preferences forms

---

controllers/oauth.js
controllers/user.js
db/DB.js
db/migrations/20190523152919_add_fxa_access_token_to_subscribers.js
db/seeds/test_subscribers.js
lib/fxa.js
tests/controllers/ses.test.js
tests/controllers/user.test.js
tests/fxa.test.js

This could be a fast-follow after release if we think it's too risky to land before. This code:
1. Adds a db column to hold the FxA access token in addition to the refresh token
2. Updates the OAuth code to store the access token it receives from FxA
3. Updates the OAuth code to update existing subscribers' FxA data every time they sign in (to get existing subscribers' access tokens, and this should help update their avatar images too.)
4. During `removeFxm` calls FxA `/destroy` endpoint for both the access token and the refresh token

fix #992: destroy access and refresh tokens on Remove

---

controllers/user.js
db/DB.js

#1044 happened because some objects assigned to `req.sesion.user =` were the return of functions that did not join the `subscribers` table with the `email_addresses` table. This code updates the `requireSessionUser` call to always join the `email_addresses` records onto the user object.

 fix #1044: ensure session user always has email_addresses 

---

public/js/monitor.js

Fix for breach cards not showing up on the user dashboard (issue is on desktop only).

Show breach cards on desktop dashboard.

---

controllers/user.js
locales/en/app.ftl
tests/controllers/user.test.js

This adds the first sentence of the error message.
@lesleyjanenorton - do you know how we can include [the second sentence of the error message](https://github.com/mozilla/blurts-server/issues/966#issuecomment-496970649) in the generic error subpage template?

fix #966: start error-must-be-signed-in message

---

controllers/email-l10n.js
controllers/hibp.js
locales/en/app.ftl
tests/controllers/hibp.test.js

This change should have been made when we updated the breach alert emails, but got lost in the shuffle.

Add and use new string for the subject of breach alert emails.

---

public/css/monitor.css

Adds more space between the `latestBreach` card and the content above it on smaller screens.

Adjust space above "latestBreach" card.

---

public/css/footer-about.css
template-helpers/footer.js
views/about.hbs

- Restyle the /about page CTAs into buttons instead of links.
- Fix strange formatting of text blocks in more verbose locales (German, specifically).
Fixes #1083
Fixes #1010

Uniform CTA formatting on /about page.

---

views/breach-detail.hbs

This information is stored in the `Event Label` for each event ping and makes it easier to identify from which page the ping originated.

Analytics Update: Add page label to breach detail pages.

---

README.md

When I tried to run the tests for the first time, I got the following error.
```
error: database "test-blurts" does not exist
```
This PR adds instructions to setup a test database.

Update README to include information on creating a test database

---

package.json

Fixes https://github.com/mozilla/blurts-server/issues/918

Replace `setupTestFrameworkScriptFile` with `setupFilesAfterEnv` in Jest config

---

controllers/user.js
lib/fxa.js

Don't merge this unless/until [the client-side code](https://phabricator.services.mozilla.com/D38228) has landed in central.

DNM: fix #1128: check fxa token for Monitor scope

---

db/DB.js
scan-results.js

When a user adds many email addresses, joining all of their full
email_addresses records data into the session user object makes the
client-sessions object larger than the cookie size limit of Firefox.
This temporary fix joins only the ids and emails of the records, because
they are the only columns we're using. This cuts the object size down by
approx. 70%.
https://github.com/mozilla/blurts-server/issues/1148 tracks moving
session data to the back-end.

fix #1084 fix #1146 - only put ids and emails into user object

---

scripts/updatebreaches.js

Now that https://github.com/mozilla-services/remote-settings-permissions/pull/62 is merged and deployed, this works on both stage & prod Remote Settings servers.

fix #1109: inlude BreachDataClasses in remote settings record

---

public/js/fxa-analytics.js
public/js/monitor.js
views/partials/analytics/default_dataset.hbs

This saves the UTM parameters of referring sites and forwards them to FxA when a user clicks one of the FxA entrypoints (sign in / log in links and buttons) from the landing page.
Closes #844

Forward utms to fxa

---

public/css/breach-cards.css
public/css/scan-results.css

Noticed this while working on #1188. If you have an email with five breaches, the fifth breach card will appear much smaller than the other four. Related: #903 (which I think is now resolved?).

Fix shrinking breach cards in dashboard.

---

public/css/breach-detail.css
views/breach-detail.hbs

I am a little bit leery of linking users to some of these websites (and I wonder if this link will be perceived somehow as an endorsement or assurance of the site's authenticity/safety) but I can't think of a way of doing this without running a considerable number of checks before deciding whether or not to surface the link.

Add website link on breach detail pages.

---

locales/en-CA/app.ftl
locales/en-GB/app.ftl
locales/en/app.ftl

- Uses "info" instead of "information" in the `known-data-breaches-exposed` string.
- Removes unused `data-breaches-exposed` string from app.ftl.
Closes #1221

Modify dashboard string

---

public/js/fxa-analytics.js
public/js/monitor.js

Store UTM values passed by referring sites in `sessionStorage` and pass these values to FxA.
Closes #844

Maintain referring site UTM values throughout Monitor.

---

views/partials/forms/add-another-email-form.hbs

Removes the `tabindex` from the submit button of the `/user/dashboard` add form so that more intuitive tabbing is possible. Fixes #1151

Remove tabindex from `#email-add-submit`

---

public/js/monitor.js

I'm afraid there's another logical bug here because the code just looks at `sessionStorage.length` to see indicate the email addresses that have been scanned.
But, now that we're putting `utm_*` params into `sessionStorage` too, we need to change the logic for detecting scanned email addresses in session storage to only look at items that start with `scanned_`

fix #1264: only send email to fxa if it exists

---

public/js/monitor.js

Since the service sends an email to verify the email address and the form already has input type `email`, using an out of date regex copy pasted from a stackoverflow answer which doesn't account for RFC822 and RFC2822 to verify email is not necessary.

Accepts emails on internationalized domain names

---

locales/en/email-strings.ftl

Searched code base for any references to the removed lines. Only removed items that had no results. 
- Check each email listed in [/email-l10n](http://localhost:6060/email-l10n)
- share-by-email-message
- share-by-email-subject
- report-pwt-headline-4
- report-pwt-summary-4
- report-pwt-headline-3
- report-pwt-summary-3
- report-pwt-summary-2
- report-pwt-headline-2
- report-pwt-summary-1
- report-pwt-headline-1
- report-pwt-blurb
- report-subhead-found-breaches
- report-subhead-no-breaches
- report-headline
- what-to-do-next
- unsubscribe-email-link
- automated-message
- click-to-verify

Fixed #1165 - Removed unused strings from email

---

public/js/fx-bento.js

This link should take users to the Mozilla homepage, instead of redirecting to the Firefox landing page on Mozilla.org.

Update Mozilla link

---

public/css/all-breaches.css

Fix strange alignment of breach cards on /breaches

---

public/js/analytics_tracking_protection.js

https://github.com/mozilla/blurts-server/pull/1275/files was an over-fix. Didn't need to use `document.location.href` for the GA `location` and `page` values. Only needed to move the `ga("set" ...)` calls out of the `loc.search` check.

revert to doc.pathname and doc.search for GA

---

locales/en/app.ftl

Adds `breach-overview-title` to the FTL file and, once localized, will be added to breach detail pages above the paragraph that summarizes breach information.

Add `breach-overview-title` to app.ftl.

---

controllers/hibp.js
controllers/oauth.js
controllers/user.js
email-utils.js

- Changes the href of the call to the action link from the user dashboard to SERVER_URL
- Changes the UTM values attached to the call to action link so that these clicks can be categorized separately.
Should fix #1278. I wasn't able to recreate the redirect to /breaches, but it does look like we were attempting to send pre-fxa subscribers to a signed in user dashboard. @groovecoder any thoughts on what could cause a redirect from the user dashboard to /breaches?

Updates the call to action link in breach alerts sent to Pre-FxA subscribers. 

---

public/css/fx-bento.css
public/js/fx-bento.js

Fixes #1214
Small refactors to `fx-bento.js` and updates to visual indicators for bento:hover, :focus, :active, and :focus-within states.

Update Bento :hover, :active, and :focus/-within states.

---

public/js/analytics_tracking_protection.js

- Send `document.location.href` (minus hash/token values) to GA instead of `document.location.pathname + document.location.search` (which sometimes evaluates to "undefined").
- Update regex to also capture "-" + any additional numerals or letters that follow. This will fix the strange "verify?-039802" URLs we are seeing in the GA dash.

Analytics Fix

---

public/css/all-breaches.css
views/partials/fuzzy-find.hbs
views/partials/top-level/all-breaches.hbs

Restyles and moves the "Sorry, that breach is not in our database" message into the central part of the page.
Fixes part of #1167

Update /breaches page.

---

public/js/fxa-analytics.js
views/breach-detail.hbs
views/partials/feature-tip-group.hbs

Fixes #1301
This PR added a function that can add dynamic GA events on elements that have a class of `send-ga-ping`. Once clicked, it looks for three specific data-attributes on that element to fire a GA event.

Add GA event to "Change your password" pathways on Breach Details page

---

template-helpers/breach-detail.js

Fixes #1408 
And here's a list of all the current breaches w/ physical-addresses:
```js
{
'physical-addresses': [
'VerificationsIO',
'RiverCityMedia',
'Exactis',
'B2BUSABusinesses',
'Evite',
'ModernBusinessSolutions',
'DataAndLeads',
'NetProspex',
'SCDailyPhoneSpamList',
'AshleyMadison',
'SpecialKSpamList',
'Ticketfly',
'VNG',
'CafePress',
'Wanelo',
'Adapt',
'DataEnrichment',
'Experian',
'CashCrate',
'StockX',
'EatStreet',
'ElasticsearchSalesLeads',
'Yatra',
'VTech',
'MoneyBookers',
'JobStreet',
'Neteller',
'SaverSpy',
'ClixSense',
'Patreon',
'MasterDeeds',
'gPotato',
'VTightGel',
'KnownCircle',
'SterKinekor',
'Eroticy',
'WhiteRoom',
'MyFHA',
'Stratfor',
'Dominos',
'Comcast',
'MortalOnline',
'PaddyPower',
'OpenCSGO',
'BulgarianNationalRevenueAgency',
'HTHStudios',
'VINs', …
```

Fix phsyical typo in priority breaches

---

public/css/app.css
public/css/breach-cards.css

Use `box-shadow` to simulate a slight scaling effect instead of `transform: scale()`, which was causing a noticeable wiggle in some browsers.
Fixes #1419 , #1287

Fix breach card wiggling on hover.

---

controllers/hibp.js

This restores the filtering out of breaches with no domain.

Filter out breaches where breach.Domain === ""

---

public/css/header.css
public/js/monitor.js
template-helpers/header.js
views/partials/header/nav-links.hbs

Fixes #1415
- Sets the `.active-link` class from the template instead of `monitor.js`.
- Adds mouseenter/mouseleave event listeners to the other header links to handle showing and hiding the gradient underline.

Fix the flickering active-link underline

---

lib/fxa.js
middleware.js
tests/middleware.test.js

Steps to Test:
1. Sign in http://localhost:6060/ and go to http://localhost:6060/user/dashboard
2. In another tab, go to https://stable.dev.lcip.org/settings/clients
3. Click "Revoke" next to the most recent "blurts-server (local)"
4. On the first tab, refresh http://localhost:6060/user/dashboard
Expected results:
Should be signed out and redirected to home page
(Old result: the page would hang.)

fix #1426: handle HTTPError during getProfileData

---

locales/en/data-classes.ftl

Per https://github.com/mozilla/blurts-server/issues/1465#issue-545915107, specifically the last bit:
```sh
npx pdehaan/blurts-server-data-classes
Missing "encrypted-keys" data class from GateHub breach
```
&mdash; via https://monitor.firefox.com/breach-details/GateHub

Add English encrypted-keys data class string

---

views/partials/subpages/confirm.hbs

This hides the `To see and manage all emails... sign in` line when the user is already signed in.

Hide `sign in` message if the user is already signed in.

---

public/js/fxa-analytics.js

I'm not sure which scope level these should be? I set them to `hit` level in GA, but if we think they should be session, user, or period we can change it.

set custom dimension for signed-in user state

---

controllers/user.js

Fixes the bug that allows the same email to be added to the same account many times as long as the letter casing is different.

Fix #1540 - The same email can be added multiple times

---

locales/en/app.ftl

Adds strings for a Firefox Mobile promo that will appear on `/breach-details` pages.

Add strings for Firefox Mobile promo

---

template-helpers/dashboard.js
views/partials/dashboards/breaches-dash.hbs
views/private-relay.hbs

Fixes last little bug in relay test logic ...
1. Change your Firefox to only accept `de` - no `en`
2. Go straight to http://localhost:6060/protect-my-email
Expected results:
Should show “Join the waitlist for updates”
Actual results:
It says “You’re on the list!” even though the user hasn’t signed up for the list.
This happens because the logic for `enLocalesIsSupported` and `hasUserSignedUpForRelay` where combined into the single `showRelayCallout` function, but the logic to display the blocks needed to be a little bit different on each page where it was used.
This PR to split those back out and use them separately on each page.

split relay test helpers and display logic

---

public/js/fxa-analytics.js
views/partials/analytics/default_dataset.hbs

Start the OAUth process and examine the URL. Check the `utm_source` param. It should be the `.hostname` of whatever dev site URL you're testing on. 
Example: On dev master: `utm_source=fx-breach-alerts.herokuapp.com`

Fixed #1669 - Set default dataset to use SERVER_URL.hostname

---

locales/en/app.ftl

- This PR is going in before the rest of the dev work for #1665 to give the l10n team time to get the string localized. 
This feature is a graduation from the first growth team experiment. (#1587)

Add new text string for homepage checkbox

---

controllers/home.js
controllers/oauth.js
controllers/user.js
controllers/utils.js
public/css/forms.css
public/css/monitor.css
public/css/scan-results.css
public/js/fxa-analytics.js
public/js/monitor.js
public/js/resolve-breaches.js
public/js/scan-email.js
scan-results.js
template-helpers/homepage.js
tests/controllers/home.test.js
tests/controllers/scan.test.js
tests/controllers/user.test.js
views/monitor.hbs
views/partials/analytics/experiment.hbs
views/partials/forms/scan-email-form.hbs
views/scan.hbs

Meta Issue: #1652
1. Set treatment/control branch via URL param: https://monitor-v2.herokuapp.com/?experimentBranch=va
1. Enter email address to be scanned: `name@example.com`
1. On scan results page, the link directly below the headline should look like the following:
---
1. Set treatment/control branch via URL param: https://monitor-v2.herokuapp.com/?experimentBranch=vb
1. Enter email address to be scanned: `name@example.com`
1. On scan results page, the link directly below the headline should look like the following:

Breach Results FxA Experiment (Growth Exp 3)

---

controllers/user.js
tests/controllers/user.test.js

Still need to figure out spot-checking instructions. It needs a Firefox configured to use stable FXA env in order to get a token that works on http://localhost:6060/user/breach-stats.
curl command would be:
```
curl 'http://localhost:6060/user/breach-stats' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:78.0) Gecko/20100101 Firefox/78.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.7,de;q=0.3' --compressed -H 'authorization: Bearer <stable auth token for the FXA user goes here!>' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: cross-site' -H 'TE: Trailers'
```

fix #1685: add resolved stats to breach-stats

---

views/partials/forms/scan-email-form.hbs
views/scan.hbs

Fixes #1764 
This PR removes experiment-specific IDs and places the same ID on entrypoint elements, regardless of experiment branch (or exclusion).
To test, click on one of the following entry points. Check the URL that is sent to FxA to validate the entry point: 
Homepage: `fx-monitor-check-for-breaches-blue-btn`
Homepage (featured): `fx-monitor-find-out-blue-btn`
Breach Scan Results (Top): `fx-monitor-alert-me-blue-btn-top`
Breach Scan Results (Bottom): `fx-monitor-alert-me-blue-btn-bottom`

Fixed #1764 - Revised entry-point IDs to be consistent

---

email-utils.js

Reordered token param to be at the **end** of the verification URL.

Fixed #1552 - Verify Email Link UTM Params

---

.circleci/config.yml

This should help troubleshoot these weird failures we are getting. Hopefully.

Add log storing to circleci integration tests builds.

---

public/css/feature-tip-group.css
template-helpers/recommendations.js
views/partials/recommendation.hbs

This updates the recommendation templates to use the strings added in #1771 and should not deployed until on or after January 15th.
Fixes #1771

Update recommendation for exposed IP addresses - DRAFT

---

public/css/feature-tip-group.css
template-helpers/breach-detail.js
template-helpers/recommendations.js

This change shows the VPN link to *ALL* locales that start with `en`, and shows the FPN link *ONLY* to locales that are exactly `en-us`.

show vpn & fpn links for all "en-*" locales

---

template-helpers/breaches.js

Sort breaches on `/breaches` by `breach.AddedDate` instead of `breach.BreachDate`.
Fixes part of #1935

Filter breaches on /breaches by "AddedDate" instead of "BreachDate"

---

public/css/fx-bento.css
public/js/fx-bento.js

This removes Lockwise from the Bento. We need to continue sending the string until Better Web has a chance to deploy these changes.

Remove Lockwise from Bento

---

controllers/home.js
package-lock.json
public/js/fx-bento.js
template-helpers/product-promos.js
template-helpers/recommendations.js

Removed Firefox Lockwise from the recommendations.js file. Was being returned in the getAllPriorityDataClasses function.
fix bug #1954

Removed reference to Lockwise in "what to do after this breach"

---

public/js/fxa-analytics.js

- Start the URL with an entry point and utm_source alreay set: 
- Go to `localhost:6060/?entrypoint=protection_report_monitor&utm_source=about-protections`
- Complete the form on the homepage with the checkbox checked (to login/create a new FxA account) 
- On the Accounts page, check the URL. It should have only one `utm_source` entry. (From this example, it should be set to `about-protections`)

Fix #2011 - Add logic to not overwrite already set URL params

---

.env-dist
README.md

To develop and test Monitor integration with SubPlat, it needs to use the FXA stage environment.

update .env-dist and README to use FXA stage

---

locales/en/data-classes.ftl

Ref: https://monitor.firefox.com/breach-details/SuperVPNGeckoVPN
Via:
```sh
npx pdehaan/blurts-server-data-classes
Missing "device-serial-numbers" data class from SuperVPNGeckoVPN breach
Missing "login-histories" data class from SuperVPNGeckoVPN breach
```

Add missing data-classes strings from recent SuperVPNGeckoVPN breach

---

template-helpers/articles.js
template-helpers/recommendations.js

It's domain was taken over and redirects to another site.
See also:
* https://github.com/mozilla/blurts-server/issues/2104
* https://github.com/2factorauth/twofactorauth/issues/5238

Update twofactorauth.org link to 2fa.directory 

---

public/js/monitor.js

Add additional logic to re-check if GA is available before tracking click to join the waitlist
To test: 
- Set your browser mode to Strict ETP 
- Go to Monitor Dashboard (Log into FxA Stage) - https://monitor-v2.herokuapp.com 
- Click on "Join Waitlist" CTA at the bottom of the page
- **Expected:** Should navigate to `/remove-my-data` page without issue.

Fix #2207 - Strict-mode waitlist signup GA fix

---

locale-utils.js
locales/en/app.ftl
public/js/monitor.js
template-helpers/hbs-helpers.js
views/partials/vpn-promo.hbs

This PR removes the current English pricing promo from the VPN banner. Reverted back to original localized strings.
Preview: 
- Set browser language to any EN/FR/DE variant. 
- Clear any previous cookies for `localhost` (in case you dismissed the banner previously) 
- Go to homepage
- **Expected:** See VPN banner at top of the page with the following text: 
- Headline: _Now’s the time to boost your safety online._
- Body copy: _Mozilla’s Virtual Private Network helps shield your internet connection from hackers and spies._ 
- Set browser language to any other language that is **NOT** an EN/FR/DE variant. 
- Clear any previous cookies for `localhost` (in case you dismissed the banner previously) 
- Go to homepage
- **Expected:** No VPN banner is visible.

Fix #2194 - Remove VPN Pricing Update Copy (EN-only) 

---

public/scss/app.scss
public/scss/partials/email-card.scss
public/scss/partials/latest-breach.scss

I ran an audit from the compiled CSS from [v13.4.8](https://github.com/mozilla/blurts-server/releases/tag/v13.4.8) against the compiled CSS. I made a few adjustments and now when comparing the dev site version prod, it's much much closer. 
- Reordered when the main SCSS file (previously app.css) gets compiled. (Previously, it was the second file to be concat'd, so I moved it back to that position) 
Notes:
- The new CSS includes additional font weights. (Ex: The main navigation had a font-weight of `600`. Previously, bc of which font weights were available, it defaulted to `700`. Now that `600` is present, the weight changed. 
STR: 
- Open both https://monitor.firefox.com/ and https://monitor-v2.herokuapp.com/
- **Expected:** Both sites should look visually the same

CSS visual fixes

---

package.json

Nodemon should not care about files in `public/`.  By ignoring all the files built in that folder, we avoid the many server restarts triggered by Nodemon's watch.

fix #2228 - dev server restart loop during build

---

.circleci/config.yml
.travis.yml
Dockerfile
package-lock.json
package.json
tests/integration/Dockerfile.integration-test.yml
tests/integration/docker-compose.yml

This PR upgrades Node from version 10 to 14 (current LTS).  This should enable package-updates to resolve vulnerabilities, and at the same time allow the latest ES features.

upgrade to Node 14

---

public/scss/partials/main.scss
public/scss/partials/remove-data.scss

Correctly link body font family to "Inter".  
I'm not up on original designs, but reviewers should please keep an eye out for layout shifts or strange text blocks as a result of this update.

fix incorrect font reference to "Inter"

---

controllers/user.js
routes/user.js

trying to resolve heroku issues, as npm-link is used to run a local version of kanary's swaggerhub generated npm module (the npm module is unpublished). Using fetch removes this dependency.

switches from using the kanary_partner_api module to using fetch

---

controllers/user.js
locales/en/app.ftl
public/js/remove-data.js
routes/user.js
template-helpers/dashboard.js
views/partials/dashboards/breach-dash-tabs.hbs
views/partials/dashboards/remove-dashboard.hbs
views/partials/removal/removal-complete.hbs
views/partials/removal/removal-result.hbs

store kanary id in session object vs browser local storage
handle empty reports results set
route remove-form and remove-dashboard routes to a single remove-data route which conditionally renders the appropriate partial
allow ability to pass a hardcoded user ID via a url param, e.g. `/user/remove-data/?kid=2875`

handle dynamic user IDs

---

public/js/dashboard.js
template-helpers/recommendations.js

If a “trusted” FXA OAuth client knows that the browser is already signed into FXA **and** knows the signed-in email address, that trusted client can send the browser thru a "prompt-less" FXA registration & sign-up flow. It does this by sending 2 extra URL params to the FXA auth url: [`prompt=none`](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/docs/oauth/prompt-none.md) and `login_hint=<email>`.
Because of that, 1 FXA OAuth client (e.g., monitor.firefox.com) can link a signed-in user to a 2nd FXA OAuth client (e.g., relay.firefox.com) with the signed-in user's email, and the 2nd OAuth client can:
1. Start an OAuth flow session
2. Append `prompt=none&login_hint<email>` to the FXA url
* FXA will automatically register the user (if needed) AND sign them into the 2nd …

Add prompt none to relay link

---

public/js/dashboard.js

When the user is signed-out, the new code in `dashboard.js` throws this error:
```
Uncaught TypeError: can't access property "textContent", document.querySelector(...) is null
```
NBD in local & heroku, because it's the last code in `dashboard.js`, so the error doesn't cause any other effects. But in stage and prod, `dashboard.js` script is bundled into the single `app.min.js` file and the error stops all the following JS from executing - yikes! Breaks a lot of functionality, including the "Sign in" button.
This changes the code so it checks the element exists before trying to access its `textContent` property.

check .nav-user-email exists before referencing

---

views/partials/analytics/default_dataset.hbs

Currently the `data-fxa-address` attribute isn't wrapped in quotes, and it was throwing some confusing warning in a tool I was trying to build:
```diff
<body data-server-url="https://monitor.firefox.com"
data-logos-origin="https://monitor.cdn.mozilla.net"
data-fxa-enabled="fxa-enabled"
-   data-fxa-address=https://accounts.firefox.com/settings
+   data-fxa-address="https://accounts.firefox.com/settings"
data-utm_source="monitor.firefox.com"
data-signed-in-user="false"
data-bento-app-id="fx-monitor"
>
```
```sh
[error] https-monitor-firefox-com-breaches.raw.html: SyntaxError: Unexpected closing tag "body". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (76:7)
[error] …
```

Add quotes around data-fxa-address data attribute in body tag

---

.circleci/config.yml
package-lock.json
package.json

Currently, integration tests fail because they specify Node 14 and pull v14.17.16 (the latest), while package.json specifies v14.17.15.  By removing the patch version, we should be able to get latest backward-compatible bug fixes and security patches without requiring a code change in the future (for Node ^14.17).

sync NPM and CircleCI versions of Node to 14.17

---

views/partials/dashboards/remove-form.hbs

get rid of pattern requirement for middle name
regex does a few things:
^               // start of line
[a-zA-Z]{2,}    // will except a name with at least two characters
\s              // will look for white space between name and surname
[a-zA-Z]{1,}    // needs at least 1 Character
\'?-?           // possibility of **'** or **-** for double barreled and hyphenated surnames
[a-zA-Z]{2,}    // will except a name with at least two characters
\s?             // possibility of another whitespace
([a-zA-Z]{1,})? // possibility of a second surname

update name regex for first and last name

---

controllers/user.js
db/DB.js
db/migrations/20211001120114_user_enroll_and_pay_null.js
db/migrations/20211001135448_removal_pilot_table.js
form-utils.js
gulpfile.js
js-constants.js
locale-utils.js
locales/en/app.ftl
middleware.js
package-lock.json
package.json
public/js/remove-data.js
public/scss/app.scss
public/scss/includes/_mixins.scss
public/scss/partials/footer.scss
public/scss/partials/remove-enroll.scss
public/scss/partials/remove-more-time.scss
routes/user.js
views/partials/dashboards/breach-dash-welcome.hbs
views/partials/dashboards/remove-delete-confirmation.hbs
views/partials/dashboards/remove-enroll-ended.hbs
views/partials/dashboards/remove-enroll-full.hbs
views/partials/dashboards/remove-enroll.hbs
views/partials/dashboards/remove-enrolled.hbs
views/partials/dashboards/remove-more-time.hbs
views/partials/dashboards/remove-pilot-ended.hbs
views/partials/dashboards/remove-signup-confirmation.hbs
views/partials/dashboards/remove-update-confirmation.hbs

Lots of changes here: 
* a few DB migrations:
* a `removal_enrolled_time` timestamp and `removal_would_pay` boolean to the `user` table
* a `removal_pilot` table designed to house all settings for the current pilot - currently just an ID, Name, and `enrolled_users` counter which keeps track of how many people have signed up for the pilot
* a bunch of constants:
* `REMOVE_ROUTES` which are set to be searched in order to be redirectable after login
* `REMOVAL_PILOT_START_TIME` which is a timestamp of when we kick off the pilot, so that we can keep track of of how long after this time to end enrollment, display a payment decision, and end the pilot itself.
* Variables for the # of days until each of the above events
* A bunch of new routes:
* `remove-enroll` enroll page
* `remove-enrolled` …

Mh/kanary 030 pmt - Payment and Enrollment Processes

---

.stylelintrc
package-lock.json
package.json
public/scss/partials/data-removal/remove-data.scss
public/scss/partials/data-removal/remove-faq.scss

disable the `line-before` rules of stylelint due to css compilation removing those things
add the stylelint prettier package so stylelint does not collide with prettier

stylelint fixes

---

controllers/user.js
public/js/remove-data.js
remove_en/remove.ftl

`node-fetch` was providing duplicate functionality to `got`, which is already in use elsewhere in monitor
replace all usages in user controller
add a few status messages / codes on error
fixes https://mozilla-hub.atlassian.net/browse/FPRDS-5

replace node-fetch library with got

---

remove_en/remove.ftl
views/partials/dashboards/remove-form-confirm.hbs
views/partials/dashboards/remove-form.hbs

...when someone already has an account, otherwise shows the form
prepopulates the review screen with account info if available
changes the back button from cancel and moves its location
figma design for back button (out of margin, no alt text, icon, larger than other items in row), would cause some responsive issues as well as accessibility hurdles, keeping it simple for now.

adds the review screen as the default view on the removal form

---

controllers/user.js
db/DB.js
db/migrations/20220104095854_add-unenroll-col-to-subscribers.js
middleware.js
public/js/remove-data.js
public/scss/includes/_mixins.scss
public/scss/partials/data-removal/remove-data.scss
public/scss/partials/main.scss
remove_en/remove.ftl
routes/user.js
views/partials/dashboards/remove-dashboard.hbs
views/partials/dashboards/remove-enroll.hbs
views/partials/dashboards/remove-form.hbs
views/partials/data-removal/modal-birth-year.hbs
views/partials/data-removal/modal-info-needed.hbs
views/partials/data-removal/modal-leaving-monitor.hbs
views/partials/data-removal/modal-remove-info-found.hbs
views/partials/data-removal/modal-remove-link.hbs
views/partials/data-removal/modal-remove-manual.hbs
views/partials/data-removal/modal-remove-optout.hbs
views/partials/data-removal/modal-remove-risk.hbs
views/partials/removal/removal-result.hbs

*Note*: contains DB migrations which must be run in order to test, an…d upon merge / deployment to server
rename previous opt-out modal to manual modal, as it treats manual removal instructions for broker results
create new opt out modal that allows user to opt out of the removal pilot, thus hiding any part of the removal pilot experience from further view
implement this opt out modal trigger both on the enroll screen as well as in the initial data removal signup form (but only when signing up for the first time, not editing info).
handle setting the session variable which allows users to see the removal pilot navigation to false on optout
create a database migration which adds a removal_optout column to the subscribers table - this column will be checked as part of the …

Add ability to opt out of pilot

---

controllers/user.js
db/DB.js
views/partials/dashboards/remove-form-confirm.hbs

prevents a user from signing up for the pilot again by setting their optout status to true on kanary account deletion or fxm account deletion

prevents a user from signing up for the pilot again after account deletion

---

controllers/user.js
form-utils.js
views/partials/top-level/remove-faq.hbs

modify the `show=true` parameter check  so that it can only be allowed if the `NODE_EV` parameter is for `dev` or `heroku`

Disable show=true parameter ability on stage / prod

---

controllers/user.js
removal-constants.js

logic for check works and dates are what we want to launch with, but need to be able to test cancellation for now. Turning this check off.

turn of enrollment_end_date check

---

controllers/oauth.js
controllers/user.js
db/DB.js
form-utils.js

• Regardless of whether user is an existing user, if they're on the pilot list set their session.onRemovalPilotList to true.
• if a user has a kanary ID, redirect them to the dashboard instead of just throwing an error.
• allow the `show=true params` to be used on stage for better debugging.

Some attempts to better address the errors happening on stage

---

controllers/user.js
server.js
views/layouts/default.hbs

CSP does not allow inline styles.  The style nonce code was added to safely bypass this, as well resolve related client errors.  Since we are not using inline styles, and I cannot replicate errors, this PR removes the associated code.
Removing the code removes the ability to bypass CSP for inline styles, and as well allows syncing between `main` and `main-kanary` to proceed without conflict.

remove style nonce for CSP inline style rule

---

controllers/user.js

Allows users to edit their info by inclusion of an `edit=true` param. 
We are getting requests from support and research of users who input improper information - this will allow them to easily update their own info without us needing to make SRE requests or obtain personal information from our users. 
The edit info functionality itself was preserved from the foxfooding pilot, so this PR only requires that we set the feature flag by way of the param.

allow editing info via an edit=true query param

---

.env-dist
app-constants.js
middleware.js

Adds a new `REMOVAL_ADMINS` env and checks against this comma separated email list to allow access to the pilot mgmt interface in the `requireMozAdmin` middleware - replacing a previous implementation which allowed any `mozilla.com` fxa user to access.

check removal admins env for match to access pilot mgmt interface

---

controllers/user.js
template-helpers/hbs-helpers.js
views/partials/header/header.hbs

to resolve issue with adding additional emails.
Requiring the `user` controller within `hbs-helpers` was causing some sort of load order issue, in which `const EmailUtils = require("../email-utils");` within the `user` controller was resolving as `undefined`. I'm not quite sure why that was happening, but for now, this pull request removes that banner altogether, as well as the code in the helper which was requiring the user controller.
We will need to come up with a method of showing a "pilot ending" banner sometime before April, but for now, pushing this PR to prevent further user issues with adding additional emails.

remove pilot ending banner

---

.circleci/config.yml
Dockerfile
controllers/home.js
middleware.js
routes/home.js
server.js

This adds some additional features to blurts-server's Sentry configuration.
From the [Sentry Express guide](https://docs.sentry.io/platforms/node/guides/express/), this adds a `requestHandler` middleware to capture request information, and a `errorHandler` middleware to catch exceptions. This replaces the `captureException` call in the `logErrors` middleware, and should give more information in Sentry issues. I've disabled some features of the `requestHandler` which may contain PII, but further experience is needed to see if we need to include or exclude more.
I've added the `CIRCLE_TAG` to the Docker image as `SENTRY_RELEASE` (same as `version` at https://monitor.firefox.com/__version__). Sentry should use this, when defined, to populate the [`release` …

Update Sentry configuration

---

.circleci/config.yml

Allow the CircleCI deploy to fail on the `git push` step but still show the job passing. A developer will need to check the job output to see if the deploy was successful, or check Heroku.

Allow CircleCI deploy fail without failing build

---

.circleci/config.yml

Add a missing continuation slash from changing the command from a single to a multi-line command. This was broken in PR #2612.

Fix CircleCI "deploy/Build Docker Image" step

---

package-lock.json
package.json

Upgrade:
* `express-handlebars` from 5.3.1 to 6.0.6. It is mostly dependency updates, and 6.x requires node 12
* `nodemailer-express-handlebars` from 4.0.0 to 5.0.0. The major change is requiring `express-handlebars` 6.0.6
There's no feature or security content here, and no changes needed to our code. `express-handlebars` added this to their README:
> **Danger 🔥**
> 
> Never put objects on the `req` object straight in as the data, this can allow hackers to run XSS attacks. Always make sure you are destructuring the values on objects like `req.query` and `req.params`. See https://blog.shoebpatel.com/2021/01/23/The-Secret-Parameter-LFR-and-Potential-RCE-in-NodeJS-Apps/ for more details.
The closest we get to that behaviour is the email test page index, and we validate that the query …

Upgrade handlebars

---

package-lock.json
package.json

Update nodemon from 2.0.4 to 2.0.19. Highlights:
* Updates dependencies
* Replaces `update-notifier` with `simple-update-notifier`, reducing the total dependencies.
* Drops node 8
* Fixes bugs on Windows

Update to nodemon 2.0.19

---

package-lock.json
package.json

Some highlights from the [Changelog](https://github.com/getsentry/sentry-javascript/blob/master/CHANGELOG.md) and [migration guide](https://github.com/getsentry/sentry-javascript/blob/master/MIGRATION.md), which do not affect our code:
* 6.0.0 - Start supporting Release Health
* 6.17.0 - Remove DSN class
* 6.18.0 - Deprecate frameContextLines
* 7.0.0 - Split @sentry/tracing into own package, distribute ES5, drop Node.js v6

Update @sentry/node from v5.27.2 to v7.12.0

---

.circleci/config.yml

Run unit tests against specific PostgreSQL versions, using current CircleCI instructions for a PostgreSQL service container.

CircleCI: Add tests for PostgreSQL versions 9.6.24 and 13.7

---

db/DB.js
db/seeds/test_subscribers.js
tests/db.test.js

Add a test subscriber and email `has_breaches`, with two tests for `getSubscribersWithUnresolvedBreaches`:
* The one subscriber is returned by `getSubscribersWithUnresolvedBreaches`
* No subscribers are returned when the `breach_stats` value is `null`
Update `getSubscribersWithUnresolvedBreaches` so that it works on PostgreSQL 9.6 and later.

MNTOR-854: Add tests for `getSubscribersWithUnresolvedBreaches`, fix query for psql 9.6

---

app-constants.js
db/DB.js
scripts/send-email-to-unresolved-breach-subscribers.js
tests/send-email-to-unresolved-breach-subscribers.test.js

* Move the script logic into functions so that running and initialization can be skipped in tests.
* Add a test to send an email to the test subscriber
* Add `MONTHLY_CRON_LIMIT` sets the maximum number of emails to send.
* Refactor the database functions to allow a limit and a count of total subscribers.

Test monthly email script, add limit

---

package-lock.json
package.json

Update dependencies. This covers:
* Bump dotenv from 8.2.0 to 16.0.2 (from PR #2643)
* Bump sns-validator from 0.3.4 to 0.3.5 (from PR #2642)
* Bump nodemailer from 6.7.5 to 6.7.8 (from PR #2641)
* Bump connect-redis from 5.0.0 to 6.1.3 (from PR #2640)

Dependency updates, September 22, 2022

---

src/app.js

Because of heroku's proxy settings, request / cookies were not persisted between calls. Hence, after login, an error is thrown when `req.session` does not contain the state hash.
Setting the trust proxy to high and securing the cookie allowed the cookie to persist.
If cookie.secure is set as true, for nodejs behind proxy, "trust proxy" needs to be set.

MNTOR-1009: heroku proxy fix

---

src/app.js
src/client/css/global.css
src/client/css/landing.css
src/views/layouts/main.js

Fixes Mozilla logo link hit-area extends full width of footer.  Also makes minor style improvements and uses safe but less-strict default for referrer-policy.

fix Mozilla footer link

---

db/DB.js
tests/controllers/user.test.js

This is a hotfix for v15.3.1, currently in production, to address issue #2744.
Add a test to remove a subscription via the primary verification token and hash. Fix `removeSubscriberByToken` by first deleting the user's emails, to avoid violating the primary key constraint.
This could be better handled by a cascading delete, but that fix should be applied to the main branch.

When unsubscribing a user by token, delete emails

---

db/DB.js
tests/controllers/ses.test.js

When handling a complaint (spam report) or a hard bounce for a primary email that has related emails, log an error and skip deletion. This should address issue #2744.
Alternatively, we could delete the related emails before deleting the subscriber, with or without a log message.

removeEmail: detect and log subscriber with related emails 

---

.github/workflows/unittests.yaml
package-lock.json
src/package.json
src/utils/breach-resolution.test.js
src/utils/breach-summary.test.js
src/utils/fluent.test.js

Run V2 unit tests using GitHub Actions.

MNTOR-1101 run V2 unit tests using Github Actions

---

Dockerfile

Jira: MNTOR-1109
Updates the dockerfile to run `npm start`, which in turn should trigger the V2 sniffer script to load either legacy or refresh site.

docker run `npm start` to trigger V2 script

---

src/package.json

Jira: MNTOR-1109
GCP throws an error when using `rsync` in npm scripts.  This PR switches to using `cp` instead.

replace `rsync` with `cp`

---

package.json

Jira: MNTOR-MNTOR-1109
Figma: 
Reverts test of calling `npm start` directly, since the issue was determined to be caused by dockerflow heartbeats.
- `npm start` should load the legacy site when .env var `MONITOR_V2=false` or undefined
- `npm start` should load the Refresh site when .env var `MONITOR_V2=true`

revert `npm start` now points to Refresh site

---

src/controllers/breaches.js

Jira: MNTOR-978
Figma: n/a
This fix is needed to ensure that when PUT is called, useBreachId field is set to true so GET will not to assume and retrieve based on recency index

MNTOR-978: Fixes for put call (Part 4)

---

src/utils/breaches.js

Jira: MNTOR-978
Figma: n/a
Quick fix for an error present in Heroku testing. When user.breach_resolution is `null`, the destructure fails
- Login with an account that has null `breach_resolution` column
- Make sure the app doesn't error out

MNTOR-978: user.breach_resolution can be null

---

src/client/js/partials/settings.js

Jira: MNTOR-983
Followup to pass CSRF tokens from settings front-end for API calls.

MNTOR-983 - pass CSRF attribute to API calls

---

src/views/email-2022.js

Jira: [MNTOR-1145](https://mozilla-hub.atlassian.net/browse/MNTOR-1145)
Fixes the path to the images for the email template. @toufali we might need to use PNGs for the emails instead of WebP for now since it seems like we are not able to preserve transparency (see screenshots) — or is there a quick and easy fix for that?
| PNG | WebP |
| --- | --- |
| <img width="642" alt="image" src="https://user-images.githubusercontent.com/13835474/216066558-bd22f79d-77cc-4dcc-a943-debbdcb5a9b6.png"> | ![image](https://user-images.githubusercontent.com/13835474/216066342-2c85d081-85b6-4eb5-ba9d-e9d305e0e3f7.png) |
Add a new email on the settings page and checkout the verification email.

fix: Email template images

---

src/controllers/settings.js

Jira: [MNTOR-1154](https://mozilla-hub.atlassian.net/browse/MNTOR-1154)
We need to account for the primary email.
Add emails that should be monitored via the settings page and make sure it’s not possible to add more that four secondary ones.

MNTOR-1154: Fix monitore emails limit

---

src/client/css/global.css
src/views/partials/settings.js

Jira: [MNTOR-1153](https://mozilla-hub.atlassian.net/browse/MNTOR-1153)
Disable the “Add email” button when users reached the limit for observed emails.
Reach the limit of allowed observed emails and try to add an email via the “Add email button” on the settings page

MNTOR-1153: Prevent users from attempting to add more emails than limit

---

package-lock.json
src/app.js
src/controllers/settings.js
src/db/tables/email_addresses.js
src/package.json

This uses a postgres-only knex raw query in order to compare timestamps on the database side.
Jira: MNTOR-1143
Limit how often users can cause verification to be sent to a particular email address to 5 minutes.
1. Adding new secondary email addresses should immediately send a new verification email
2. Click "Resend verification email" within 5 minutes and confirm that API returns error
3. Click "Resend verification email" again after 5 minutes, should send a new verification email

MNTOR-1143 - limit how often users can verify email addresses to 5 minutes, with generic rate limiting for all APIs

---

src/controllers/breaches.js

Jira: MNTOR-1165
On the Breaches page, with my primary email selected, when marking a resolution step complete, the PUT request fails. We were not accounting for the primary email case
1) create a new Monitor account with primary email that has known breaches
2) visit the breaches page and expand a breach
3) tick or untick a resolution step

MNTOR-1165: fix primary email case

---

README.md
package.json
src/package.json

This ensures that anyone with [Volta](https://volta.sh/) installed is running the same versions of Node and npm.

Use Volta to align toolchains

---

package-lock.json
package.json
src/package.json

Jira: MNTOR-
Figma: 
Fixes `Error: The package "esbuild-darwin-64" could not be found, and is needed by esbuild.` triggered via `npm start`, apparently due to outdated ESBuild version.

fix `npm start` error with ESBuild version

---

src/client/css/fonts.css
src/client/css/global.css
src/client/css/partials/breaches.css
src/client/css/partials/landing.css
src/client/css/partials/settings.css
src/client/css/variables.css
src/client/js/partials/breaches.js
src/views/partials/breaches.js

Jira: MNTOR-1086
Figma: https://www.figma.com/file/gvyyqS9egsGjsH0LUDqT1m/Breach-Resolution-Flow-Design?node-id=654%3A16313&t=I1S7G3TnYG1IGh0z-4
Refactor Breaches page zero-states to use a single template with dynamic email updated with state.  
Per @Vinnl [comment](https://github.com/mozilla/blurts-server/pull/2821#discussion_r1101504633), creating a separate zero state for each condition under each email account is not ideal.  This refactor attempts to simplify it by using `selectedEmail` stored in state to inject into a single zero-state, created as needed.
1. Open the breaches page for an email address with zero breaches - it should show the "No breaches found" message and hide the "Unresolved / Resolved" tabs.
2. Open the breaches page for an email address with more …

use template and dynamic email for zero-state

---

src/controllers/auth.js
src/controllers/email-preview.js
src/controllers/hibp.js
src/utils/email.js
src/views/partials/email-breach-alert.js
src/views/partials/email-breach-card.js
src/views/partials/email-signup-report.js

Jira: [MNTOR-1037](https://mozilla-hub.atlassian.net/browse/MNTOR-1037)
Migrates the sign-up report email template.
The ability to preview and send emails from within Monitor is being added by PR #2790. You can view and trigger the email from the emails previewer under `/admin/emails`.

MNTOR-1037: Migrate sign-up email template

---

src/middleware/auth.js

Jira: MNTOR-1198
Figma: n/a
Stage and Heroku crashed because of a bug in admin check middleware:
1. getProfileData errors out (401?) returns e here
```
catch (e) {
console.warn('getProfileData', { stack: e.stack })
return e
}
```
2. requireAdmin middleware thinks it's a json, tries to parse it, cannot parse it
3. Uncaught exception took the server(s) down
1. A login without auth / with stale auth should now be redirected to login page
2. requireAdmin middleware should now utilize `UnauthorizedError` class instead of returning a `401` status

MNTOR-1198: admin middleware json parse fix

---

src/esbuild.js

Jira: MNTOR-1192
Upon initial Breaches page load, the email address displayed in zero-state content does not appear.  This is apparently due to a [known bug with ESBuild](https://github.com/evanw/esbuild/issues/399) and flagged in the current [ESBuild docs](https://esbuild.github.io/api/#splitting).
In addition to causing the email variable to initialize before ready, this has potential impact to other portions of the site.  This PR disables the ESBuild code-splitting functionality with the following rationale:
- The complete client bundle is currently only ~10kB transferred; splitting this down further is unlikely to result in significant  load speed gains
- A ticket exists to set up logical code-splitting depending on partial: 
https://mozilla-hub.atlassian.net/browse/MNTOR-1171
The …

Disable ESBuild code-splitting

---

src/controllers/auth.js
src/controllers/settings.js
src/views/partials/email-signup-report.js

Jira: MNTOR-1199
Figma: 
During auth (especially for sign ups), we are seeing 500s being returned:
```
{"success":false,"status":500,"message":"Cannot read properties of undefined (reading 'slice')","stack":{}}
```
Upon further investigation, the stack trace looks like:
```
ERROR fx-monitor.middleware.error: TypeError: Cannot read properties of undefined (reading 'slice')
at getBreachesForEmail (file:///app/src/utils/hibp.js:190:27)
at confirmed (file:///app/src/controllers/auth.js:105:42)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
which appears to be an issue with `email.sha`
I've also correct a similar error in settings
* Sign up with a new email should not throw the above 500 error anymore

MNTOR-1199: email.sha1 does not exist

---

src/package.json

Jira: MNTOR-1255
This PR disables server restart for client changes.
Currently when making changes to client code, “nodemon” restarts the server.  This important for server changes but is often not necessary for client changes.  Restarting the server means a developer needs to re-login for every change – this can be very time-consuming.  
Note that this change does not include template/partial files in `src/views` because they are technically server-side code.  Disabling server reload for these files might yield unexpected results during development.
- visit the Breaches page after logging in
- make a change to the Breaches page in CSS or client JS, e.g. in `init()` add:
```js
document.body.insertAdjacentHTML('afterbegin', '<h1>TESTING TESTING 123</h1>')
``` 
- reload the Breaches page …

Disable server restart for client file changes

---

locales/en/breaches.ftl
src/client/js/partials/add-email.js
src/client/js/partials/breaches.js
src/controllers/breaches.js
src/controllers/settings.js
src/controllers/settings.test.js
src/views/partials/breaches.js

Jira: MNTOR-1188
With this PR:
- the "monitored email" count in the header panel should only display verified email count
- the “Add email address” link in the header panel should open the “Settings” page instead of the “Add email” dialog
- the “Add email address” buttons in the Breaches table “zero-state” should continue to open the “Add email” dialog
- the “Add email address” buttons in the Breaches table “zero-state” should dynamically disappear after the user has reached their limit
TODO: Waiting for UX decision on whether the header link should read "manage emails" instead of "add email address".
Visit the breaches page and test the acceptance criteria above.

Mntor 1188/breaches email count

---

src/client/js/partials/breaches.js

Jira: MNTOR-1134
Figma: N/A
Whenever a user ticks a checkbox on the Breaches page, a call to the server is made to store the updated data.  In order to deter “button mashing” and flooding the server with calls, these checkbox is now in a disabled state until the server call has completed.
[Screencast from 2023-02-20 17-54-06.webm](https://user-images.githubusercontent.com/4251/220164213-3bf0e7cf-2976-47c2-ba27-edae6e58b5e5.webm)
Check a breach step, then try to check it again while it's submitting.

Disable step checkbox while applying changes

---

src/controllers/auth.js
src/utils/email.js
src/views/emails/email-breach-alert.js
src/views/emails/email-breach-card.js
src/views/emails/email-signup-report.js

Jira: [MNTOR-1258](https://mozilla-hub.atlassian.net/browse/MNTOR-1258)
Fix the generation of the sign-up email template for users that sign up with an email that is not involved in a relevant breach.
1. Sign up with an email address that has no relevant associated breaches.
2. Check out the email that we send upon sign-up.

Fix sign-up email template for emails with no breaches

---

src/routes/index.js

Jira: [MNTOR-1264](https://mozilla-hub.atlassian.net/browse/MNTOR-1264)
Do not enable the non-auth preview route on prod.
Navigate to `/preview/emails`: Dev should work as expected and staging is expected to show a `404`.

Disable non-auth previews on prod

---

package-lock.json
package.json
src/app.js
src/utils/redis-mock.js

Jira: MNTOR-1269
Our app uses Node's `AsyncLocalStorage` API to persist a user's locale in a request thread.  This is done to avoid redundantly calling `negotiateLanguages` and to avoid having to pass down the request object to locale functions.  `node-redis` < v4 breaks this API by overwriting the value with `undefined`, and causing our app to default to English translations.
Simply upgrading `node-redis` to latest has a ripple effect breaking `connect-redis` and `redis-mock` in the process.  This PR addresses all the above.
Using `redis-mock`: 
1. update your env var to `REDIS_URL=redis-mock`
2. change your preferred website language to a Monitor-supported language other than English
3. start the server
4. visit the Landing page, confirm the language you chose is displayed.
5. log in …

fix redis overwriting `AsyncLocalStore`

---

src/client/js/dialog.js

Jira: MNTOR-1275
To serve localized content, the app listens for `text/html` requests and updates the locale accordingly.  The dialog/modal fetch did not specify that it needs a `text/html` response and therefore locale was ignored.  This PR adds the required `Accept` header to a dialog request, enabling localization.
1. change your preferred website language to something other than English
2. login to an account that allows adding additional emails
3. trigger the "Add new email" dialog by clicking the button in Settings or in Breaches zero-state.
4. confirm the dialog is displayed in the specified language.

set `Accept` header to request localized dialog

---

src/app.js

Jira: MNTOR-1285
Fix for broken Heroku servers due to apparent Redis 4 incompatibility

fix heroku/redis 4 crashes

---

src/client/js/app.js
src/client/js/index.js
src/client/js/partials/add-email.js
src/client/js/partials/settings.js

Jira: MNTOR-1189
After a user adds a new email from the dialog on the Settings page, if they click the close button (x) they return to the settings screen which has not been updated with the newly added email.  This PR listens for that sequence of events (add email -> close dialog) and reloads the page if triggered.
This is a preliminary measure – for future updates/refactor we could look into making this page reactive to avoid reload.
Also included in this PR is a related bug fix for toast errors not displaying over the dialog scrim.  This error message is not localized and requires more work under [separate PR](https://mozilla-hub.atlassian.net/browse/MNTOR-1271).
1. visit the Settings page
2. add a new email
3. close the dialog via the "x" close button
4. confirm the new email is …

reload Settings page to show newly added email

---

.eslintrc.json
locales/en/breaches.ftl
src/client/css/partials/breaches.css
src/controllers/breaches.js
src/utils/breach-resolution.js
src/utils/breach-resolution.test.js
src/utils/country-code.js
src/utils/country-code.test.js

Jira: MNTOR-1322
Figma: N/A
Some of the breach resolutions reference external services; this PR turns those into links. Also tagging @mansaj, since he added the original `<a>` tags to a couple of strings, just in case he had a plan for turning those into links that I missed.
Not all resolutions apply to all countries. I've added some code to detect the user's country through their IP address based on [similar code in Relay](https://github.com/mozilla/fx-private-relay/blob/0d14ccf6f894b09b0ae13026a4b54226ac12c025/privaterelay/utils.py#L20-L27), which I think is also applicable to Monitor. Additionally, I added a guard that checks that we do not show resolutions that involve going to the breached company's website when we don't actually know where that website is.
The way I implemented the …

Add relevant links to breach resolutions

---

src/client/js/partials/unsubscribe.js

Jira: MNTOR-1355
- confirm the following error or similar no longer appears on non-unsubscribe pages:
```
Uncaught TypeError: unsubscribeButton is null
<anonymous> http://localhost:6060/js/partials/unsubscribe.js:7
```
- confirm the "Add email" button on the settings page triggers the modal/works as expected.

fix null unsubscribeButton on irrelevant pages

---

src/utils/hibp.js

Instead of waiting for the icon downloads to finish (which can take a while, even if we already have a cache of the images - disk access is slow), we just continue starting the server, and any sessions that load before the icon download has finished will show the fallback letter-based icons. A page refresh should then result in the actual icons being shown.

Don't pause server start for icon download

---

src/client/css/partials/breaches.css
src/views/partials/breaches.js

Jira: MNTOR-1350 & MNTOR-1406
With the addition of company logos, the company name ellipses broke.  Additionally, fallback logos created from the company's first initial are squished/cut-off.  This PR aims to fix both issues.
You'll need a breach with company name that's longer than most, and a breached company that does not have a logo (falls back on circle with company initial)
- Visit the breaches page
- reduce your viewport width until company name no longer fits within the column
- confirm ellipses show up and that the text is not abruptly cut-off
- confirm any fallback items are not squished/cut-off

fix broken company ellipses and fallback icon

---

src/utils/hibp.js

We already handled non-success responses when fetching a site's favicon by simply not storing an icon. However, if the request failed (i.e. no response came in in the first place, e.g. because the network is down), we didn't handle the error. This change ensures that in those cases, too, we just do not save an icon.
Disable your internet, then start the server. It should not stop initialising with a bunch of errors trying to fetch

Don't stop the server if icons couldn't be fetched

---

src/client/js/partials/unsubscribe.js
src/controllers/unsubscribe.js
src/views/partials/unsubscribe.js

Jira: MNTOR-1438
Figma: N/A
It should now no longer be possible to pass arbitrary HTML (e.g. including malicious JS, though our CSP blocks that) into the query parameters and have that show up on the unsubscribe page. Additionally, the query parameters get validated, and only the relevant parameters are sent to the back-end.
Note: I don't actually know how to get to the unsubscribe page with valid parameters, so I haven't been able to verify that I'm not actually breaking unsubscription - would be good to get some input there.
Visit `/user/unsubscribe?'"><marquee><h1>In ur HTML</h1></marquee>` - you should just see an unmodified "Unsubscribe" button.
Also, visit `/user/unsubscribe?token={"__proto__":"{"test":"ouch"}}&hash=hi`, and verify that the token is passed as a verbatim string to …

Don't pass unsanitised user input into HTML

---

src/app.js
src/middleware/noSearchEngineIndex.js
src/routes/index.js

Jira: MNTOR-1351
Figma: N/A
Previously we provided a robots.txt, telling search engines and other bots not to proactively visit our stage and dev sites. That's good for reducing the load, but won't tell them not to add our dev and stage sites to their search indexes. The X-Robots-Tag: noindex header does.
Note that this also required removing the robots.txt, since otherwise that would tell search engines not to crawl those headers, apparently.
See also:
https://developers.google.com/search/docs/crawling-indexing/block-indexing
Visit a resource locally, and verify that it has the ` X-Robots-Tag: noindex` header. That doesn't test all the way until seeing that search engines actually do not index our content, but I don't know of a way to do that.

Prevent search engines from indexing non-prod envs

---

src/utils/breach-resolution.js

Jira: MNTOR-1446
Figma: N/A
Adds UTM parameters for links to Mozilla websites in breach resolutions.
With an account with breaches, verify that the links to Relay, password manager, and VPN include UTM parameters.

Add UTM parameters to links to Mozilla websites

---

src/client/css/partials/breachDetails.css
src/package.json

Jira: MNTOR-1470
- ~Fixes path for images displayed on breach details pages~
- Fixes SVGO cli recursive flag not working as expected:
https://github.com/svg/svgo#cli-usage (suggests -f for recursive)
https://github.com/svg/svgo/issues/1269 (suggests -f _and_ -r)
visit a breach detail page and confirm images next to recommendations display as expected (see screenshot above)

Mntor 1470/fix broken seo images

---

src/client/js/partials/breaches.js

Jira: MNTOR-1440
Small followup to MNTOR-1440 to include `data-classes` (email-adress, ip-address, etc)

MNTOR-1440 fixup: include data_class with Breach Item GA event

---

src/views/guestLayout.js
src/views/mainLayout.js

Jira: MNTOR-1439
Figma: N/A
Not all social media websites implement the same (or any) fallbacks for preview cards, so we have to add them redundantly to make sure they show up everywhere.
You should be able to use https://cards-dev.twitter.com/validator if you have a Twitter account after it is deployed. Until then, you can only check the meta tags yourself, I suppose.

Add redundant social media preview tags

---

src/client/images/icon-help.svg

Jira: MNTOR-1471
Figma: N/A
The other icons are all 16x16, with a canvas size of 24x24. It'd probably be safer if our icons did not include padding inside the images themselves, but had that added through CSS, but that's a larger refactor that would involve checking all our icons and their uses.
Previous:
Open the user menu, verify that all icons are aligned.

Use consistent spacing for "Help and support" icon

---

src/controllers/settings.js
src/db/tables/subscribers.js

Jira: MNTOR-1180
When a user deletes a secondary email from Settings, the email is deleted from the email_addresses table but the breach resolutions aren't updated to reflect the change. This becomes an issue for 1) data retention 2) when we run our migration script, it returns a lot of false positives since our scripts still think those emails exist
Current:
* Use a secondary email to resolve some breaches
* Delete secondary email from Settings
* Add email back 
* The breach resolution state remains
Fix:
* Use a secondary email to resolve some breaches
* Delete secondary email from Settings
* Add email back 
* The breach resolution state should be reset (0 marked as resolved)

MNTOR-1180: removal of resolution when email is removed

---

src/client/js/partials/add-email.js

Jira: MNTOR-1437
@pdehaan noticed that I missed an event, GA4 only allows _ as separator in custom event names.

MNTOR-1437 fixup: do not use spaces in add_email GA event

---

src/client/css/partials/allBreaches.css

Jira: MNTOR-1481
Figma: N/A
Breach cards used to have a minimum size of
min-width + 2 * padding-md, but with the container's marging added to that, that wouldn't fit on screens as small as 360px wide. Thus, the cards are now constrained to min-width, and extra padding is subtracted from that.
Go to `/breaches`, resize your screen.

Make breach cards fit in small screens

---

src/client/js/components/custom-select.js

Jira: [MNTOR-1475](https://mozilla-hub.atlassian.net/browse/MNTOR-1475)
It’s possible that `temp` has a width of `0` when trying to retrieve its bounding rect. Let’s wait for the next tick to make sure its dimensions are calculated correctly.
1. Open Safari on macOS
2. Visit the dashboard `/user/breaches` and reload multiple times (~10-20 always did it for me)
3. Make sure that the width of the select is bigger than `5px`

MNTOR-1475: Wait for custom email select width to be available

---

src/scripts/kube-jobs/recencyToBreachId.js

Simplify where statement to ignore the check of db_migration_1 col

MNTOR-1395: simplify where statement

---

src/db/tables/subscribers.js

Jira: MNTOR-1491
This ticket addresses a bug for deleting resolution when a user deletes a secondary email. The code currently does not handle the case when resolution field is empty
* add a secondary email to an account
* make sure the account does not have breaches resolved or checked (column null in database)
* delete the email
* you should see a log `No resolution with [email] found, skip`

MNTOR-1491: fix null pointer exception

---

src/client/css/partials/breachDetails.css
src/controllers/breach-details.js
src/views/partials/breach-detail.js

Jira: MNTOR-1494
Figma: N/A
It'll be lower quality than the organic, free-range, hand-crafted logos served from our CDN, but at least it'll free up Maxx to learn some Qt. Meanwhile design can come up with a new design that doesn't feature the logos at this size.
An ugly one:
[(Current)](https://monitor.firefox.com/breach-details/SlideTeam)
An OK one:
([Current](https://monitor.firefox.com/breach-details/FaceUP) uses a logo rather than an icon.)
Without a found favicon:
Visit http://localhost:6060/breaches, then open a couple of individual breaches.

Also use cached favicon on breach detail page

---

src/controllers/auth.js
src/controllers/email-preview.js
src/controllers/hibp.js
src/utils/breach-logo.js
src/utils/email.js
src/views/emails/email-2022.js
src/views/emails/email-breach-alert.js
src/views/emails/email-breach-card.js
src/views/emails/email-signup-report.js

Jira: [MNTOR-1496](https://mozilla-hub.atlassian.net/browse/MNTOR-1496)
This adds the logos and fallback icon we introduced for the breaches to the email breach notifications.
| Logo available | Logo fallback |
| --- | --- |
|  <img width="510" alt="breach-notification-icon" src="https://user-images.githubusercontent.com/13835474/229140799-f9a95d60-a95b-4ea5-943b-ca53d36aa9be.png"> | <img width="506" alt="breach-notification-fallback" src="https://user-images.githubusercontent.com/13835474/229140851-dcac307b-35e8-412c-8c7b-c1ae9f7e652e.png"> |
Visit `/admin/emails/notification` and send yourself a test email.

Use cached logos and fallback icons for breach email

---

src/views/guestLayout.js
src/views/mainLayout.js

Jira: MNTOR-1440
`gtag.js` appears to load fine in Firefox, but fails when trying to submit data:
`
Cookie “_ga_[...]” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
`
Followed by:
`
Cookie “_ga_[...]” has been rejected for invalid domain.
`
Use the site with Firefox network devtools open:
HTTP `POST` to `https://www.google-analytics.com/g/collect` succeeds with HTTP …

MNTOR-1440 fixup: allow third-party GA cookie for Firefox standard tracking protection

---

src/views/guestLayout.js
src/views/mainLayout.js

Jira: MNTOR-1509
We are currently trying to read `navigator.doNotTrack`, but this is deprecated and not supported in Safari https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack - browsers seem to be moving away from DNT and towards using tracking protection in the client anyway.
I think we should just remove it for now.

MNTOR-1509 remove doNotTrack handling

---

.circleci/config.yml
.eslintrc.json
package-lock.json
package.json
src/app-constants.js
src/client/js/components/circle-chart.js
src/client/js/components/custom-select.js
src/client/js/components/toast-alert.js
src/controllers/settings.js
src/custom-types.d.ts
src/db/tables/email_addresses.js
src/utils/email.test.js
src/utils/error.js
src/utils/fluent.js
src/views/partials/add-email.js
src/views/partials/admin.js
src/views/partials/settings.js
src/views/partials/unsubscribe.js
tsconfig.json

This adds a CI check to verify the type annotations for the following files, as per the discussion in Slack and the eng meeting:
- `src/client/js/components/**/*`
- `src/views/partials/add-email.js`
- `src/views/partials/admin.js`
We can fix the type annotations for additional files as we go, and add them to `tsconfig.json` to get them checked. If you use VSCode or another editor that supports TypeScript, it'll also warn you inline if you introduce mistakes.
We could also add a separate `tsconfig.json` for local vs. in CI, where the local one covers all files in `src/` (and maybe allows implicit `any`s), but I imagine the number of red squigglies could get quite annoying quickly, so let's save that for a followup PR, maybe.

Add type checking for a couple of files

---

src/views/guestLayout.js
src/views/mainLayout.js

Jira: MNTOR-1509
The Do Not Track (DNT) header is deprecated and not implemented in all browsers (notably Safari), but until we have a better opt-out mechanism we should keep this in place to be consistent with other Mozilla sites.

MNTOR-1509 - re-implement DNT check so it works with Safari

---

src/controllers/exposure-scan.js
src/controllers/exposures.js
src/custom-types.d.ts
src/routes/user.js
src/views/guestLayout.js
src/views/mainLayout.js
src/views/partials/exposures-list.js
src/views/partials/exposures-setup.js
tsconfig.json

This should make it easier to work on both in parallel while minimising conflicts.
Jira: MNTOR-1544
Figma: https://www.figma.com/file/iJFOikscJeplRBOuKOtYEW/Onboarding?node-id=297%3A26021&t=AExoU4tTaoOmlEt9-4
This adds a `/user/exposures` route, which should eventually show the exposure scan signup if the user hasn't gone through that signup before, and shows the exposures dashboard otherwise.
Note that I added all files to the `tsconfig.json`; if you need help with defining type definitions, either let me know, or remove the file you're working on from `tsconfig.json`. (Try it out by running `npm run lint:ts` in the project root.)
The new route isn't linked to, so it should not block production deployments.
Visit `/user/exposures`. You should be prompted to log in, and see the partial …

Add routes for exposure scan signup and overview

---

src/client/css/partials/exposureScan.css

Jira: MNTOR-1545
Figma: N/A
The layout looked all bunched up on iOS:
This PR fixes that.
Do a scan from the landing page on iOS. Things shouldn't overlap.

Fix bunched-up layout on iOS on the exposure scan

---

src/client/js/partials/allBreaches.js

Jira: MNTOR-1479
Figma: N/A
On the public breach list, the search input that filters the list of breaches would respond to `keyup` events specifically, rather than anything that might change the input. Thus, if (e.g. in Chrome or Safari) a browser adds a "Clear input" icon to the field and the user clicks that, the field gets emptied, but the list of breaches are still narrowed down to the previous input.
[Screencast from 2023-04-17 12-28-50.webm](https://user-images.githubusercontent.com/4251/232458914-04d835de-b2e4-4693-a50c-2c7168a0751e.webm)
Visit `/breaches` in a Blink or WebKit browser, type something in the search field, then clear the field. The filter should get reset.

Update filter results when clearing search field

---

src/client/css/partials/exposureScan.css

Jira: MNTOR-1547
Figma: N/A
On large viewports, we don't want the hero content part to endlessly grow if the user's email address happens to be ridiculously long. This change limits it to a reasonable size that maintains readability for the regular content, and truncates the email address if it is wider than that.
Previously:
Enter a very long email address to scan for.

Add a maximum width for email address

---

.env-dist
db/migrations/20230413104243_add_onerep_profile_id.js
src/appConstants.js
src/client/js/partials/exposuresSetup.js
src/controllers/exposures.js
src/controllers/storeExposureScanData.js
src/custom-types.d.ts
src/db/tables/subscribers.js
src/db/tables/subscribers_types.d.ts
src/external/onerep.js
src/routes/api/v1/user.js
src/routes/user.js
src/utils/parse.js
src/utils/states.js
src/views/partials/exposuresList.js
src/views/partials/exposuresSetup.js
tsconfig.json

Jira: MNTOR-1543
Figma: https://www.figma.com/file/iJFOikscJeplRBOuKOtYEW/Onboarding?node-id=297%3A26021&t=AExoU4tTaoOmlEt9-4
This adds an API at `/api/v1/user/exposures/` that allows passing in the data to scan for to find exposures. And adds a button at `/user/exposures` to send mock data to that API, to test it out.
Make sure to run the migrations first and add the sandbox `ONEREP_API_KEY` to your env vars (ask me or Amri), then visit http://localhost:6060/user/exposures. Open your browser's network console before you click the button. After clicking it, your user should have a OneRep profile ID, and no longer be shown the button.

Add API to store data to scan for exposures

---

src/appConstants.js

For testing features that are dependent on `env` variables it would be helpful to have a way to mock and change [AppConstants](https://github.com/mozilla/blurts-server/blob/main/src/appConstants.js) on the fly when running tests.
As a concrete example: This change would enable us to add more thorough tests to for the link block list we’ll introduce with PR #2961 and [was brought up](https://github.com/mozilla/blurts-server/pull/2961#discussion_r1170198870) by @Vinnl.

Don’t freeze AppConstants for tests

---

src/utils/breachResolution.test.js

Additional tests for the blocked company domain links in the breach resolution as requested and promised in https://github.com/mozilla/blurts-server/pull/2961#discussion_r1170343857.

Additional tests for blocklisted breach resolution links

---

src/routes/index.js

Jira: MNTOR-1464
Figma:  N/A
When users end up at `/security-tips` (e.g. by following old links from elsewhere), redirect them somewhere userful, rather than giving them a 404.
Go to `/security-tips`.

Redirect users following links to /security-tips

---

src/client/css/partials/landing.css

When a user with the Relay add-on installed visits the homepage, the injected Relay icon is outside of the email input.
Jira: https://mozilla-hub.atlassian.net/browse/MNTOR-1592
- Test in Firefox browser
- Install [Relay add-on](https://addons.mozilla.org/en-US/firefox/addon/private-relay/) and log into Relay
- Open homepage
- **Expected:** The Relay icon should be inside the email input form

Fix issue where Relay icon was outside of email input

---

README.md

Amri [pointed out](https://mozilla.slack.com/archives/C04BLQVN151/p1683645520098899?thread_ts=1683640128.490769&cid=C04BLQVN151) that setting up Redis will preserve sessions across session restarts, which I figured was worth documenting.

Add note on running Redis locally

---

src/views/partials/landing.js

Jira: MNTOR-
Figma: 
Noticed while trying to lint some HTML on staging.
```sh
git grep -En "scan-email-ad{2,3}ress" src | cat
src/views/partials/landing.js:13:      <label for="scan-email-adddress" class="visually-hidden">
src/views/partials/landing.js:17:        id="scan-email-address"
```
```txt
Error: The value of the for attribute of the label element must be the ID of a non-hidden form control.
From line 62, column 7; to line 62, column 63
n">↩      <label for="scan-email-adddress" class="visually-hidden">↩     
```

Fix adddress typo in landing partial

---

.stylelintrc

Jira: MNTOR-
Figma: 
Removes the `The "string-quotes" rule is deprecated.` deprecation warning when running <kbd>npm run lint:css</kbd>.
```diff
npm run lint:css
-Deprecation warnings:
- - The "string-quotes" rule is deprecated.
src/client/css/nav.css
78:1  ⚠  Expected selector "nav .callouts a" to come before selector "nav.site-nav a:not(.current):hover"  no-descending-specificity
src/client/css/partials/breachDetail.css
259:1  ⚠  Expected selector ".breach-detail-recommendation dd a" to come before selector ".breach-detail-attribution a:hover"  no-descending-specificity
src/client/css/partials/breaches.css
300:1  ⚠  Expected selector ".zero-state p" to come before selector ".breaches-table details > article p:first-of-type"             no-descending-specificity
300:1  ⚠  Expected …
```

Remove deprecated stylelint string-quotes rule

---

src/client/css/partials/landing.css
src/views/partials/landing.js

This PR solves a few extra issues that pop-up from solving [MNTOR-1592](https://mozilla-hub.atlassian.net/browse/MNTOR-1592)
See #3020 for more context
Jira: [MNTOR-1598](https://mozilla-hub.atlassian.net/browse/MNTOR-1598)
Jira: [MNTOR-1600](https://mozilla-hub.atlassian.net/browse/MNTOR-1600)
Figma: N/A
- Test in Firefox browser
- Install [Relay add-on](https://addons.mozilla.org/en-US/firefox/addon/private-relay/) and log into Relay
- Open homepage
- **Expected:** The Relay icon should be inside the email input form

Fix MNTOR-1598 - Add wrapper to input form on homepage breach scan

---

src/app/api/auth/[...nextauth]/route.ts

Jira: MNTOR-1624
Supercedes https://github.com/mozilla/blurts-server/pull/3051
Finally managed to find the correct incantations to successfully authenticate against FxA using Next-Auth :tada: 
Add the following two variables to your .env:
```
NEXTAUTH_URL=http://localhost:6060
NEXTAUTH_SECRET=<generate using `openssl rand -base64 32`>
```
You can then add <SignInButton/> to e.g. the landing page to kick off authentication.

Make Next-Auth work with FxA

---

package-lock.json
package.json
patches/intel+1.2.0.patch
src/app/api/auth/[...nextauth]/route.ts
src/customTypes.d.ts
src/utils/log.js

Jira: MNTOR-1643
Figma: N/A
Unfortunately, this required patching the `intel` package in a `postinstall` script. That said, since that package hasn't been updated in six years, this should be relatively safe.
The problem is that `intel` was trying to dynamically determine which modules to load based on which files were present in its directory. However, since Next.js moves (and presumably bundles) Node modules into the `.next` folder, it was unable to find the modules that `mozlog` was expecting to use.
The patch fixes this by simply explicitly importing those four modules.
You should not encounter mozlog-related errors anymore when running the application.

Make mozlog work with Next.js

---

.github/workflows/conflicts.yml

This adds a CI job that checks that there are no conflict markers checked in. Direct reason: I fixed some conflicts in https://github.com/mozilla/blurts-server/pull/3073, but [missed one](https://github.com/mozilla/blurts-server/commit/f307c8752e02ae41efa83626467ce0984659dad6).

Prevent merging unresolved conflicts

---

src/client/js/partials/breaches.js

Currently on stage, you get an error message when resolving a breach and no error occurred:

Don't show error when everything was OK

---

src/utils/utmParams.js
src/views/partials/floatingBanner.js
tsconfig.json

Jira: [MNTOR-1664](https://mozilla-hub.atlassian.net/browse/MNTOR-1664)
Follow up for https://github.com/mozilla/blurts-server/pull/3067: We are adding UTM params to the floating banner link.
1. Set the following `.env` variables:
```
FLOATING_BANNER_DELAY=5000
FLOATING_BANNER_LINK='https://www.mozilla.org/newsletter/security-and-privacy/'
FLOATING_BANNER_TYPE='newsletterSignupBanner'
FLOATING_BANNER_PAGES='/breaches,/user/breaches'
```
2. The Banner should be shown after a delay of `5000 ms` when navigating to `/breaches` or `/user/breaches`.
3. The sign-up link should have the UTM parameters appended to it.
4. After following the sign-up link or dismissing the banner once a user should not see the banner again.

Add UTM params to floating banner link

---

next.config.js

Jira: MNTOR-1640
Figma:  N/A
This adds the Next.js equivalent to https://github.com/mozilla/blurts-server/blob/83a32d11b4a95abbde24088fa9dcdcba2c5fc00a/src/routes/index.js#L42-L43
See also https://nextjs.org/docs/app/api-reference/next-config-js/redirects
Start the Next.js server, go to `/security-tips`.

Add a redirect from /security-tips for Next.js

---

src/app.js
src/utils/hibp.js

Jira: MNTOR-1773
We saw some exceptions and error messages that indicated that exceptions were not being loaded into app local storage, but we only actually got Sentry exceptions (with stack traces etc) from the settings code trying to read it.
This is because the Sentry error handler is loaded (as Express middleware) pretty late in startup, this PR moves it to load as early as possible.
EDIT: see also https://github.com/mozilla/blurts-server/pull/3088#issuecomment-1569539983 - the function that is throwing the exception we want is actually swallowing the exception and throwing a more generic message, but we want that stack trace! I've added a commit to address this as well.
I did a positive test by making sure that the app functions correctly and passes tests, and a negative test by …

MNTOR-1773/move sentry error handler earlier in startup

---

src/app/(nextjs_migration)/(guest)/user/unsubscribe-monthly/page.tsx

Jira: MNTOR-1634
Figma: N/A
Adds the page to unsubscribe from the monthly emails.
Visit http://localhost:6060/user/unsubscribe-monthly?token=token_123&hash=hash_123. Also note how this is in the `(guest)` route group, even though it shares a path (`/user/`) with routes in the `(authenticated)` group - nevertheless, the authenticated dashboard still works.

Port unsubscribe-monthly page to Next.js

---

src/app/(nextjs_migration)/(authenticated)/user/breaches/page.tsx
src/app/api/auth/[...nextauth]/route.ts
src/app/functions/server/getUserBreaches.ts
src/app/transitionTypes.ts
src/db/tables/emailAddresses.js
src/next-auth.d.ts
src/utils/fluent.js
src/views/emails/email2022.js
src/views/emails/emailSignupReport.js

Jira: MNTOR-1774 and MNTOR-1775
Figma: N/A
This does a couple of things:
- It adds a `getStringLookup` API to ease the transition from old Fluent functions (which depend on the user's locale being stored in AsyncLocalStorage). It will behave the same as the old getMessage() when called as-is, but when passed an instance of ReactLocalization (which we have access to in Next.js routes), it will retrieve the localised string from that.
- It updates the code that sends the breach check email on first sign-in to pass an instance of ReactLocalization.
- It splits session data and JWT properties to separate data provided to use by FxA from data we store in our own database.
- It checks if the user that signs in is already known in our database, and if not, it adds them. It does so using mostly …

Store new users in the database

---

.stylelintrc
.vscode/settings.json
src/client/css/partials/floatingBanner.css

Jira: MNTOR-1819
Figma: N/A
Safari on iOS <16.4, which is still widely used (e.g. by the iPhone 13), doesn't support them.
The max-width media query was rewritten to the range syntax by our format-on-save setting, so I also disabled that.
Visit the dashboard using a browser that doesn't support [range syntax](https://caniuse.com/css-media-range-syntax) for media queries, such as Safari before 16.4. Wait until the banner from https://github.com/mozilla/blurts-server/pull/3067 appears, and check that the buttons are stacked on a small screen.

Fix media query not working on Safari

---

public/nextjs_migration/client/js/emailPreview.js
src/app/(nextjs_migration)/(authenticated)/admin/emails/[template]/page.tsx
src/app/(nextjs_migration)/(authenticated)/admin/emails/page.tsx
src/app/(nextjs_migration)/(authenticated)/admin/layout.tsx
src/app/(nextjs_migration)/(authenticated)/admin/page.tsx
src/app/(nextjs_migration)/(authenticated)/admin/send-test-email/route.ts
src/utils/email.js
src/views/emails/email2022.js
src/views/emails/emailBreachAlert.js
src/views/emails/emailBreachCard.js
src/views/emails/emailMonthlyUnresolved.js
src/views/emails/emailSignupReport.js
src/views/emails/emailVerify.js

Jira: MNTOR-1639
Figma: N/A
This recreated the admin page. Note that the Notification email doesn't work yet, because I don't know how to trigger the Cloud Function. Guidance appreciated :)
Visit `/admin` while logged in to an account that is listed in the `ADMINS` environment variable.

Port admin pages to Next.js

---

next.config.js
src/app/(nextjs_migration)/(authenticated)/admin/emails/[template]/page.tsx
src/app/(nextjs_migration)/(authenticated)/user/breaches/page.tsx
src/app/(nextjs_migration)/(authenticated)/user/settings/page.tsx
src/app/(nextjs_migration)/(guest)/breaches/page.tsx
src/app/(nextjs_migration)/(guest)/page.tsx
src/app/(nextjs_migration)/(guest)/scan/page.tsx
src/app/(nextjs_migration)/components/client/UserMenu.tsx
src/app/(nextjs_migration)/layout.tsx

A couple of changes that were necessary to make the built+deployed version work:
- Add `type="module"` to `<script>` tag for the ported client-side scripts. We already had this on the old website, and it gives each module its own scope - which is good, because there are overlapping identifiers in them (e.g. `init`).
- Fix the loading of the user's avatar - we used Next.js's `<Image>` component, but the avatar is an SVG, which it doesn't load.
- Use `<BreachLogo>` to display a company's logo on the dashboard as well. We already used it on the public breach pages as a replacement for the previous function that generated an HTML string.
- Allow Next.js's dynamically-injected scripts in our Content Security Policy.
This branch is currently deployed to Heroku, where you can see it in action. …

Nextjs premerge

---

src/app/[slug]/route.ts

Jira: MNTOR-1838
Figma: N/A
To ensure breach data and icons are available as soon as possible, this starts fetching them as soon as the __heartbeat__ endpoint receives a call. Note that they won't _delay_ that call; the Response is sent while the Promise callback is still pending. The icons and breach data shouldn't get refetched on _every_ heartbeat; new fetches are only started if there's no existing data.
This PR is just a proposal, but feel free to point out reasons this isn't a good idea.
Delete `public/logo_cache` if it exists, then visit `/__heatbeat__/`. Verify that the response still comes in instantly.

Fetch breach data and icons on heartbeat

---

src/app/(nextjs_migration)/(authenticated)/user/layout.tsx
src/app/(nextjs_migration)/(guest)/layout.tsx
src/app/(nextjs_migration)/(guest)/page.tsx
src/app/(nextjs_migration)/layout.tsx

I’ve noticed that there is a layout shift that happens pretty late with the `Next.js` version of the landing page in comparison to https://monitor.firefox.com/. The `Script` tag seems to not pre/async load `/nextjs_migration/client/js/resizeObserver.js` and ignores the attributes. One workaround would be to just add the scripts that we depend on for setting the layout correctly with HTML `script` tags.
**Before**
https://github.com/mozilla/blurts-server/assets/13835474/6439fa7d-7c30-47f8-9d99-7d49905200f0
**After**
https://github.com/mozilla/blurts-server/assets/13835474/c6a97fe1-2e7e-4e59-8326-d8e4d800e1a1
- Visit `/` and reload the page
- Compare page load with `main`

Initial landing page loading enhancements

---

src/app/(nextjs_migration)/(guest)/page.tsx

Found while testing the new Next.js code in dev/stage. Verified the error doesn't exist on prod currently, so looks like a regression from the migration.
```
Incorrect use of <label for=FORM_ELEMENT>
The label's for attribute doesn't match any element id. This might prevent the browser from correctly autofilling the form and accessibility tools from working correctly.
To fix this issue, make sure the label's for attribute references the correct id of a form field.
```
Jira: MNTOR-
Figma: 

Typo in scan-email-address label on homepage

---

src/app/api/auth/[...nextauth]/route.ts

Request subscription scope when authenticating, as some of our RPs are not yet allowed.
This will fail early vs. just silently not working.
Jira: MNTOR-1385
Whether or not this works depends on the configuration of the environment on the FxA side, on investigating with SRE we found several client IDs registered for Fxa staging, most of which we are no longer using on the Monitor team.
SRE is adding the scope to our existing client IDs now, and we will work separately to deprecate any unused client IDs so there isn't confusing in the future. Additionally, SRE will enable this for production before we ship this feature (which is behind a flag).

MNTOR-1385 - request subscription scope, as some of our RPs are not yet allowed

---

package.json
src/app/(nextjs_migration)/(guest)/breach-details/[breachName]/page.tsx
src/client/css/partials/breaches.css

This fixes a couple of small things:
- Makes the HIBP link on the breach detail page clickable again ([example of bug](https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/breach-details/JDGroup))
- Starts the built server on port 6060 as well (which aligns with the redirect URLs configured for FxA)
- Makes sure the breach icons are also vertically aligned on the dashboard, by applying styles that were no longer applied by using the new icon component.

A couple of small fixes

---

src/app/layout.tsx

This ensures that relative URLs (such as those in
`openGraph.images`) resolve to the correct URL, and thus fixes the problem called out by @pdehaan in https://github.com/mozilla/blurts-server/pull/3134#issuecomment-1593770158.
We should be able to properly test this on stage, but it does give confidence that a warning about this got removed from the build log, and that [the docs say](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase):
> The field's relative path will be composed with metadataBase to form a fully qualified URL.
If not configured, metadataBase is automatically populated with a [default value](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#default-value).
It should also apply for all other pages:
> metadataBase is …

Set the base path for metadata

---

src/views/emails/email2022.js

Since this is the same fix as in https://github.com/mozilla/blurts-server/pull/3134/commits/add1e8ecf889fbc819b6c86ac34496fdc7cec876, I figured I'd quickly apply it here too.
Jira: MNTOR-1858

Fix HIBP link in verification email

---

sentry.client.config.ts
sentry.server.config.ts

This is a small config change for the Heroku dev env to send in more performance and log debug data for Sentry. It causes Heroku (and local development, if enabled with the `SENTRY_DSN` and `NEXT_PUBLIC_SENTRY_DSN` env vars) to log to the console and also set the traces sample rate to 100%.
Production (and any other environments such as stage) will have the trace sample rate set to 1% and disabled debug logging.

config: send more debug info from dev/heroku envs

---

.env-dist
sentry.edge.config.ts
src/app/(nextjs_migration)/(authenticated)/user/breaches/page.tsx
src/app/api/utils/auth.ts
src/app/api/v1/premium/route.ts

Jira: MNTOR-949
Adds/removes subscription button based on users current subscription status.
The current approach of checking the FxA token for `subscription` claims seems to work fine locally, but not on our dev server. The current approach also requires refreshing the token, where this does not.
This is the same set of steps to test as MNTOR-949, but with the added benefit that it does not require the user to log out/in again, and it should work on our dev/stage servers and not just locally.
1. Create new FxA user and log in to Monitor
2. Verify that "Subscribe to Premium" button appears on dashboard
3. Click "Subscribe to Premium" and subscribe
4. Verify that "Subscribe to Premium" button does *not* appear on dashboard

MNTOR-949/check subscriptions on dashboard

---

.env-dist
package-lock.json
package.json
src/scripts/syncBreaches.js

Jira: MNTOR-1838
Adding logo fetching to an existing cronjob (sync breaches). On top of updating the latest breaches from HIBP, the script will also fetch logos based on the breaches db and upload them to a public bucket in AWS S3.
The frontend will use the logo assets hosted on s3 instead of local assets
`http://s3.amazonaws.com/firefoxmonitor-dev-monitor-cdn-dev-static-website/`
`node src/scripts/syncBreaches.js`

MNTOR-1838: cronjob for breach logos

---

.lintstagedrc.js

To test this, I removed the newline at the end of `preview-head.html` and added that to this commit, and Prettier re-added it before committing.

Also apply Prettier to HTML files

---

package-lock.json
package.json
src/scripts/syncBreaches.js

This migration was done using
npx aws-sdk-js-codemod -t v2-to-v3
As listed on https://www.npmjs.com/package/aws-sdk:
> AWS SDK for JavaScript v3 is the latest and recommended version,
> which has been GA since December 2020.
The new version also modularises the different clients, hopefully
resulting in less frequent dependency updates that mostly do not
affect us.
I was not able to test this yet, since I don't have the credentials. This includes the `deleteFromS3` function - which I'm not sure we need long term, but it would be good to remove the 404 icons we've already stored on S3.

Update to AWS SDK v3, and don't store 404'd logos

---

.github/workflows/reference_linter.yaml

This ensures that common issues with `.ftl` files are also highlighted by CI when they are present in `pendingTranslations.ftl`. (The job still only runs when the file is edited, so I can't set it as a merge condition - I can make it run always if we prefer that.)

Also lint pendingTranslations in CI

---

.storybook/preview-head.html
.storybook/preview.tsx

This is especially useful for stories that demonstrate full pages. Individual stories can still override this by setting
parameters: { layout: "centered" }
or
parameters: { layout: "padded" }
on a per-story basis. See
https://storybook.js.org/docs/react/configure/story-layout.
Compare [the preview deployment](https://deploy-preview-3193--fx-monitor-storybook.netlify.app/iframe.html?args=&id=pages-dashboard--shell&viewMode=story) with [the one in `main`](https://fx-monitor-storybook.netlify.app/iframe.html?args=&id=pages-dashboard--shell&viewMode=story).

Make Storybook stories cover the full screen

---

src/app/api/v1/scan/route.ts
src/utils/breachLogo.js

Jira: MNTOR-1883
Figma: N/A
This partially reverts 3311fea; the UI still expects the API to send the HTML for each breach's icon, and even though that HTML is no longer generated from a logo map, it's still needed.
Enter an email address that has breaches (e.g. `test@mailinator.com`), and verify that the breaches are shown. ([Stage](https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/scan#email=test%40mailinator.com) currently shows an error because accessing `response.logos` throws.)

Restore serving logos in the free scan API

---

src/controllers/dockerflow.js

I noticed that https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/__version__ currently shows the fallback data:
https://github.com/mozilla/blurts-server/blob/dd9c4b3529bfe90058587ed8724af0b3e31aab21/src/controllers/dockerflow.js#L28-L32
Presumably, that's because it's not looking in the right location for the `version.json`.

Fix path to version.json

---

.storybook/preview.tsx
locales-pending/premium.ftl
src/app/(proper_react)/(onboarding)/user/welcome/Onboarding.test.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.stories.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.test.tsx
src/app/(proper_react)/redesign/MobileShell.tsx
src/app/functions/server/l10n.ts
src/app/functions/server/mockL10n.ts

Accessing next/headers in tests results in an error because it's not in a Server Component context, so calling our regular `getL10n()` functions from inside Storybook would result in test failures. Instead, I replaced that call with a function that just loads the English strings directly, rather than looking at request headers.
Note that there are also a couple of test changes - now that proper English strings are loaded, some of the tests would fail without accommodating that :)
I've set https://github.com/mozilla/blurts-server/pull/3209's branch as the target, because this also resolves what I mentioned there:
> Note that unfortunately, I wasn't able to re-use the Storybook story in the unit test

Unblock Storybook-in-tests with l10n

---

src/app/tokens.scss

This was triggered by @codemist [pointing out that](https://github.com/mozilla/blurts-server/pull/3190#discussion_r1254675445) I was setting a media query to tone a header down a notch, which we probably want to do everywhere we use a header - which could get repetitive. So this PR instead incorporates that into the tokens. I'm not sure if this will always align with the designs, but it feels like a relatively safe thing to do, in the sense that it's probably fine overriding the designs if they don't align with this PR.
It sets all font tokens to have a size that's dependent on the viewport size, as determined by `svw`. In other words, it's dependent on the size of the viewport when all browser UI (scrollbars, etc.) is visible.
The `clamp()` functions have three arguments. The third …

Scale all fonts down one notch on small screens

---

src/app/functions/server/onerep.ts
src/db/tables/onerep_scans.ts

When testing this feature with a new account, I noticed that it depends on the scan result being non-null (which will not be the case for users that haven't performed a scan yet).

fix: scan result may be empty

---

locales/en/data-classes.ftl

```sh
npx pdehaan/blurts-server-data-classes
Missing "clothing-sizes" data class from RobloxDeveloperConference breach
```
- https://monitor.firefox.com/breaches
- https://monitor.firefox.com/breach-details/RobloxDeveloperConference (which isn't currently displaying all data classes &mdash; see [MNTOR-1909](https://mozilla-hub.atlassian.net/jira/software/c/projects/MNTOR/issues/MNTOR-1909))
- https://haveibeenpwned.com/api/v3/breach/RobloxDeveloperConference
Jira: MNTOR-
Figma:

Add "clothing-sizes" to data-classes.ftl

---

locales-pending/premium.ftl
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.tsx
src/app/components/client/ExposureCard.module.scss
src/app/components/client/ExposureCard.tsx
src/app/components/client/ExposuresFilter.module.scss
src/app/components/client/ExposuresFilter.tsx
src/app/components/server/StatusPill.module.scss
src/app/tokens.scss

This PR includes several enhancements based on feedback from both technical and design discussions. The changes are as follows:
1) Placeholder Fallback Logo: Added a logo using the initial letter of the exposure name when an actual logo is unavailable.
2) Multi-Row Data Types: The breach exposure card can now support two or more rows of data types.
3) Instead of displaying '1 found,' we now show the user's email associated with the breach, providing better context for users.
After performing a scan, view these changes on `/redesign/user/dashboard`.

Fixup exposure cards UI

---

.env-dist
esbuild.js
sentry.client.config.ts
sentry.server.config.ts
src/app.js
src/app/api/v1/user/welcome-scan/progress/route.ts
src/appConstants.js
src/db/knexfile.js
src/middleware/error.js
src/middleware/noSearchEngineIndex.js
src/utils/dockerflow.js

Jira: MNTOR-1915
Use `NODE_ENV` and `APP_ENV` per https://nextjs.org/docs/messages/non-standard-node-env
Everything should function as before, but we should take extra care to test that Sentry handles this correctly.

MNTOR-1915 - use APP_ENV to differentiate environments per NextJS recommendation

---

.env-dist
src/app/(proper_react)/redesign/(authenticated)/user/welcome/FindExposures.tsx

NextJS special-cases `process.env.NODE_ENV` for front-end code, all other variables such as `APP_ENV` must use the `NEXT_PUBLIC_` prefix.
Scan (using polling method) should now work on Heroku.

fix: use NEXT_PUBLIC_ prefix for APP_ENV in front-end code

---

src/app/(proper_react)/redesign/(authenticated)/user/welcome/EnterInfo.tsx

Jira: MNTOR-2003
Fix: the confirmation screen for the date-of-birth in the free scan shows the previous day for me, it seems to be assuming UTC timezone. Passing "UTC" explicity to `toLocaleString()` seems to work.

MNTOR-2003 - fix: confirmation date-of-birth is off-by-one, set timezone explicitly

---

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/DashboardTopBanner.tsx

In commit af9ee12e94 the env var was replaced with a const exported by the onerep server function, but the dashboard hasn't switched over.

fix: use ONEREP_DATA_BROKER_COUNT const not env var

---

docs/test-coverage.md
jest.config.cjs
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/DashboardTopBanner.tsx
src/app/components/client/toolbar/UserMenu.tsx
src/app/components/server/Button.tsx
src/app/functions/client/gaEvent.ts
src/app/functions/server/getCountryCode.ts
src/app/functions/server/mockL10n.ts
src/app/hooks/useElementWidth.ts
src/contextProviders/localization.tsx

All future code that is inside a file that gets executed as part of a test, test coverage should be 100%. I have added exceptions for existing files under test that do not reach this threshold; ideally those exceptions get removed over time.
We will probably want to have a conversation about which code does not need unit tests; those can either be added to the `coveragePathIgnorePatterns` property in `jest.config.cjs` if those reasons apply to an entire file; otherwise, specific lines of code can be ignored using specific comments as described in https://github.com/istanbuljs/v8-to-istanbul/blob/fca5e6a9e6ef38a9cdc3a178d5a6cf9ef82e6cab/README.md#ignoring-uncovered-lines
I have already applied a couple of such comments to existing code. For example, `useElementWidth` heavily interacts with …

Up test coverage threshold for future code to 100%

---

.github/dependabot.yml

This should hopefully cut down on some of the noise of ESLint updates, and ensure that packages that break unless they are updated together are actually updated together.
See https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/

Group related Dependabot updates

---

jest.config.cjs
src/app/(nextjs_migration)/components/client/FalseDoorBanner.tsx
src/app/functions/server/featureFlags.ts

Jira: MNTOR-1834
A few small followups to the false door test:
- add GA - it's a little redundant but for completeness we'll fire the following events:
1. our existing `clicked_cta` event for CTAs
2. the automatic GA4 event for outbound clicks
3. a new `clicked_false_door` that shows whether the user clicked the outbound link or dismissed with X
I think (3) is the one we'll want to look at, (1) I included but it's a little odd because we don't have any other CTAs that behave like this (they are not dismiss-able). 
- after testing, I noticed that the flag is still not working correctly for anonymous (not authenticated) users, I corrected the flag code for this: if a `user` object is not passed then the allow list is not tested.

MNTOR-1834/add ga and anon flag

---

src/app/(nextjs_migration)/layout.tsx

Jira: MNTOR-1834
Filter by locale in addition to geo-location for false door test.
Test with primary locale not set to en-* and geo-location not in US.

fix: add locale filtering in addition to geo for false door test

---

jest.config.cjs
src/utils/subscriberBreaches.test.ts
src/utils/subscriberBreaches.ts

The primary change here is to change `resetMocks` and `resetModules` to `true`, to ensure each unit test can run independently. To do so, I did have to update the tests from https://github.com/mozilla/blurts-server/pull/3304 to define the mocks each specific test depended on inside that test, rather than in a `beforeAll` call that set them up in the precise order that the tests had to run in as well.
I wasn't entirely sure from the test descriptions what behaviour they were verifying, so I updated the descriptions to specify what I _though_ they did. Let me know if they're wrong.

Ensure tests can run in isolation

---

src/app/(nextjs_migration)/layout.tsx

This feature currently uses Fluent's `getLocale()` but that only happens to work when we have a localized version of the string (which we are reverting) - let's just look directly at the header.
Check using different preferred (i.e. set first in the list) `Accept-Language` header in your browser.

fix: adjust locale filtering, do not fall back to en

---

src/app/components/client/ExposuresFilter.tsx
src/app/components/client/ProgressCard.tsx

These warnings would show up in tests, and I think also in the browser console. In essence, the fix is that `triggerProps` returns an `onPress` property, which is an option for `useButton`, but can't be passed directly to a `<button>`. Thus, the fix is to use `useButton` for `<button>`s.

Fix warnings about unknown `onPress` attribute

---

src/app/api/v1/fxa-rp-events/route.ts

Jira: MNTOR-2103
This is a partial fix for MNTOR-2103, I think it will fix the immediate issue but the acceptance criteria also includes investigating:
1. if unit tests could've caught this
2. why it didn't show up in Sentry (just Heroku logs)
Heroku is currently throwing errors and not consuming the FxA queue, after we land this patch it should start working again.

MNTOR-2103 - pass subscriber ID correctly to getOnerepProfileId function

---

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.stories.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.test.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/DashboardTopBanner.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/page.tsx
src/app/components/client/Chart.tsx
src/app/components/client/stories/Chart.stories.ts

Jira: MNTOR-2119
Figma: N/A
The chart would prompt users who hadn't run a scan yet to start a free scan - even those who unfortunately cannot. This fixes that.
Set your language to something other than `en-US`, then visit the dashboard with a free user who has not run a scan yet. On `main`, you see the above prompt; in this branch, you shouldn't.

Do not prompt ineligible users to start a scan

---

jest.setup.ts
package-lock.json
package.json
src/app/components/client/toolbar/UserMenu.test.tsx
src/app/components/client/toolbar/UserMenu.tsx
src/app/functions/server/featureFlags.ts
src/cloud-functions/index.js

I'm not sure about this approach, but together with https://github.com/mozilla/blurts-server/pull/3340 and https://github.com/mozilla/blurts-server/pull/3341, this should ensure our console output when running tests is only related to code we're currently working on - happy to hear suggestions on other methods of achieving that.

Remove irrelevant warnings in tests

---

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/DashboardTopBanner.tsx
src/app/components/client/PremiumUpsellDialog.tsx
src/app/components/server/Button.tsx
src/app/components/server/stories/Button.stories.ts

If a button has a link target, it should always be a link, so no need for the caller to think about that explicitly.
One potential future improvement is to use an `<a>` if `href` doesn't start with `/`, but I'm not sure if we'll ever use `<Button>` for external links (maybe to FxA?).

Remove `buttonType` prop from <Button>

---

.circleci/config.yml

Glean requires python3 at build time, ensure that it is present for both Heroku and Docker builders.

Include python for Heroku and CircleCI builders

---

src/db/tables/onerep_profiles.ts
src/knex-tables.d.ts

This adds a type for the `onerep_profiles` table, based on https://github.com/mozilla/blurts-server/blob/main/src/db/migrations/20230703010356_add-onerep-profiles-table.js.

Add type for the onerep_profiles table

---

src/apiMocks/mockData.ts
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.tsx
src/app/components/client/ExposureCard.tsx
src/utils/parse.js
src/utils/subscriberBreaches.test.ts
src/utils/subscriberBreaches.ts

This aligns the SubscriberBreach type definition with the type of data that's actually being returned from the database.
Unfortunately, the data isn't always returned from the database; sometimes it's fetched from HIBP's API. Changing that to ensure it returns Date objects in that case as well is probably too risky, but for the relatively new getSubBreaches function, it's probably safe to normalise, as we can check all its call sites and make sure that they expect a Date object.

Dates on SubscriberBreach are Date objects

---

.circleci/config.yml

Figma: 
When re-landing a5fe8c87ca4bc5111698c7804c6d56530bad649f, I accidentally re-introduced some changes to the Circle CI config that are no longer needed after testing on https://github.com/mozilla/blurts-server/pull/new/debug-deploy-with-glean

MNTOR-2022 fixup: revert unneeded Circle CI config changes

---

src/apiMocks/mockData.ts
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.stories.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/FixView.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/ManualRemoveView.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/view-data-brokers/page.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/layout.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/page.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/subscribed/page.tsx
src/app/(proper_react)/redesign/(authenticated)/user/welcome/EnterInfo.tsx
src/app/api/v1/onerep-events/route.ts
src/app/api/v1/user/welcome-scan/progress/route.ts
src/app/api/v1/user/welcome-scan/result/route.ts
src/app/components/client/DataBrokerProfiles.tsx
src/app/components/client/ExposureCard.tsx
src/app/components/client/ExposureCardDataClass.tsx
src/app/functions/server/dashboard.ts
src/app/functions/server/onerep.ts
src/db/migrations/20230907143204_add_onerep_scanresults_table.js
src/db/tables/onerep_profiles.ts
src/db/tables/onerep_scans.ts
src/knex-tables.d.ts

As discussed on Slack, this removes the scan results column that contains a JSON blob from the `onerep_scans` table, and instead creates a new `onerep_scan_results` table that holds the results - this will enable us to allow the user to resolve individual scan results from a scan. In a followup PR, I'll extend that table to add a boolean `manually_resolved` column, and an API to toggle that.
Note: this builds on https://github.com/mozilla/blurts-server/pull/3367 and https://github.com/mozilla/blurts-server/pull/3373, so merging those first should allow shrinking this PR a bit.

Store scan results in a separate table

---

.npmrc
netlify.toml
package-lock.json
package.json

Dependabot was [logging the following error](https://github.com/mozilla/blurts-server/network/updates/723120103):
Dependabot uses Node.js v18.17.1 and NPM 9.6.5.
Due to the engine-strict setting, the update will not succeed.
Since we use Volta locally, and explicitly configure our Node versions elsewhere, I don't think engine-strict is necessary. And it would be good to get JS dependency updates again.
~~We might want to update our npm version to align with Dependabot though.~~ I added e3685adc0 to align our npm version with Dependabot - I expect that that's a relatively safe change, i.e. not as impactful as e.g. [changing our Node version](https://github.com/mozilla/blurts-server/pull/3295).

Unset engine-strict option

---

src/apiMocks/mockData.ts
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/subscribed/page.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/unsubscribed/page.tsx
src/app/api/v1/user/scan-result/[onerepScanResultId]/resolution/route.ts
src/app/api/v1/user/welcome-scan/create/route.ts
src/db/migrations/20230908154315_add_manual_resolution_column.js
src/db/tables/onerep_scans.ts
src/knex-tables.d.ts

Jira: MNTOR-2117
Figma: N/A
Note: this builds on https://github.com/mozilla/blurts-server/pull/3383.
This adds a boolean column `manually_resolved` to the table of scan results, and an API that allows the user to mark that as true.
The client doesn't properly call it yet, but you can replace the `letsFixItBtn` inside `<ScanResultCard>` with the following, and then click the "Let's fix it" button on broker cards:
```jsx
const letsFixItBtn = (
<span className={styles.fixItBtn}>
<Button variant={"primary"} onClick={(event) => {
event.preventDefault();
void fetch(
`/api/v1/user/scan-result/${props.scanResult.onerep_scan_result_id}/resolution`,
{
method: "POST",
credentials: "same-origin",
}
);
}}>{l10n.getString("exposure-card-cta")}</Button>
</span>
);
```

Add API to manually mark scan results as resolved

---

playwright.config.js

Enabling e2e tests for chrome and firefox thus reducing amount of manual effort for QA and getting closer to faster deployments
Jira: [MNTOR-2165](https://mozilla-hub.atlassian.net/browse/MNTOR-2165) and [MNTOR-2164](https://mozilla-hub.atlassian.net/browse/MNTOR-2164)
[MNTOR-2165]: https://mozilla-hub.atlassian.net/browse/MNTOR-2165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MNTOR-2164]: https://mozilla-hub.atlassian.net/browse/MNTOR-2164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

enabling e2e tests on both chrome and firefox

---

.env-dist

Change Nimbus sidecar URL default to match the default in infra, so it's more likely to work out-of-the-box.

chore: change nimbus sidecar URL default port to 8001

---

netlify.toml

The main way you'll currently notice the lack of env vars is in the Premium badge not being visible on Netlify, because PREMIUM_ENABLED is not true.
Which does bring up the question... Why do we even have this `PREMIUM_ENABLED` var in the first place?

Enable Premium features on Netlify

---

src/app/functions/server/getExperiments.ts

The Cirrus container requires `Content-Type: application/json` (or it returns HTTP 422), and additionally `context` may not be empty.
I ran the Cirrus container in https://github.com/mozilla/experimenter/ locally, but I think we can just deploy to stage and test it there at this point.

MNTOR-2022/add content type header for cirrus

---

.env-dist
src/app/functions/server/dashboard.ts
src/scripts/emailBreachAlerts.js

Jira: MNTOR-2120
The email breach alert worker is taking a little over a minute to process 1k no-op jobs (they are valid breaches, but in the spam category and not eligible for sending email). I'd like to try bumping up the max number of messages the workers process from 1k to 10k.
Once we are able to measure how long it takes when there are actual emails to construct and send, we could consider upping the frequency (it runs once per hour right now), at the current rate it won't process the current backlog before it expires so we should do this before Thursday Sept 28 (and/or increase the retention period).

bump max email worker jobs to 10k, split out to env var

---

src/app/(nextjs_migration)/(guest)/breach-details/[breachName]/page.tsx
src/app/(nextjs_migration)/(guest)/breaches/page.tsx
src/app/(nextjs_migration)/layout.tsx
src/app/(proper_react)/layout.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.stories.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/high-risk-data-breaches/HighRiskBreachLayout.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/high-risk-data-breaches/[type]/page.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/high-risk-data-breaches/highRiskBreachData.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/high-risk-data-breaches/page.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/leaked-passwords/LeakedPasswordsLayout.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/leaked-passwords/[type]/page.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/security-recommendations/SecurityRecommendationsLayout.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/security-recommendations/[type]/page.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/page.tsx
src/app/(proper_react)/redesign/(authenticated)/user/welcome/EnterInfo.tsx
src/app/functions/server/l10n.ts
src/app/functions/universal/getLocale.test.ts
src/app/functions/universal/getLocale.ts
src/app/layout.tsx

As called out in https://github.com/mozilla/blurts-server/pull/3427#issuecomment-1729707101, we hardcoded `en-US` here, rather than relying on the user's locale. d500cfac7b72e192480233ea85ca758463faa50d makes that dependent on the user's locale - the main downside is that that locale might not match the language of the website, since this part of the website is forced in English.
This PR also includes 4721768add9bcbfcde33ee3289040f1edab3fd89, which allows calling `getLocale` in client components - but does now require passing in the `l10n` instance.

Format date according to a user's locale

---

.storybook/preview.tsx
jest.config.cjs
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/view-data-brokers/View.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/view-data-brokers/ViewDataBrokers.stories.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/view-data-brokers/page.tsx

This adds a Storybook story for the scan results step in the guided resolution flow. Note that all the other steps don't have a story yet, and this is the second step in the flow (assuming all of them apply), so I named it "2." - but this one is relevant to my upcoming work, so I've focused on just this one for now.
https://deploy-preview-3464--fx-monitor-storybook.netlify.app/?path=/story/pages-guided-resolution-2-scan-results--none-free

Add Storybook story for Scan Results step

---

.storybook/preview.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/01c.ManualRemove.stories.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/ManualRemoveView.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/page.tsx

This moves all the async data fetching from `ManualRemoveView.tsx` into the `page.tsx`, making the former just render data that it gets passed as props. That can then also be used as a story.
Note that this builds on https://github.com/mozilla/blurts-server/pull/3464.

Add story for the manual broker resolution view

---

src/app/(proper_react)/redesign/GaScript.tsx

When server-rendering, `navigator` is not defined - but by comparing that variable directly with `undefined`, we're still referring to it and thus still triggering an error message. Passing it into `typeof` avoids that.

Avoid error about undefined `navigator`

---

src/app/api/utils/auth.ts
src/next-auth.d.ts

This is re: https://github.com/mozilla/blurts-server/pull/3486#discussion_r1345652068
I think they represent what they should know. This also separates out the FxA OAuth config from the Next-Auth user session management config, which should hopefully also help with the mental model.
So we now have `Profile`, which represents the shape of the data as returned by FxA's `/userinfo/` endpoint. Then we have the `User`, representing the user object we give to Next-Auth.

Fix Next-Auth types

---

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/FixView.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/ManualRemove.stories.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/ManualRemoveView.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/page.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/start-free-scan/page.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/high-risk-data-breaches/[type]/page.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/high-risk-data-breaches/highRiskBreachData.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/getUserDashboardState.tsx
src/app/functions/server/getRelevantGuidedSteps.ts

This also involved merging the scan steps into a single one, since we don't want the "Skip" button on the scan step to skip to the scan results step.
I also fixed some numbers that were hardcoded to 0, and the link to the credit card breach resolution.
Jira: MNTOR-2116
Figma: N/A
This makes the "Skip for now" link on the manual broker resolution page work.
Visit http://localhost:6060/redesign/user/dashboard/fix/data-broker-profiles/manual-remove, then click "Skip for now".

Make scan resolution skip link work

---

locales-pending/premium.ftl
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.tsx

Figma: [Dashboard permutations](https://www.figma.com/file/pb1X1JlHT3ZMmFf2rKKRu1/Permutations?type=whiteboard&node-id=41-9169&t=IAvbvLZoTkl0RYgl-0)
Only show the free scan CTA for the dashboard zero state to eligible users. This also fixes the link tags within the string which did not show.

Only show the free scan CTA for users that are eligible for one

---

README.md
locales-pending/premium.ftl
locales/en/app.ftl
locales/en/settings.ftl
src/app/(nextjs_migration)/(authenticated)/user/layout.tsx
src/app/(nextjs_migration)/(authenticated)/user/settings/page.tsx
src/app/(nextjs_migration)/components/client/UserMenu.tsx
src/app/api/utils/auth.ts
src/app/components/client/toolbar/UserMenu.test.tsx
src/db/tables/featureFlags.ts
src/e2e/specs/breachResolution.spec.ts

Builds on https://github.com/mozilla/blurts-server/pull/3525.
Hidden behind the "FxaRebrand" flag so we can roll it out across different products at the same time.
Jira: MNTOR-1852
Figma: N/A
Visit the settings page, and the old and new user menu. If you have enabled the flat `FxaRebrand`, you should only see "Mozilla account" and "Mozilla settings". If the flag is off, it should be "Firefox account" / "Firefox settings".

Change Firefox Accounts to Mozilla Accounts

---

src/app/functions/server/logging.ts

I think this should resolve the issue of https://github.com/mozilla/blurts-server/pull/3646 without needing a revert.
Without this change, we see the following error on staging:
TypeError: Cannot set property transports of #<Logger> which has only a getter
at 40066 (/app/.next/server/chunks/1701.js:1:352)
at __webpack_require__ (/app/.next/server/webpack-runtime.js:1:161)
at 5183 (/app/.next/server/chunks/5183.js:1:139)
at __webpack_require__ (/app/.next/server/webpack-runtime.js:1:161)
at 4205 (/app/.next/server/chunks/5127.js:1:1956)
at Function.__webpack_require__ (/app/.next/server/webpack-runtime.js:1:161)
at runNextTicks (node:internal/process/task_queues:60:5)
at listOnTimeout (node:internal/timers:540:9)
at process.processTimers (node:internal/timers:514:7)
at async eq …

Do not assign to read-only property

---

src/db/tables/onerep_scans.ts

Jira: MNTOR-2385
Discovered during spike for https://mozilla-hub.atlassian.net/browse/MNTOR-1431 - we need to be logging this info at the level of each broker so we can see how long removals take.

MNTOR-2385 - add more logging for onerep scans

---

src/app/functions/server/logging.ts

Jira: MNTOR-2401
There appears to be a permission issue in staging with creating structured logs, fall back to console logging for now.
Leave it on for `APP_ENV=gcpdev` so we can debug in a sandbox.

MNTOR-2401 - disable structured logging in stage/prod for debugging

---

src/app/functions/server/logging.ts
src/db/tables/onerep_scans.ts

Jira: MNTOR-2385
While testing as part of the spike for MNTOR-2385, I noticed that we're collecting more scan data than we should. We only need the IDs and the status.

MNTOR-2385/only log scan metadata

---

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/getUserDashboardState.tsx

Jira: MNTOR-2423
Add debugging (Sentry) for client-side `InvalidUserState` failure on dashboard (which shouldn't happen, but is for some existing accounts on production).

MNTOR-2423 - add Sentry captureMessage to debug cause of InvalidUserState on dashboard

---

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.test.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/getUserDashboardState.tsx

Jira: MNTOR-2423
~~Sentry's captureMessage has a length limit, move logging to server - I didn't do this initially because this function appears to be both used by client and server code, so I am guarding against server code by putting the import and function call to the server logger behind a check for the `window` global.~~ EDIT: storybook-build is having trouble with this, instead of worrying about it we can just use `console.error` for now, which will work in both GCP (as a stdout textPayload) or client contexts.

MNTOR-2423 - captureMessage has a length limit, move logging to server

---

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.tsx
src/app/components/client/Chart.tsx

Jira: [MNTOR-2402](https://mozilla-hub.atlassian.net/browse/MNTOR-2402)
Direct returning users to the shortened version of the welcome onboarding
Example Storybook user state: [US user, without Premium, without scan, with 0 breaches](https://deploy-preview-3661--fx-monitor-storybook.netlify.app/?path=/story/pages-dashboard--dashboard-us-no-premium-no-scan-no-breaches)
[MNTOR-2402]: https://mozilla-hub.atlassian.net/browse/MNTOR-2402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Direct returning users to the shortened version of the welcome onboarding

---

src/db/tables/onerep_scans.ts

Jira: MNTOR-2385
A previous patch attempted to use `.forEach()` on an array-of-objects to exclude PII for logging purposes, but it should have used `.map()` instead.

MNTOR-2385 - use map not foreach to re-map scan results for logging

---

src/scripts/syncBreaches.js

Jira: MNTOR-2421
Taking out unnecessary step to cache logos locally on disk in `tmp`
The step adds more time/complexity to the script where the actual s3 step is append-only anyways, making it impossible to delete existing logos

MNTOR-2421 - taking out unnecessary step to store locally

---

src/db/tables/onerep_scans.ts

Jira: Possibly causing [MNTOR-2426](https://mozilla-hub.atlassian.net/browse/MNTOR-2426).
Inserting an empty results array into the table `onerep_scan_results` results in the following error:
```
Error: The query is empty
```
This might prevent the scans `onerep_scan_status` from `in_progress` to `finished`.
[MNTOR-2426]: https://mozilla-hub.atlassian.net/browse/MNTOR-2426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Do not insert empty scan results

---

src/app/api/v1/onerep-events/route.ts
src/app/api/v1/user/welcome-scan/create/route.ts
src/app/api/v1/user/welcome-scan/progress/route.ts
src/app/functions/server/refreshStoredScanResults.ts
src/db/migrations/20231102024624_add_unique_index_to_scan_results_id.js
src/db/tables/onerep_scans.ts

Jira: MNTOR-2444
More detail in https://mozilla-hub.atlassian.net/browse/MNTOR-2444?focusedCommentId=789660 - the short version is that we were not handling new scan IDs correctly, *and* scan results are not attached to scan IDs in the way we thought they would be.
I tried to simplify and reuse the logic in `refreshStoredScanResults` while I was at it.
This is unfortunately very difficult to test, as it relies on the behavior of the production scan service, and requires subscribing (which can't be undone). However, I believe it should fix the existing accounts that are stuck with fewer results than they should be showing (one of these is mine).
We don't really have automated testing around this behavior (outside of mocks), but I'll see if I can add it.

MNTOR-2444 - handle scan results updates correctly

---

src/db/migrations/20231102024624_add_unique_index_to_scan_results_id.js
src/db/tables/onerep_scans.ts

This migration failed on staging because there are duplicate rows already in the `onrep_scan_results` table - this is probably a result of our early tests. This adds a raw `DELETE` query that generically keeps the latest row if there are any duplicates (using `ctid` which is Postgres-specific). It doesn't require any parameters.

Delete duplicate rows from onerep scan results

---

locales/en/app.ftl
locales/en/settings.ftl
src/app/(nextjs_migration)/(authenticated)/user/settings/page.tsx
src/app/(nextjs_migration)/components/client/UserMenu.tsx
src/db/tables/featureFlags.ts

Jira: MNTOR-2304
Figma: N/A
The `FxaRebrand` feature flag has now been enabled successfully, so we can make that change permanent and always use "Mozilla accounts" everywhere.
Nothing should have changed compared to `main` if you've enabled the `FxaRebrand` flag.

Make the Firefox Accounts rebrand permanent

---

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/welcome-to-premium/WelcomeToPremiumView.tsx
src/app/(proper_react)/redesign/Shell.tsx
src/app/components/client/PremiumBadge.tsx

Jira: [MNTOR-2396](https://mozilla-hub.atlassian.net/browse/MNTOR-2396)
Removes the redundant session update from `PremiumBadge` and moves the session update to `Shell` to get the latest subscription status. This ensures that we check the status more consistently and remove the duplicate check from `PremiumBadge`: It is being rendered twice — once in [Toolbar](https://github.com/mozilla/blurts-server/blob/premium-button-remove-session-update/src/app/components/client/toolbar/Toolbar.tsx#L27) and also in [MobileShell](https://github.com/mozilla/blurts-server/blob/premium-button-remove-session-update/src/app/(proper_react)/redesign/MobileShell.tsx#L106).
[MNTOR-2396]: https://mozilla-hub.atlassian.net/browse/MNTOR-2396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …

Remove session update from PremiumButton

---

src/app/components/client/toolbar/Toolbar.tsx

We are using Toolbar as a client component and have to explicitly make a client component since we are using useL10n.

Fix: Mark Toolbar as client component

---

src/app/api/v1/hibp/notify/route.ts
src/db/tables/email_notifications.js
src/scripts/emailBreachAlerts.js

Jira: MNTOR-2281
This adds a few optimizations around email breach alert processing:
1. check to see a breach is actionable breach before queuing
2. move reading breach data out of loop in worker
One thing I'm a little concerned about with (1) is that we've tried to avoid having dependencies on anything except Pub/Sub being up, and this adds a scan of the breach table. We might want to use Redis here.

MNTOR-2281/optimize email breaches

---

src/app/functions/server/getRelevantGuidedSteps.test.ts
src/app/functions/server/getRelevantGuidedSteps.ts

As @codemist rightly pointed out in https://github.com/mozilla/blurts-server/pull/3641#discussion_r1368825125, the `getNextGuidedStep()` function was not covered by unit tests. This PR adds a bunch that should cover the cases that are most likely to break, I think - but happy to take suggestions for more to add.

Add tests for getNextGuidedStep()

---

package-lock.json
package.json

Since PR #3266 we do not use `ts-node` as a dependency.

Remove unused dependency ts-node

---

src/scripts/emailBreachAlerts.js

We're trying to diagnose whether the script is hanging in stage/prod or not, I noticed that the Sentry check-in comes after tearing down Postgres connections. We should have it be the very last thing the script does instead, this will allow Sentry to alert us to hanging cron jobs.

emailBreachAlerts: Move sentry cron check-in to end of finally block

---

public/nextjs_migration/client/js/analytics.js

Jira: MNTOR-2143
We're not seeing outbound clicks to `mozilla.org` in GA4, I'm suspecting that we're overriding these with our `click` handler for elements that have `cta_id` data properties.
I think we probably need to be including the page location with `clicked_cta` events anyway, so this would be a "good enough" fix for the problem of being able to count CTA clicks to `mozilla.org`.

MNTOR-2143 send page_location with cta_id

---

src/app/components/client/DataBrokerProfiles.module.scss
src/app/components/client/DataBrokerProfiles.tsx

Jira: [MNTOR-2440](https://mozilla-hub.atlassian.net/browse/MNTOR-2440): "View your profile" links in guided flow and on the dashboard don't open in a new tab
Adds an icon for outgoing links and add target `_blank` to the “View your profile” links.
1. Visit `/redesign/user/dashboard/fix/data-broker-profiles/view-data-brokers`.
2. The “View your profile” links should have icon beside them and open in a new tab or window.
[MNTOR-2440]: https://mozilla-hub.atlassian.net/browse/MNTOR-2440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Open view profile link in a blank target

---

package-lock.json
package.json
src/app/(proper_react)/redesign/(authenticated)/user/welcome/EnterInfo.tsx
src/app/(proper_react)/redesign/(authenticated)/user/welcome/Onboarding.test.tsx
src/app/components/client/ComboBox.tsx
src/app/components/client/InputField.tsx
src/app/components/client/ListBox.tsx
src/app/components/client/LocationAutocompleteInput.tsx
src/app/components/client/TabList.tsx
src/app/hooks/__mocks__/locationSuggestions.ts
src/app/hooks/locationSuggestions.ts

This PR does two things:
1. Revert https://github.com/mozilla/blurts-server/pull/3785 to re-apply the React Aria upgrade
2. Fix the modifications I made to make `<LocationAutocompleteInput>` compatible with the new version, and add a unit test verifying it.
For #2, the main change here is to leave the async loading of the location
data to `useAsyncList`, as described in the react-aria docs:
https://react-spectrum.adobe.com/react-aria/useComboBox.html#asynchronous-loading
I think the root issue, however, was the ComboBox being a
controlled component, w.r.t. its selection, and the selection
value being set to the state variable instead of the value passed
to the `handleOnSelectionChange` handler, and thus being one render
behind. I've now changed it to both be an uncontrolled component,
and …

Re-apply React-Aria upgrade, updating <LocationAutocompleteInput>

---

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/welcome-to-premium/WelcomeToPremiumView.tsx

Jira: [MNTOR-2025: Update Welcome to Premium Card to re-enable the CTA](https://mozilla-hub.atlassian.net/browse/MNTOR-2025)
Re-enable the welcome to premium CTA that was disabled for the first round of FF.
1. Visit `/redesign/user/dashboard/fix/data-broker-profiles/welcome-to-premium`.
2. The “Let’s keep going” button should be enabled again.

Re-enable welcome to premium CTA

---

src/db/tables/subscribers.js
src/utils/fxa.js

Jira: MNTOR-1932
Updating session token revoke URI to use the new FxA endpoint
In Heroku, go to settings and update your password. Check logs in heroku to make sure there's no 400 or 500 errors

MNTOR-1932: update destroy oauth token fxa API

---

.eslintrc.json
locales-pending/landing-premium.ftl
locales/en/app.ftl
src/app/(proper_react)/redesign/(public)/LandingView.module.scss
src/app/(proper_react)/redesign/(public)/LandingView.test.tsx
src/app/(proper_react)/redesign/(public)/LandingView.tsx
src/app/(proper_react)/redesign/(public)/PlansTable.module.scss
src/app/(proper_react)/redesign/(public)/PlansTable.tsx
src/app/components/client/BillingPeriod.module.scss
src/app/components/client/BillingPeriod.tsx
src/app/components/server/VisuallyHidden.module.scss
src/app/components/server/VisuallyHidden.tsx
src/app/components/server/button.module.scss

Jira: MNTOR-2471
Figma: https://www.figma.com/file/YqpVpUbSTzZMj9Jbp2po8Q/Mozilla-Monitor-Premium-LP?type=design&node-id=1942-21098&mode=dev
This adds the plans comparison table.
Version for smaller screens will be added later.
Make sure the tooltips open, the pricing toggle changes what's shown and where the buttons go to, and that it's accessible.

Add plans to the landing page on wide screens

---

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/high-risk-data-breaches/HighRiskBreachLayout.tsx

Jira: [MNTOR-2620](https://mozilla-hub.atlassian.net/browse/MNTOR-2620): “Continue” button from the no high-risk data breaches found screen does not work
Fixes the “Continue” button on the high-risk data breaches step in the guided resolution.
[MNTOR-2620]: https://mozilla-hub.atlassian.net/browse/MNTOR-2620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Continue button on high-risk resolution step

---

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/DashboardTopBanner/DashboardTopBannerContent.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/DashboardTopBanner/index.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/ResolutionContainer.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/ManualRemove.test.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/ManualRemoveView.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/manual-remove/RemovalCard.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/welcome-to-premium/WelcomeToPremiumView.tsx
src/app/components/client/Chart.tsx
src/app/functions/server/dashboard.test.ts
src/app/functions/server/dashboard.ts

Jira: MNTOR-2268
Figma: N/A
This PR does _three_ things. The most important thing is that manual resolutions are now subtracted from the count of the "Action needed" dashboard: 1a58a4e8daac0c27bbae6c31e3329f701ac63fa4.
That is the part that fixes the issue. Most of the code changes, however, are renames (b0caf54218fe1545d09b638323b226dd8de00d41) and a small bit of refactoring (d1c0498b1e8f8805edd52d60cb843d8d8485f79c). I had to do those to be able to understand what was going on and how to fix it. The main thing with big impact is that I renamed `exposure` in `dashboard.ts` to `dataPoint`, because we already used "exposure" to mean "broker scan result or data breach" elsewhere in the code, and I kept getting confused. **I would recommend filtering the review by commits** to ease review. …

Don't count manual resolves as unresolved

---

src/app/functions/server/dashboard.test.ts
src/app/functions/server/dashboard.ts

Jira: [MNTOR-2622](https://mozilla-hub.atlassian.net/browse/MNTOR-2622)
Individual fixed breach data classes were only counted if a breach had been resolved entirely. Instead, we should increase the summary for breach classes as soon as the affected class is resolved.
[MNTOR-2622]: https://mozilla-hub.atlassian.net/browse/MNTOR-2622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Count fixed breach data classes not only for resolved breaches

---

src/app/(proper_react)/redesign/(public)/PlansTable.module.scss
src/app/(proper_react)/redesign/(public)/PlansTable.tsx

This makes the `?` icon not drop to a new line on Tony's device, but also in general gives the text some more room on smaller screens.

Decrease padding in plan cards

---

src/app/(proper_react)/redesign/Shell.tsx

Jira: [MNTOR-2436](https://mozilla-hub.atlassian.net/browse/MNTOR-2436): Redesigned Monitor logo button redirects to the landing page instead of the dashboard
[MNTOR-2436]: https://mozilla-hub.atlassian.net/browse/MNTOR-2436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adjust redesign Monitor logo link target

---

locales-pending/premium.ftl

Jira: MNTOR-
Figma: 
Didn't see any other obvious results using this cursed <kbd>grep</kbd>:
```sh
git grep -Pn "asso[^c]" -- ":(exclude)locationAutocompleteData.json" ":(exclude)locales/*/*.ftl"
```

fix 'associated' typo

---

.github/workflows/e2e_cron.yml
.github/workflows/e2e_pr.yml
.github/workflows/unittests.yaml
Dockerfile
netlify.toml
package.json

Something changed in how V8 measures coverage, it seems, because running the tests in Node 20.10 results in <100% coverage. Among the uncovered lines are some inside of `getLocale`, although running specifically the `getLocale` tests results in full coverage.
We didn't catch this in CI because CI didn't use the same Node version as we do locally. This aligns CI and local versions, but due to the above problem, on Node 20.9. Once we figure out the actual issue, we can merge https://github.com/mozilla/blurts-server/pull/3869.

Align on Node 20.9 everywhere

---

locales/en/data-classes.ftl
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.test.tsx
src/app/components/client/Chart.tsx

Jira: [MNTOR-2502](https://mozilla-hub.atlassian.net/browse/MNTOR-2502)
In #3870 we removed the in-progress exposures from the count of fixed items, but they were still included in the chart subtext on the Dashboard.
[MNTOR-2502]: https://mozilla-hub.atlassian.net/browse/MNTOR-2502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Don’t include in-progress exposures in dashboard chart subtext

---

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/welcome-to-premium/WelcomeToPremiumView.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/welcome-to-premium/page.tsx

Although it runs as a server component in production, we also want to render it in Storybook, which runs everything as a client component.
This should make Netlify succeed again.

Keep the ManualRemove View universal

---

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/welcome-to-premium/WelcomeToPremiumView.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/fix/data-broker-profiles/welcome-to-premium/page.tsx
src/app/functions/server/getPremiumSubscriptionUrl.ts

Otherwise the landing page stories break: https://fx-monitor-storybook.netlify.app/?path=/story/pages-public-landing-page--landing-us

Allow running getPremiumSubscriptionUrl in stories

---

src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.test.tsx
src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.tsx
src/app/functions/server/dashboard.ts

Jira: MNTOR-2632
Figma: N/A
The dashboard overview (the paragraph before the cards) did not incorporate manually-resolved scan results.
Manually resolve a scan result, and verify that it is subtracted from the text:
> We found your information exposed `x` times over ⁨198⁩ data breaches and ⁨`y` data broker sites that are selling your personal info.

Also subtract manually resolved brokers

---

docs/analytics.md

The repo isn't really the right place to inform end users, and the doc was outdated anyway, so I just repurposed `analytics.md` for developer-focused documentation.

Add dev docs on debugging Glean

---

src/app/functions/server/l10n.ts

This means we won't localise the UI to locales that aren't listed in SUPPORTED_LOCALES. This avoids showing languages with only a few localised strings.
I'm not sure if we decided not to use this for now, but it was so easy to implement that I figured I'd just submit a PR and we'd see.

Respect the SUPPORTED_LOCALES env var

---

.storybook/preview.tsx
src/TestComponentWrapper.tsx
src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/Dashboard.stories.tsx
src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/automatic-remove/AutomaticRemove.stories.tsx
src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/manual-remove/ManualRemove.stories.tsx
src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/start-free-scan/StartFreeScan.stories.tsx
src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/view-data-brokers/ViewDataBrokers.stories.tsx
src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-premium/WelcomeToPremium.stories.tsx
src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/[type]/HighRiskDataBreach.stories.tsx
src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/[type]/LeakedPasswords.stories.tsx
src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/[type]/SecurityRecommendations.stories.tsx
src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/SettingsPage.test.tsx
src/app/(proper_react)/redesign/(public)/LandingView.stories.tsx
src/app/functions/server/__mocks__/l10n.ts
src/app/functions/server/mockL10n.ts

@flodolo With this change, you'll be able to add `&locale=<chosen locale>` to the Storybook URL to load that locale's strings - [example](https://deploy-preview-3972--fx-monitor-storybook.netlify.app/?path=/story/pages-public-landing-page--landing-non-us&locale=cs). Non-submitted English strings will also be loaded.

Allow loading Storybook in other locales

---

package-lock.json
package.json

It was added to the top-level package.json in 3c50bc2 as part of the pre-Next.js/pre-Jest test infrastructure, and is no longer needed. (This will be proven if CI succeeds on this PR :P )

Remove direct c8 dependency

---

src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/view-data-brokers/View.tsx
src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/view-data-brokers/ViewDataBrokers.stories.tsx
src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/view-data-brokers/page.tsx

Storybook renders universal components as client components, so even if they're rendered as server components on the actual website, they shouldn't call server-side APIs like `getL10n` if we can avoid it.
See this broken story on `main`: https://fx-monitor-storybook.netlify.app/?path=/story/pages-guided-resolution-1b-scan-results--none-free
That same story for this PR: https://deploy-preview-3992--fx-monitor-storybook.netlify.app/?path=/story/pages-guided-resolution-1b-scan-results--none-free

Fix Guided Resolution step 1b. in Storybook

---

src/app/api/v1/fxa-rp-events/route.ts

Jira: MNTOR-2627
Don't send fxa user id to sentry. We'd want to capture in gcp logs though

MNTOR-2627: don't send fxa user id to sentry

---

.env-dist
src/app/(nextjs_migration)/(authenticated)/user/breaches/page.tsx
src/app/(nextjs_migration)/(authenticated)/user/settings/page.tsx
src/app/(nextjs_migration)/components/server/AddEmailDialog.tsx
src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/DashboardTopBanner/DashboardTopBannerContent.tsx
src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/View.tsx
src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/automatic-remove/AutomaticRemoveView.tsx
src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/start-free-scan/StartFreeScanView.tsx
src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/view-data-brokers/AboutBrokersIcon.tsx
src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/EmailAddressAdder.tsx
src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/View.tsx
src/app/(proper_react)/redesign/(authenticated)/user/(dashboard)/settings/actions.ts
src/app/(proper_react)/redesign/(authenticated)/user/welcome/[[...slug]]/page.tsx
src/app/(proper_react)/redesign/(public)/Faq.tsx
src/app/(proper_react)/redesign/(public)/PlansTable.tsx
src/app/(proper_react)/redesign/(public)/ScanLimit.tsx
src/app/(proper_react)/redesign/Footer.tsx
src/app/(proper_react)/redesign/GaScript.tsx
src/app/api/v1/user/email/route.ts
src/app/components/client/Chart.tsx
src/app/components/client/ExposuresFilterExplainer.tsx
src/app/components/client/SubscriberWaitlistDialog.tsx
src/app/components/client/UpsellDialog.tsx
src/app/components/client/toolbar/UserMenu.tsx
src/app/hooks/useGa.ts
src/app/layout.tsx
src/constants.ts

We used NEXT_PUBLIC_* env vars for values that:
- were the same across environments, and
- we wanted to easily change.
In other words, they were essentially constants. By turning them into regular, statically-analysable, JS variables, they:
- can easily be renamed,
- are known to be defined and thus don't need non-null or type assertions, and
- can have non-string values, removing the need to e.g. parse integers,
- are more explicitly the same in every environment, avoiding the temptation to attempt (and fail) to set environment-specific env vars to override them.
We'll also no longer have to tell people to copy the values over to their personal `.env` files.

Remove NEXT_PUBLIC env vars by constants

---

src/app/(nextjs_migration)/(authenticated)/user/layout.tsx
src/app/(nextjs_migration)/(guest)/layout.tsx
src/app/(nextjs_migration)/components/client/PageLoadEvent.tsx
src/app/(proper_react)/layout.tsx
src/app/components/client/PageLoadEvent.tsx
src/app/functions/server/getUserId.tsx

Jira: MNTOR-2335
Figma: N/A
This fixes the `<PageLoadEvent>` component to actually track the path of the current page (@rhelmer unless I made a big oversight and it was tracked in a way I did not understand), and adds it to the new pages as well.
I added a log statement [here](https://github.com/mozilla/blurts-server/blob/a039d08f5356b7fa2ee25182a87141d3af6a7dfe/src/app/components/client/PageLoadEvent.tsx#L50) to verify what was logged. But I assume the Glean realtime viewer should also work, if you remember where that was :sweat_smile:

Count page views on the new site

---

src/app/api/v1/fxa-rp-events/route.ts

Jira: MNTOR-2711
When testing on staging, I encountered a situation where the subscription webhook came through but OneRep activation failed. In this case our webhook handler returns an HTTP error so FxA retries, but the badge doesn't show up right away. 
We should update our database first.
I ran into this on stage, this can be tested by pointing the `ONEREP_API_BASE` var to an endpoint that always returns `500`.

MNTOR-2711 - update database from subscription webhook before onerep

---

.github/workflows/e2e_cron.yml
.github/workflows/e2e_pr.yml

That way, it can start up the server without errors.

Pass OneRep sandbox API key to end-to-end tests

---

src/e2e/pages/authPage.ts

It appears that the IDs on the FxA sign-up page have been removed? Ideally I'd use `getByLabel` and `getByRole` to select on markup that matches what users are looking for, but it looks like these selectors are used on different pages (sign in vs. sign up), and thus the labels differ even though the elements are similar. So for now, I've updated the selectors to ones that appear to work for the different pages (even now that some IDs appear to have disappeared), but ideally, we'd have selectors specific to each page, based on user-visible selection characteristics.

Somewhat more resilient selectors for auth page

---

src/e2e/global-setup.ts

It used to be that, even if headless mode was disabled, the setup would still run in headless mode, which can be confusing. This change ensures that the setup is also run in headed mode, if the tests itself are too.

Make setup headed when any browser is

---

src/app/(proper_react)/(redesign)/(public)/LandingView.stories.tsx
src/app/(proper_react)/(redesign)/(public)/LandingView.test.tsx
src/app/(proper_react)/(redesign)/(public)/LandingView.tsx
src/app/(proper_react)/(redesign)/(public)/RebrandAnnouncement.module.scss
src/app/(proper_react)/(redesign)/(public)/RebrandAnnouncement.tsx
src/app/(proper_react)/(redesign)/(public)/page.tsx
src/app/hooks/useHasRenderedClientSide.tsx
src/app/hooks/useLocalDismissal.test.tsx
src/app/hooks/useLocalDismissal.ts
src/db/tables/featureFlags.ts

Jira: MNTOR-2522
Figma: https://www.figma.com/file/51jgudmkBoMMU9twT7UOKB/Monitor-Plus-Launch?type=design&node-id=310-6816&mode=design&t=PAVHr1PiURqF4TxK-0
(Based on https://github.com/mozilla/blurts-server/pull/4033 to avoid adding this to the wrong directory.)
First, enabled the `RebrandAnnouncement` feature flag.
Open the landing page. You should see the announcement. After you click the X, it should go away, and stay away after a refresh.

Add banner announcing "Mozilla Monitor" rebrand

---

.circleci/config.yml
.github/workflows/build.yaml

This should speed up our CI pipelines, work more towards consolidating on GitHub Actions, and minimise the RAM usage of a single CI job.
The trigger for this PR was https://github.com/mozilla/blurts-server/pull/4060#issuecomment-1904453505. This isn't a true solution - it seems like it's a bit much to use 4GB RAM in the build :unamused: But regardless, this is probably a good idea, and might unblock us for the moment.

Split build step into separate CI job

---

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/HighRiskBreachLayout.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/LeakedPasswordsLayout.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/SecurityRecommendationsLayout.tsx

Jira: MNTOR-2464
Figma: 
This essentially applies the same thing [we already did for data brokers](https://github.com/mozilla/blurts-server/blob/6ce3bcdb02e4e8cf4bf235898699deb58f78eae3/src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/manual-remove/RemovalCard.tsx#L39-L42) for data breaches: after we resolve them, we make sure that the next render of the dashboard fetches fresh data. Otherwise, fixed breaches will still be listed under the "active" tab.
Open the resolution flow and move to the first breach. Go back to the dashboard and check what data is breached, and then resolve those in the guided flow. With this branch, when you end up at the dashboard at the end, the breach should be moved to the "Fixed" tab, whereas on `main`, it …

Refresh breaches after resolving some

---

src/app/(proper_react)/(redesign)/(authenticated)/user/welcome/[[...slug]]/page.tsx

Jira: [MNTOR-2613](https://mozilla-hub.atlassian.net/browse/MNTOR-2613)
Redirect to the dashboard instead of throwing an application error if a user is not eligible for a free scan.
1. Navigate to `/user/welcome` as a user who is not eligible for a free scan.
2. Instead of an application error you should be redirected to `/user/dashboard`.
[MNTOR-2613]: https://mozilla-hub.atlassian.net/browse/MNTOR-2613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Subscriber not eligible for free scan redirect (MNTOR-2613)

---

src/db/migrations/20240111101826_subscriber_email_cascade_delete.js

It didn't drop the modified foreign index before re-creating it without the cascades.

Fix invalid rollback

---

src/app/(proper_react)/(redesign)/(authenticated)/admin/dev/UserAdmin.module.scss
src/app/(proper_react)/(redesign)/(authenticated)/admin/dev/UserAdmin.tsx
src/app/(proper_react)/(redesign)/(authenticated)/admin/dev/page.tsx
src/app/api/v1/admin/users/[primarySha1]/route.ts
src/app/components/client/Button.module.scss

This provides a simple frontend for the API `/api/v1/admin/users/[sha1]/`, allowing the addition and removal of Plus status and scans, to make problems there easier to debug.
It is only accessible when running locally (i.e. when `APP_ENV="local"`), at `/admin/dev/`.

Add local admin interface to administer users

---

src/app/functions/universal/convertCamelToSnakeCase.test.ts
src/app/functions/universal/convertCamelToSnakeCase.ts
src/app/hooks/useTelemetry.ts

Jira: [MNTOR-2831](https://mozilla-hub.atlassian.net/browse/MNTOR-2831)
As [discussed](https://mozilla-hub.atlassian.net/wiki/spaces/PXI/pages/133431380?focusedCommentId=539362916) during the Engineering Office Hours we should convert the GA event categories from `camelCase` to `snake_case` to match the Glean event keys that are being reported.
[MNTOR-2831]: https://mozilla-hub.atlassian.net/browse/MNTOR-2831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Match telemetry event category keys for GA and Glean

---

src/e2e/specs/auth.spec.ts

Chore: the sign up redirect is different for local than it is for other environments, this change should handle addressing it for local vs others

address the different redirect after sign up for local and other envs.

---

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/View.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/page.tsx

I noticed when reviewing with the data team that we're missing the `dashboard.view` event.

Add missing dashboard view event

---

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/Dashboard.test.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/DashboardTopBanner/DashboardTopBannerContent.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/View.tsx

**Submitting for input on the general approach, and on how to test. Will fix the test later, but figured I'd submit this so people know this code exists.**
Jira: MNTOR-2865
Figma: N/A
Even if the user has Plus, OneRep won't automatically start removing found exposures; it first sends a request to our webhook, and then the webhook sends an opt-out request to OneRep. Meanwhile, however, we're just waiting for the systems to do their thing, and there's no action for the user to take; hence, this change also marks the exposures as being in progress.
With a new Plus user, you should not see "Action needed" "info for sale" cards on the dashboard after completing the free scan flow.

Mark new scan results as in progress for Plus users

---

src/app/components/client/GoogleAnalyticsWorkaround.tsx
src/app/layout.tsx

Jira: MNTOR-2904
Figma: N/A
In lieu of upstream adding support for setting a nonce (https://github.com/vercel/next.js/issues/61714), this forks their component and adds the support ourselves. This should make it easy to migrate once the upstream issue is resolved (which presumably will use a similar API).
Build the app, then run it and verify that data is sent.

Add a nonce to the analytics script

---

src/app/(proper_react)/(redesign)/(authenticated)/user/welcome/EnterInfo.tsx

Jira: MNTOR-2903
Figma: N/A
When entering your info in the onboarding flow, the dialog should link to https://www.mozilla.org/privacy/subscription-services/ for the privacy policy. (The current link does redirect there, but still.)
Open the EnterInfo screen, open the dialog, follow the link.

Use correct Privacy Policy link in welcome dialog

---

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/page.tsx
src/db/tables/attributions.ts

Jira: MNTOR-2908
Intended unique constraints in `attributions` table is throwing too many errors in prod. We'd want to log info instead. 
Adding the try/catch to the util function at the table level

MNTOR-2908: better logging for unique constraints

---

next.config.js

Jira: MNTOR-2911 
We are getting reports of users getting stuck trying to log in because they are somehow triggering the old endpoint. Add a redirect while we investigate.

MNTOR-2911 - redirect old oauth endpoint to new

---

src/app/api/v1/location-autocomplete/route.ts
src/app/api/v1/location-autocomplete/types.ts
src/app/components/client/LocationAutocompleteInput.tsx
src/app/hooks/__mocks__/locationSuggestions.ts
src/scripts/uploadAutoCompleteLocations.js

Jira: [MNTOR-2913](https://mozilla-hub.atlassian.net/jira/software/c/projects/MNTOR/issues/MNTOR-2913)
This PR does two things:
1. **Do not filter locations with a population of zero** 
We’ve been filtering out locations with a population of zero so we do not bloat the dataset too much. This seems to have the potential for false positives and we’ve received a report that a user could not enter their populated location. I checked and [GeoNames](https://www.geonames.org/) does not list a population. Even though I’ve contributed the population number from the latest  [2020 US Census](https://www.census.gov/programs-surveys/decennial-census/decade/2020/2020-census-results.html) to that location and this would already fix the issue for the certain location chances are high that this will be …

Include locations that have a population of zero on GeoNames (MNTOR-2913)

---

package-lock.json
package.json
src/app/functions/server/dashboard.test.ts
src/app/functions/server/dashboard.ts

So this is a big PR, but it mainly adds [property-based tests](https://fast-check.dev/docs/introduction/why-property-based/) for the `getDashboardSummary` function. I figured I'd add those after the report about the changing stats data, to rule out errors in the calculation itself.
Basically, what the test does is a bunch of runs of the following:
1. Generate some arbitrary statistics.
2. Create the breaches and scan results to match those statistics.
3. Pass those breaches and scan results to `getDashboardSummary`, then verify that the result matches the numbers generated in step 1. (This is the "property" that is verified to hold, hence the name.)
Step 1 is done randomly, and then when the test fails, it returns the seed that resulted in the invalid test result's input data. I found two …

Add property-based test, fix two bugs in stats calculation

---

src/db/tables/subscribers.js

fix: case insensitive email

---

src/app/functions/server/getUserBreaches.ts
src/db/tables/subscribers.js

Jira: MNTOR-2929
We've identified a case-sensitivity problem causing issues for some users when loading the dashboard pages, including the welcome-to-plus page. We'd like to get a fix out quickly while we work on cleaning up the reason the data is like this. This PR tries to first look up users using the email address in their FxA profile information, and if that fails, it falls back to current behavior.
It also reverts the `ilike` commits that were causing high database utilization due to missing indexes. There is a FIXME comment to follow up.
Test and watch PG stats, the query quickly rose to the top before.

Fallback behavior for case-sensitivity issues in email lookup

---

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/actions.ts
src/app/api/utils/auth.ts
src/app/api/v1/user/breaches/bulk-resolve/route.ts
src/app/api/v1/user/breaches/route.ts
src/app/api/v1/user/email/route.ts
src/app/api/v1/user/remove-email/route.ts
src/app/api/v1/user/resend-email/route.ts
src/app/api/v1/user/update-comm-option/route.ts
src/app/api/v1/user/welcome-scan/create/route.ts
src/app/api/v1/user/welcome-scan/progress/route.ts
src/app/api/v1/user/welcome-scan/result/route.ts
src/app/functions/server/getSubscriberEmails.ts
src/app/functions/server/getUserBreaches.ts
src/app/functions/server/onerep.ts

Jira: MNTOR-2938
We've been trying to fix problems with email mixed-case in a one-off way, but I think at the end of the day email addresses are a poor choice of identifier. The `fxa_uid` is a stable identifier that represents a Mozilla Accounts user, we should switch to this wherever possible. Email addresses are very complex and notoriously difficult to validate, since they are more about what servers accept historically and aren't really intended to be a stable identifier.
I've left `getSubscriberByEmail()` in a few places where it makes sense (e.g. looking up and removing an email address that is bouncing), but when we have a JWT from Mozilla Accounts, we should prefer the UID over the email.
This should entirely eliminate the class of bugs that happen when registering with a …

MNTOR-2938 - switch from looking up by email to fxa_uid wherever possible

---

src/app/components/client/GoogleAnalyticsWorkaround.tsx
src/app/hooks/useGlean.ts

Jira: MNTOR-2957
Next is attempting to load client-side analytics scripts on the server-side. This is generating spurious logs and HTTP 500s that don't seem to be impacting the product experience, but are most likely causing SSR not to work and impacting performance.
This is a workaround while we investigate.

MNTOR-2957 - avoid loading client-side analytics on server

---

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/LeakedPasswordsLayout.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/[type]/LeakedPasswordsLayout.test.tsx

Jira: [MNTOR-2956](https://mozilla-hub.atlassian.net/browse/MNTOR-2956)
Prevent users from visiting the “leaked passwords” step in the guided resolution flow.
- There are two scenarios where users can land on an empty “leaked passwords” breach resolution step. Both require a user to have an account with unresolved breaches that include passwords:
1. Fix resolve guided resolution step ”leaked passwords”  and go back in the browser history.
2. Directly navigate to `/user/dashboard/fix/leaked-passwords/passwords`.
[MNTOR-2956]: https://mozilla-hub.atlassian.net/browse/MNTOR-2956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Redirect users from leaked password step if nothing to resolve

---

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/HighRiskBreachLayout.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/[type]/HighRiskBreachLayout.test.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/LeakedPasswordsLayout.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/SecurityRecommendationsLayout.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/[type]/SecurityRecommendations.test.tsx

Jira: [MNTOR-2956](https://mozilla-hub.atlassian.net/browse/MNTOR-2956)
Prevent users from visiting or navigating back to an already resolved step in the guided resolution flow.
1. Fix a breach category, for example, “high-risk data breaches”
2. Directly navigate to `/user/dashboard/fix/high-risk-data-breaches`.
[MNTOR-2956]: https://mozilla-hub.atlassian.net/browse/MNTOR-2956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Guard breach resolution steps if already resolved (MNTOR-2956)

---

src/app/api/v1/fxa-rp-events/route.ts

Jira: MNTOR-2995
Figma: 
Not having fxa tokens shouldn't be considered a failure and return 500
We will simply revoke tokens if available

MNTOR-2995: not having fxa tokens shouldn't return 500

---

src/app/api/v1/fxa-rp-events/route.ts

Jira: MNTOR-2997
We have a fxa webhook that’s throwing 500 for an edge case:
* a user subscribed
* the user never ran a one rep scan, thus no id
* the user unsubbed
In this case, we are currently throwing 500 and spamming the fxa queue.
We’d want to return a 200

MNTOR-2997: deactivate without onerep id returns 200

---

src/app/components/client/stories/ProgressBar.stories.tsx

It's a bit hard to test since you have to run the manual scan to get to the progress bar, so with a separate story, we can at least see what it looks like when loading.
I added this to try and verify https://github.com/mozilla/blurts-server/pull/4271, but though it probably isn't the best way to verify that specific case, I figured the story might still be useful.
View it live at https://deploy-preview-4272--fx-monitor-storybook.netlify.app/?path=/story/progress-bar--progress-bar.

Add a story to test the progress bar

---

src/app/components/client/Button.test.tsx
src/app/components/client/Button.tsx

This is a followup after testing https://github.com/mozilla/blurts-server/pull/4134#discussion_r1486547071.
Since the Button is now responsible for changing its contents, it also knows enough to decide whether aria-live is needed.
(Additionally, passing `aria-live` to `useButton` doesn't actually apply it to the element itself either, apparently - or at least, my screen reader did not read out the content change.)
With your screen reader on, add an email address. When the button changes to the loading state in the dialog, that should be read out by your screen reader - it is not on `main`.

Move aria-live into <Button>

---

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/actions.ts
src/app/api/utils/email.ts
src/db/tables/emailAddresses.js

Jira: MNTOR-2988
Figma: N/A
It was possible to trigger re-sending any verification email by simply modifying the email ID passed in to the /resend-email/ endpoint. With this change, we also verify that the email is actually linked to the current subscriber - and enforce that for any route calling sendVerificationEmail /
resetUnverifiedEmailAddress.
See ticket.

Only (re)send verification emails for current user

---

.circleci/config.yml

Jira: MNTOR-2247
Take out the `deploy to dockerhub` step in CircleCI. We already do that via GHA

MNTOR-2247: circleCI - take out deploy to dockerhub step

---

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/SettingsPage.test.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/View.tsx

Jira: https://mozilla-hub.atlassian.net/browse/MNTOR-1371?focusedCommentId=857676
When the `MonitorAccountDeletion` flag is enabled, don't show the link to SubPlat to cancel the subscription (that's what's replaced by the deletion flow).
vs
Visit settings with the flag enabled and disabled.

Only show cancellation link if deletion is hidden

---

src/scripts/build/getAutoCompleteLocations.js

Sorry, I broke that in https://github.com/mozilla/blurts-server/pull/4439 (https://github.com/mozilla/blurts-server/commit/b546e7b705addff70ead7954c8084baf6f112232 specifically). I moved the script, but since the path wasn't relative to the script, I shouldn't have changed that.

Fix: location data is relative to root

---

.github/workflows/build.yaml
.github/workflows/lint.yaml
scripts/check-node-version-alignment.js

Followup to https://github.com/mozilla/blurts-server/pull/4400#discussion_r1556418422. It's not pretty, and it won't keep our dependencies up-to-date for us, but it will ensure that we don't forget to update any references to the Node version when Dependabot updates the Node version in our `Dockerfile`. This way, everything is aligned with what will be production.

Node version consistency

---

package.json

This won't re-build it if `nimbus.yaml` changes, but at least it won't break if you haven't run it before, or if it's changed since the last time you started the dev server.

Always build experiment data before npm run dev

---

.stylelintrc
src/app/components/client/CsatSurvey.module.scss

!important can never be overridden, which is almost never what you
want. Better is to provide either a more specific selector, or
potentially a CSS @layer.
For more information, see
https://developer.mozilla.org/en-US/docs/Web/CSS/important#best_practices
(Not sure why this isn't in stylelint's recommended set; maybe for the rare exceptions, e.g. user styles?)

Block the use of !important in our CSS

---

package.json

The cron job configs can then just point to these scripts, and we can update file paths in our own repo as needed. (Particularly relevant if we migrate the breach alerts job to TypeScript.)

Add npm scripts to run cron jobs

---

src/app/functions/l10n/cronjobs.ts

I moved the l10n loading from /src/emails/getEmailL10n.node.ts to /src/app/functions/l10n/cronjobs.ts in
c68110264ef9c687005bd0a7ee0e4f0ffecc98a5, and in doing so, missed that I also had to update the paths to the FTL files. These are loaded at runtime, so I didn't get a build error for that either.

Fix paths to FTL files from cron job l10n loading

---

src/app/functions/l10n/cronjobs.ts

Jira: MNTOR-3067
Figma: N/A
When the cronjob l10n loading code gets included from a cronjob file, it gets inlined by esbuild. This means that paths that were relative to that specific module, all of a sudden are relative to the calling module.
In Next.js, Storybook, and Jest, this is resolved by using Webpack's `require.context`. In esbuild, however, this isn't available, thus, this simply walks up the tree until it finds the directory that contains `locales`.
This fixes the following error when running the monthly activity cronjob:
```
Error: ENOENT: no such file or directory, scandir '/locales'
```
Run `npm run build-cronjobs; npm run cron:monthly-activity`. You should not get the above error, and instead, the cronjob should just run.

Fix cron jobs not finding FTL files

---

.github/workflows/preview_deploy_gcp.yml
.github/workflows/preview_deploy_gcp_cleanup.yml

Jira: MNTOR-3183
Generating database on the fly as the PR opens, clean up the database when the PR closes or merges
Also cleans up the cloud run service generated that links with the database

MNTOR-3183: Generating / cleaning up DB on the fly with each PR open/merge

---

.github/workflows/preview_deploy_gcp.yml
.github/workflows/preview_deploy_gcp_cleanup.yml

They don't have access to the credentials needed for deployment (because the updated dependencies could exploit those).

Don't run preview deployments for Dependabot PRs

---

src/utils/email.js
src/utils/email.test.js

Jira: MNTOR-3219
The `sendEmail` function doesn't currently log sends and errors on its own, this leaves it up to the caller but it's an important function that we should be logging. It made some recent SES configuration changes more difficult to track down than we would've liked.
Sending email locally or on stage/prod should now log when an email is sent or an error occurs, in addition to returning info to the caller.

MNTOR-3219 - sendEmail function should logs sends and errors

---

src/app/(proper_react)/(redesign)/(authenticated)/admin/dev/UserAdmin.tsx
src/app/api/v1/admin/users/[fxaUid]/route.ts

Jira: MNTOR-3155
This is mostly just removing code, since internally this code turned a sha1 hash of the primary email address into a fxa UID for lookup. I also noticed that the error handling wasn't logging exceptions correctly so I corrected that.
`GET` of a valid `fxa_uid` from `subscribers` table should return relevant IDs.
`PUT` with the following should take the appropriate action:
```
{
"actions":[
"subscribe",
"unsubscribe",
"delete_onerep_profile",
"delete_onerep_scans",
"delete_onerep_scan_results",
"delete_subscriber"
]
}
```
http://localhost:6060/admin/dev provides a convenient dev-only web UI to manage this.

MNTOR-3155 - look up users by fxa uid not primary sha1 hash of email

---

package-lock.json
package.json

Upgrade to glean.js 5.0.2 to pick up fix for `ModuleNotFoundError: No module named 'pkg_resources'.` error we're seeing in Monitor builds.

chore: upgrade to glean.js 5.0.2

---

src/app/functions/server/getExperiments.ts

Jira: MNTOR-3239
Per the Nimbus team, they are expecting `language` and `region` for the parameter names of targeting criteria. We're currently passing `locale` and `countryCode` respectively so it's not matching.

use language and region for Nimbus/Cirrus

---

src/e2e/specs/landing.spec.ts

The rebrand banner flag was removed in https://github.com/mozilla/blurts-server/pull/4586 so this test is failing. Removed the part this is causing the failiure
Passing job: https://github.com/mozilla/blurts-server/actions/runs/9230359512

Remove rebrand banner check in e2e tests

---

locales/nn-NO/fix.ftl

Reverts mozilla/blurts-server#4600
We are investigating an unexpected spike in out-of-memory errors that started on stage right after this was landed. It seems unlikely this patch would cause the problem by itself, unless there's an existing bug in Fluent or its dependencies but we want to try rolling back things in the regression range.

Revert "Import translations from l10n repository (2024-05-28)"

---

config/nimbus.yaml

We're testing roll-out on stage, we need to set `welcome-scan-optional-info` to `false` by default.

disable welcome-scan-optional-info feature on stage for testing Nimbus

---

src/app/functions/server/getExperiments.ts

Make the `countryCode` upper-case for Cirrus, we should consider changing this throughout the code to be more compliant wiht ISO-3166. I'll file a separate ticket if we decide to do that.

Cirrus expects ISO-3166 compliant upper-case country code

---

src/app/(proper_react)/(redesign)/(public)/breach-details/[breachName]/BreachDetailView.tsx

Jira: MNTOR-3226
Figma:
Seems like the issue was because href interpreted the given domain as a relative path instead of absolute. Adding a "//" in front seems to have fixed the issue.
Follow the steps in the jira ticket for any breach that has its 'breach-details' page.

MNTOR-3226 - Breach details pages link to a wrong website URL

---

.github/workflows/e2e_cron.yml
.github/workflows/e2e_pr.yml
.gitignore
playwright.config.js
src/e2e/README.md
src/e2e/pages/landingPage.ts
src/e2e/specs/landing.spec.ts
src/e2e/specs/purchase.spec.ts

Jira: MNTOR-3210, MNTOR-3211
Adds an alert sent to #monitor-alerts in slack when the e2e cron fails. Fix for flaky tests and made retries for tests a 1 instead of 2.
* Run this in the GHA tab against this branch.
Test pass except paypal ones
https://github.com/mozilla/blurts-server/actions/runs/9408352400

MNTOR-3210, MNTOR-3211: E2E cron failure alerts and warning fixes.

---

src/app/(proper_react)/(redesign)/(authenticated)/admin/emails/EmailTrigger.tsx
src/app/(proper_react)/(redesign)/(authenticated)/admin/emails/actions.tsx

Jira: [MNTOR-2700](https://mozilla-hub.atlassian.net/browse/MNTOR-2700)
Add the ability to send a test “First data broker removal fixed” email from the admin view.
Note: Sending emails locally does not work at the moment.
1. Make sure you are added as an admin
2. Visit `/admin/emails`
[MNTOR-2700]: https://mozilla-hub.atlassian.net/browse/MNTOR-2700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add admin email trigger for first data broker removal fixed

---

src/app/functions/server/getExperimentationId.ts

Jira: MNTOR-3291
The `experimentationId` is not being set correctly for signed-in users, looks like confusion over the type (it's a `number` but there's a check for `string`).

MNTOR-3291 - set experimentationId correctly for signed-in users

---

locales-pending/emails-all.ftl
src/app/(proper_react)/(redesign)/(authenticated)/admin/emails/actions.tsx
src/emails/templates/EmailFooter.tsx
src/emails/templates/firstDataBrokerRemovalFixed/FirstDataBrokerRemovalFixed.stories.tsx
src/emails/templates/firstDataBrokerRemovalFixed/FirstDataBrokerRemovalFixed.test.tsx
src/emails/templates/firstDataBrokerRemovalFixed/FirstDataBrokerRemovalFixed.tsx
src/scripts/cronjobs/firstDataBrokerRemovalFixed.tsx

Jira:
- [MNTOR-3294](https://mozilla-hub.atlassian.net/browse/MNTOR-3294): Some links in First data broker removal fixed email redirect to the Action needed tab instead of the Fixed tab
- [MNTOR-3296](https://mozilla-hub.atlassian.net/browse/MNTOR-3296): Footer displays standard text instead of custom text referring to a one-time automated email
Figma: https://www.figma.com/design/CaEKIhvSJqf6KNIMzSkt40/Concepts-for-Monitor-MVP-Redesign?t=hTR7PAsYeLpS2V1N-0
Updates the footer text for one-time emails and the dashboard link target.
| Footer text (before) | Footer text (after) |
| --- | --- |
| <img width="491" alt="image" src="https://github.com/mozilla/blurts-server/assets/13835474/50f82a36-90c3-4bea-a9ec-464b4c6cc515"> | <img width="480" alt="image" …

First data broker removed email adjustments (MNTOR-2700)

---

src/app/(proper_react)/(redesign)/(public)/how-it-works/HowItWorksView.module.scss

Jira: MNTOR-3308
Added horizontal padding for intro of brokers and breaches sections on mobile

updated styles to add padding to intro sections

---

src/app/(proper_react)/(redesign)/(public)/how-it-works/HowItWorksView.module.scss
src/app/(proper_react)/(redesign)/(public)/how-it-works/HowItWorksView.test.tsx
src/app/(proper_react)/(redesign)/(public)/how-it-works/components/DataBreaches.tsx

Jira: MNTOR-3310
Figma:
Also resolves MNTOR-3311
Users (new and returning) clicking Get Free Scan buttons on How it works page stuck in loop that returns them to the  page after login, rather than taking them to the dashboard
1. Have VPN location set to USA
2. Be signed in to Monitor;
3. Be on the https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net/how-it-works 
4. Scroll down to the “Get free scan” CTA;
5. Click on the CTA;
6. Observe behavior;

hrefs added to DataBreaches CTA buttons

---

src/app/components/client/exposure_card/ExposureCard.stories.ts
src/app/components/client/exposure_card/ScanResultCard.tsx
src/app/components/server/StatusPill.module.scss
src/app/components/server/StatusPill.tsx

Jira:
- [MNTOR-3201](https://mozilla-hub.atlassian.net/browse/MNTOR-3201)
- [MNTOR-3329](https://mozilla-hub.atlassian.net/browse/MNTOR-3329)
Fixes the exposure card content for manually fixed results as well as the status pill layout for mobile.
| Before | After |
| --- | --- |
| <img width="294" alt="image" src="https://github.com/mozilla/blurts-server/assets/13835474/b3efad68-765d-465a-a85d-833b236c58f4"> | <img width="284" alt="image" src="https://github.com/mozilla/blurts-server/assets/13835474/3a2a6088-d56a-48be-a2c0-c0e191a65ae3"> |
Step to reproduce from QA:
1. Navigate to the Monitor dashboard.
2. Manually mark some of the Data Brokers as fixed/removed.
3. Upgrade to Monitor Plus.
4. Return to the “fixed tab” and observe the previously manually fixed cards.
[MNTOR-3201]: …

Exposure card info for manually fixed results (MNTOR-3329)

---

src/scripts/cronjobs/firstDataBrokerRemovalFixed.tsx

Jira: [MNTOR-3352](https://mozilla-hub.atlassian.net/browse/MNTOR-3352)
Ensure a subscriber has their first data broker removal before attempting to send the email.
[MNTOR-3352]: https://mozilla-hub.atlassian.net/browse/MNTOR-3352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ensure a subscriber has their first data broker removal before sending email

---

src/app/(proper_react)/(redesign)/(public)/SignUpForm.tsx

Jira: MNTOR-3354
Navigate to the Monitor “How it works” page;
Scroll down to the last Get free scan button;
Click on the email field and observe the telemetry pings;
Click on the Get free scan button and observe the telemetry pings;
Refresh the page and repeat only step 4, observing the telemetry pings;
Expected result:
Clicking the Get free scan button triggers only a ping for clicking the button;
Actual result:
Clicking the Get free scan button after interacting with the field triggers both a field focus ping and a clicking the button ping;
Note: [Comments in Jira ticket](https://mozilla-hub.atlassian.net/browse/MNTOR-3354?focusedCommentId=905069) include how to observe telemetry pings when running locally

MNTOR-3354 - Last Get free scan button can trigger an extra field focused telemetry ping

---

src/app/components/client/csat_survey/CsatSurveyBanner.module.scss
src/app/components/client/csat_survey/CsatSurveyBanner.tsx

Jira: [MNTOR-3317](https://mozilla-hub.atlassian.net/browse/MNTOR-3317)
Figma: https://www.figma.com/design/DTbmXzCQCw2PxXpHQW8yfW/Monitor-MVP-Enhancements?node-id=329-6723&t=oWtFX5z5dIEj8Iii-0
Adjusts the CSAT banner layout to be more fluid for smaller viewports.
| Desktop | Mobile |
| --- | --- |
| <img width="761" alt="image" src="https://github.com/mozilla/blurts-server/assets/13835474/ad34b12f-210d-4c3a-8dec-5b234fbb02c7"> | <img width="422" alt="image" src="https://github.com/mozilla/blurts-server/assets/13835474/764f3357-e22a-4962-bbe4-460fb875e748"> |
[MNTOR-3317]: https://mozilla-hub.atlassian.net/browse/MNTOR-3317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adjust CSAT banner button layout (MNTOR-3317)

---

src/app/components/client/PetitionBanner.tsx

Jira: [MNTOR-3337](https://mozilla-hub.atlassian.net/browse/MNTOR-3337)
Figma: https://www.figma.com/board/LGjPMlfA7Li3xkS5YZ6VLY/Monitor-Telemetry-Documentation?node-id=0-1&t=N3IYkNEwLXvLrrTc-0
Adds telemetry to the petition banner.
1. Enable the experiment `data-privacy-petition-banner` for local in `nimbus.yaml`
2. Run `npm run build-nimbus`
3. Navigate to the dashboard and interact with the banner
[MNTOR-3337]: https://mozilla-hub.atlassian.net/browse/MNTOR-3337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add telemetry to PetitionBanner (MNTOR-3337)

---

src/app/functions/universal/user.ts
src/utils/fxa.js

Jira: MNTOR-3359
Figma: N/A
The settings page would refuse to load since https://github.com/mozilla/blurts-server/pull/4731 because we threw an error after SubPlat's API returned a 404, which it always does for free users.
TypeScript didn't catch this, because we didn't define the type for the SubPlat API response, and instead "laundered" it through JSON.parse(JSON.stringify()) to mark it as `any`. So I've added a minimal type definition that includes the data we use (plan_id), and a bit of data that we might use later, but it's not unlikely that we'll need to update it as we read more data from this API.
Create a new free account, then visit the settings page. This results in a server error on `main`, but should no longer do so on this branch.

Don't crash when SubPlat doesn't know a user

---

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/SettingsPage.test.tsx

Jira: MNTOR-3018
Added unit tests to confirm that "add email address" button is shown for users with up to 4 email addresses, and hidden when they reach five
Run unit tests locally

Adding test for mntor 3018

---

.github/workflows/unittests.yaml
package.json

It took quite a bit of tracking down when all my tests failed due to my not having generated the Nimbus experiment types. Since the code generation happens basically instantly, it seems fine to just run it every time before running the tests.

Make sure experiment code exists during tests

---

src/appConstants.js

We need to explicitly provide the [option.path](https://github.com/kerimdzhanov/dotenv-flow?tab=readme-ov-file#optionspath) in [appConstants.js](https://github.com/mozilla/blurts-server/blob/main/src/appConstants.js#L12) when running scripts like `npm run db:migrate` which change the `CWD`.

Explicitly provide env file path

---

config/nimbus.yaml
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/Dashboard.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/Dashboard.test.tsx
src/app/components/client/csat_survey/CsatSurvey.tsx
src/app/components/client/csat_survey/surveys/automaticRemovalCsatSurvey.ts
src/app/components/client/csat_survey/surveys/csatSurvey.ts
src/app/components/client/stories/CsatSurvey.stories.ts
src/db/tables/featureFlags.ts

Converts the experiment `automatic-removal-csat-survey` to use the feature flag `AutomaticRemovalCsatSurvey` instead.

Convert experiment automatic-removal-csat-survey to feature flag

---

src/appConstants.js

Don't manually load env vars in Storybook.
This breaks Storybook, and it should already emulate Next.js's env var loading behaviour.
See https://fx-monitor-storybook.netlify.app/?path=/story/pages-logged-in-dashboard--dashboard-non-us-no-breaches for an example of the breakage.
Here's that same page for this PR: https://deploy-preview-4806--fx-monitor-storybook.netlify.app/?path=/story/pages-logged-in-dashboard--dashboard-non-us-no-breaches

Fix Storybook

---

config/nimbus.yaml

Disable the experiment also for local environments so it does not [break the Monitor Cron e2e tests](https://github.com/mozilla/blurts-server/actions/runs/9953077903).

Fix e2e: Disable landing page experiment locally

---

src/app/(proper_react)/(redesign)/(public)/FreeScanCta.tsx
src/app/(proper_react)/(redesign)/(public)/LandingView.test.tsx

Passing the UTM parameter to Mozilla accounts endpoint `/authorization` results in an `Invalid OAuth parameter: service` error.

Remove invalid OAuth parameter service

---

src/utils/fxa.js

Jira: MNTOR-3344
use account uri instead of api uri (not set in prod)

MNTOR-3344: use account uri

---

src/app/functions/server/onerep.ts

Catch and log if stats API result cannot be parsed. `undefined` being return will cause the waitlist functionality to activate.

ongoing incident: catch and log profile stats being down

---

.env

I just ran into this testing locally, since `OAUTH_API_URI` was removed my local env fell back to `OAUTH_ACCOUNT_URI` default which points to the prod URL and not stage (as the other `OAUTH` examples do)

change OAUTH_ACCOUNT_URI to stage to match other OAUTH defaults

---

config/nimbus.yaml
locales/en/landing-all.ftl
src/app/(proper_react)/(redesign)/(public)/FreeScanCta.tsx
src/app/(proper_react)/(redesign)/(public)/LandingView.test.tsx

Jira: [MNTOR-3429](https://mozilla-hub.atlassian.net/browse/MNTOR-3429)
Figma: https://www.figma.com/design/YqpVpUbSTzZMj9Jbp2po8Q/Mozilla-Monitor-Premium-LP?node-id=3562-11693&t=WW3B3g07hmf6qdsB-4
Update the landing page CTA label for experiment variation B. From the Jira ticket:
> On Variation B: we have the CTA as “Sign in to get free scan”. After reviewing on stage we believe this should be changed to “Sign up to get free scan” as “Sign in” might cause confusion for users because they might not see a clear path forward to sign up.
[MNTOR-3429]: https://mozilla-hub.atlassian.net/browse/MNTOR-3429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update Monitor CTA experiment copy (MNTOR-3429)

---

jest.config.cjs

Without this change, running `npm test` after running `npm run build-cronjobs` will result in failing tests.

Do not run tests of compiled cronjobs

---

.github/workflows/e2e_cron.yml
.github/workflows/e2e_pr.yml
package.json

Jira: MNTOR-3391
Some people might get an error with 22.5.0 when using Volta and `npm run build`
Ref: https://github.com/nodejs/node/issues/53902

MNTOR-3391: node 22.5.1 fixes an error with npm build

---

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/page.tsx
src/app/functions/server/user.ts
src/app/functions/universal/user.ts

Jira: MNTOR-3460
`fxa` module can only be used by server components, the import from a client component is causing confusing messages to be logged to the browser.
Browser devtools console should not log messages such as:
```
Required environment variable was not set
```

fix client import, move checkUserHasMonthlySubscription from universal to server function

---

.github/workflows/docker_build_deploy.yml

Jira: MNTOR-
Figma:
This will fix the errors in the deploy pipeline from two jobs running at the same time.  latest tag is the same as sha tag as well.

chore: removes docker latest tag and push

---

src/app/components/client/csat_survey/CsatSurveyBanner.tsx
src/app/components/client/csat_survey/surveys/csatSurvey.ts
src/app/hooks/useViewTelemetry.ts
src/telemetry/metrics.yaml

Jira: [MNTOR-3469](https://mozilla-hub.atlassian.net/browse/MNTOR-3469)
Add `view` and `dismiss` telemetry to the CSAT surveys.
[MNTOR-3469]: https://mozilla-hub.atlassian.net/browse/MNTOR-3469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add additional CSAT telemetry (MNTOR-3469)

---

src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/components/FlagEditor.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/Dashboard.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/DashboardTopBanner/DashboardTopBannerContent.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/automatic-remove/AutomaticRemove.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/manual-remove/ManualRemove.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/start-free-scan/StartFreeScan.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/view-data-brokers/ViewDataBrokers.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/WelcomeToPlus.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/WelcomeToPlusView.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/page.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/[type]/HighRiskDataBreach.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/[type]/LeakedPasswords.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/[type]/SecurityRecommendations.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/layout.tsx
src/app/(proper_react)/(redesign)/(public)/PublicShell.tsx
src/app/(proper_react)/(redesign)/(public)/how-it-works/page.tsx
src/app/(proper_react)/(redesign)/Footer.tsx
src/app/(proper_react)/(redesign)/MobileShell.tsx
src/app/(proper_react)/(redesign)/Shell.tsx
src/db/tables/featureFlags.ts

https://github.com/mozilla/blurts-server/pull/4666/files#diff-a54be8bc10c4d286b8f42676102b87a3d78308578c01609682cef692b1d812b9 ignored the allowlist for the Welcome to Plus page when determining whether to link to the "How it works" page, and although that made sense for the public pages, when I now used that same list of enabled flags for the removal time estimation, all of a sudden the allowlist didn't work.
I also removed the `HowItWorksPage` flag, since it's now enabled, and had a couple of other allowlist-free feature flag fetches.

Don't ignore allowlist on "Welcome to Plus" page, remove "HowItWorksPage" flag

---

README.md
locales/en/email-strings.ftl
package.json
src/apiMocks/mockData.ts
src/app/(proper_react)/(redesign)/(authenticated)/admin/emails/EmailTrigger.tsx
src/app/(proper_react)/(redesign)/(authenticated)/admin/emails/actions.tsx
src/app/functions/l10n/cronjobs.ts
src/emails/templates/EmailFooter.tsx
src/emails/templates/breachAlert/BreachAlertEmail.stories.tsx
src/emails/templates/breachAlert/BreachAlertEmail.test.tsx
src/emails/templates/breachAlert/BreachAlertEmail.tsx
src/scripts/cronjobs/emailBreachAlerts.test.ts
src/scripts/cronjobs/emailBreachAlerts.tsx
src/utils/formatDate.ts

Jira: MNTOR-3448
Figma: N/A
This updates the breach alert email to be based on the new email template (behind a flag).
As received on Mailinator:
Previous version, for comparison:
The email is present in Storybook, so you can [view it there](https://deploy-preview-4895--fx-monitor-storybook.netlify.app/?path=/story/emails-breach-alert--breach-alert-email-story).
You can also send it to yourself via `/admin/emails`.
However, if you want to actually verify that it works as it would do in production, that's a bit more involved.
The first step would be to enable the `RedesignedEmails` feature flag for your user. Then follow the instructions in the README under "PubSub". Then to make sure the email gets sent to your email addess, you'll want to modify the `getSubscribersByHashes` function in …

Port breach alert email to new email template

---

src/app/(proper_react)/(redesign)/(authenticated)/admin/emails/EmailTrigger.tsx
src/app/(proper_react)/(redesign)/(authenticated)/admin/emails/actions.tsx
src/app/api/utils/auth.tsx
src/emails/components/BreachCard.tsx
src/emails/templates/signupReport/SignupReportEmail.stories.tsx
src/emails/templates/signupReport/SignupReportEmail.test.tsx
src/emails/templates/signupReport/SignupReportEmail.tsx

Jira: MNTOR-3449
Figma: N/A
Note that the old template includes code to render data from a variable `emailBreachStats`, but that variable is always unset. Thus, we're never rendering that anymore, so I didn't port it. For what was originally in that variable, see
https://github.com/mozilla/blurts-server/blob/870cca305e2e52ddfe7e0ea5ff5611a58537b70f/template-helpers/emails.js#L8-L33
Before:
and without breaches:
After:
and without breaches:
From easy to hard, aka from superficial to more thorough:
1. Open it [in Storybook](https://deploy-preview-4922--fx-monitor-storybook.netlify.app/?path=/story/emails-signup-report)
2. Send it to yourself via `/admin/emails`
3. Enable the `RedesignedEmails` feature flag. Create a new account with an email that has/has not been breached.

Port the signup report email to the new template

---

src/utils/breaches.ts

Jira: [MNTOR-3495](https://mozilla-hub.atlassian.net/browse/MNTOR-3495)
Resolving breaches for secondary emails is currently broken as we are passing the users primary email address to `bundleVerifiedEmails` accidentally by default since [converting `breaches.js` to TS](https://github.com/mozilla/blurts-server/pull/4876).
[MNTOR-3495]: https://mozilla-hub.atlassian.net/browse/MNTOR-3495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix resolving breaches for secondary emails (MNTOR-3495)

---

src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/components/AddFeatureFlag.tsx
src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/components/FlagEditor.module.scss
src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/components/FlagEditor.tsx
src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/page.module.scss
src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/page.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/page.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/[type]/page.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/page.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/[type]/page.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/[type]/page.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/page.tsx
src/app/(proper_react)/(redesign)/(public)/page.tsx
src/db/tables/featureFlags.ts

Jira: MNTOR-3528
Figma:
The allowlist now only applies to disabled flags, allowing us to enable those flags for specific users. The code now also makes more explicit that you should always pass the user's email address, the only exception being if they're not logged in. (It makes intuitive sense that a flag can't be enabled for a specific user if that user is not logged in.)
In other words, enabling a flag now always enables it for everyone, regardless of the allowlist.
Also note that I moved disabled feature flags to the top, since those are the ones we'll usually want to take action on, whereas we don't usually want to disable flags once they are enabled. (And once we remove their code, disabling them doesn't do anything anymore.)
This is the right moment to make this change, because …

More intuitive flag behaviour

---

src/app/api/v1/hibp/notify/route.ts

Jira: MNTOR-3465
Respond with 429 instead of 500 for HIBP webhook

MNTOR-3465: HIBP responses with 429

---

locales-pending/dashboard-premium.ftl
locales-pending/fix-premium.ftl
locales-pending/landing-premium.ftl
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/Dashboard.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/DashboardTopBanner/DashboardTopBannerContent.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/DashboardTopBanner/index.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/View.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/ResolutionContainer.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/WelcomeToPlus.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/WelcomeToPlusView.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/page.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/HighRiskBreachLayout.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/[type]/HighRiskDataBreach.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/[type]/page.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/page.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/LeakedPasswordsLayout.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/[type]/LeakedPasswords.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/[type]/page.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/SecurityRecommendationsLayout.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/[type]/SecurityRecommendations.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/[type]/page.tsx
src/app/(proper_react)/(redesign)/(public)/Faq.tsx
src/app/(proper_react)/(redesign)/(public)/LandingView.stories.tsx
src/app/(proper_react)/(redesign)/(public)/LandingView.tsx
src/app/(proper_react)/(redesign)/(public)/page.tsx
src/app/components/client/ExposuresFilterExplainer.tsx
src/app/components/client/PercentageChart.tsx
src/app/components/client/ProgressCard.tsx
src/app/components/client/stories/ProgressCard.stories.ts
src/db/tables/featureFlags.ts

Jira: MNTOR-3543
Figma:
This is a followup to https://github.com/mozilla/blurts-server/pull/4854, removing the `SetExpectationsForUsers` flag, now that it's been enabled.
We shouldn't mention the 7-14-day period anymore. (Even though it was prefixed by "typically", it was still a surprise if removals took longer.)

Remove `SetExpectationsForUsers` flag

---

src/app/(proper_react)/(redesign)/(public)/breaches/BreachIndexView.module.scss

Jira: MNTOR-3510
Figma: N/A
The minimum breach card size of $content-xs caused the breach cards from overflowing on small screens. Removing that and reducing some padding elsewhere, the cards are able to take up the space they need on mobile.
After:
Before:
Visit https://blurts-server-pr-4971-mgjlpikfea-uk.a.run.app/breaches. Compare to https://monitor.mozilla.org/breaches on small screens.

Prevent breach cards from overflowing on mobile

---

locales-pending/settings-premium.ftl
locales/en/settings.ftl
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/AlertAddressForm.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/SettingsPage.test.tsx

Jira: MNTOR-3512
Figma: N/A
Also, since that setting only applies to Plus users, moved the string to the non-localised strings. (The previous string might come back in a future feature, but as I understand it, Pontoon will remember it for easy re-translation.)
Visit the Settings page with a Plus account.

Rename Monthly Monitor report to *Plus report

---

next-env.d.ts
package-lock.json

Next automatically did this after I recently reset my dev environment:
```
⚠ Found lockfile missing swc dependencies, patching...
○ Compiling /instrumentation ...
⚠ Lockfile was successfully patched, please run "npm install" to ensure @next/swc dependencies are downloaded
```

land patched package lock for SWC

---

src/app/(proper_react)/(redesign)/(authenticated)/admin/emails/actions.tsx

We need the user's scan and breach data when that user is eligible for Plus (i.e. is in the US), does not have Plus already, and has run a scan - that's when we show the number of data points found.
The actual email sending logic (in
src/scripts/cronjobs/emailBreachAlerts.tsx) [does this correctly](https://github.com/mozilla/blurts-server/blob/df0207dd3063b8d522ccd836955c408f6ae755ca/src/scripts/cronjobs/emailBreachAlerts.tsx#L283), but the admin page inadvertently checked that the user *did* have Plus, making QA unable to test that variant.

Fix data loading logic on admin email page

---

.github/workflows/e2e_cron.yml
.github/workflows/e2e_pr_full.yml
playwright.config.js

Let’s keep the default `maxFailures` option for the E2E tests that are running in the daily cronjob against `stage` as well as for the blocking `@smoke` test suite.

Only set max failures for the optional full E2E test suite

---

esbuild.cronjobs.js
src/emails/components/BreachCard.tsx
src/emails/components/EmailBanner.tsx
src/emails/components/EmailDataPointCount.tsx
src/emails/components/EmailHero.tsx
src/emails/templates/EmailFooter.tsx
src/emails/templates/EmailHeader.tsx
src/emails/templates/breachAlert/BreachAlertEmail.tsx
src/emails/templates/firstDataBrokerRemovalFixed/FirstDataBrokerRemovalFixed.tsx
src/emails/templates/monthlyActivity/MonthlyActivityEmail.tsx
src/emails/templates/monthlyActivity/freeUser/MonthlyActivityFreeUser.tsx
src/emails/templates/signupReport/SignupReportEmail.tsx
src/scripts/cronjobs/emailBreachAlerts.tsx
src/scripts/cronjobs/firstDataBrokerRemovalFixed.tsx
src/scripts/cronjobs/monthlyActivity.tsx

This caused errors in production, but not in dev, making them easy to slip through. Specifically, the error was just re-introduced via `<HeaderStyles>`.
With this changes, it's no longer possible to forget to add the React import, because it will be added automatically (just like it is for the Next.js site).
See https://esbuild.github.io/api/#jsx.

Remove need to import React in cronjobs

---

.github/workflows/e2e_cron.yml

Let’s disable parallel E2E test execution again for the [Monitor Cron e2e Tests](https://github.com/mozilla/blurts-server/actions/workflows/e2e_cron.yml) until they run more stable. We can keep improving and debugging the E2E test suite with new the optional [Monitor E2E Test Suite (full)](https://github.com/mozilla/blurts-server/actions/workflows/e2e_pr_full.yml) that is running no every PR.

Disable parallel test execution for E2E cronjob

---

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/Dashboard.test.tsx
src/app/components/client/csat_survey/CsatSurvey.tsx

Jira: [MNTOR-3657](https://mozilla-hub.atlassian.net/browse/MNTOR-3657)
After disabling the follow-up CSAT survey for the Petition banner, the condition guarding the CSAT banners did not evaluate to `true` for CSAT surveys with a lower priority. The change ensures that we do not show any CSAT survey if the Petition banner is displayed.
[MNTOR-3657]: https://mozilla-hub.atlassian.net/browse/MNTOR-3657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Show any CSAT survey only after the petition banner has been dismissed

---

src/app/(proper_react)/(redesign)/(authenticated)/admin/emails/actions.tsx
src/app/functions/cronjobs/unsubscribeLinks.ts
src/scripts/cronjobs/monthlyActivityFree.tsx

Jira: N/A
Figma:
It's not just used by the cronjob, but also by the admin tool on /admin/emails/. Since that is a Next.js page, if the function is imported from a module that also imports the cronjob l10n module, it breaks. Thus, I've moved it into its own module.
Try sending an email using the admin email tool (any email). It should no longer fail.

Move unsubscribe link generation into own module

---

src/db/tables/emailAddresses.ts

Jira: MNTOR-1452
As previously discussed, this sets the isolation level to `SERIALIZABLE` so adding secondary email works as expected.
See Jira ticket for test case.

correct transaction isolation level for adding email

---

src/app/components/client/PromptNoneAuth.tsx

Jira: [MNTOR-3492](https://mozilla-hub.atlassian.net/browse/MNTOR-3492)
Update the dashboard link for FxA silent authentication to link directly to the Premium upsell.
1. Enable the feature flag `PromptNoneAuthFlow`
2. Visit http://localhost:6060/?utm_source=moz-account&utm_campaign=settings-promo&utm_content=monitor-free with and without the user authenticated with FxA
[MNTOR-3492]: https://mozilla-hub.atlassian.net/browse/MNTOR-3492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update FxA promo silent authentication path to dashboard

---

src/app/api/auth/[...nextauth]/route.ts

Follow-up to address https://github.com/mozilla/blurts-server/pull/5104#discussion_r1799621794.
Update the fallback path in case of a silent authentication callback error.
Same steps as for PR #5104:
- Enable the feature flag `PromptNoneAuthFlow`
- Visit http://localhost:6060/?utm_source=moz-account&utm_campaign=settings-promo&utm_content=monitor-free with and without the user authenticated with FxA

Update fallback path for silent authentication error

---

esbuild.cronjobs.js
src/emails/templates/breachAlert/BreachAlertEmail.stories.tsx
src/emails/templates/breachAlert/BreachAlertEmail.tsx
src/scripts/cronjobs/emailBreachAlerts.test.ts
src/scripts/cronjobs/emailBreachAlerts.tsx
tsconfig.cronjobs.json

Jira: MNTOR-3433
Figma:
There was a bug where the email template didn't correctly check if a scan had run - to fix this, I'm now looking at the `hasRunFreeScan` variable that @codemist added for exactly that purpose 😅 Note that that specific fix is in 86ef22453; I also added 229673769308707d6aea9ff6457add1a65fd7bea which fixes a "React is not defined" error when running cronjobs locally (basically, also applying the fix from https://github.com/mozilla/blurts-server/pull/5153 to dev mode).
I've updated the storybook to pass in the dashboard summary even if no scan was run (i.e. `onerep_profile_id` is `null`), so you should see the correct UTM parameters in Storybook, and the tests still succeed (whereas they fail with _only_ the Storybook change, without the code change).
You can also …

MNTOR-3433: Correctly detect the lack of scan

---

README.md

Add the badge for better way to check for daily e2e daily cron status

MNTOR-null: add e2e cron badge to README

---

.github/workflows/preview_deploy_gcp.yml

Figma:
Caused by this upgrade: https://github.com/mozilla/blurts-server/pull/5172
Migrate from v2 to v3 to prevent comment spamming in preview deployment

MNTOR-null: fix preview-deploy-pr-comments changes

---

src/db/tables/subscribers.ts

Jira: MNTOR-3606
Figma: N/A
While the query that selected free users to send the monthly report to had a clause to select subscribers who were in the flag's allowlist, it never ran that query if the flag is disabled (which is the only case in which the allowlist applies) :unamused: 
Disable the `MonthlyReportFreeUser` flag, add the email address of a free user whose `fxa_profile_json.locale` has `en-US` as the main locale, then run `npm run dev:cron:monthly-activity-free`. It should send an email to that user.
If you want to ensure that the locale is correct for your user, at least until they next login, you can use this query:
```sql
UPDATE subscribers SET fxa_profile_json = jsonb_set(fxa_profile_json, '{locale}', '"en-US;q=0.8,en;q=0.5,nl;q=0.3"') WHERE primary_email='<email address>'; …
```

MNTOR-3606: Respect allowlist of disabled flag

---

.github/workflows/release_cron_daily.yml

The github default token cannot trigger another github actions.. it would have to be a personal access token. For best security practices, we wouldn't want to use a personal access token. 
Instead we should just add the docker push at the end of this job, since it shouldn't trigger the retag job

MNTOR-null: add push to docker

---

.github/workflows/release_cron_daily.yml

pre release workflow needs to do a pull first to get the image
Error from last run: https://github.com/mozilla/blurts-server/actions/runs/11509608474/job/32040015716

MNTOR-null: pre release workflow needs to do a pull first

---

jest.config.cjs
src/app/functions/server/logging.ts
src/utils/email.test.ts
src/utils/email.ts

Jira: MNTOR-3713
Use the Winston logging library from the email utils so we get [structured logging](https://cloud.google.com/logging/docs/structured-logging) in GCP. Right now log messages are split across several lines which makes it difficult to locate and link to problems.
Our logging library automatically falls back to console logging in local environments, so the output can be inspected that way. We'll want to check on stage that the output looks acceptable.

use structured logging for email utils

---

next.config.js

Alternatively, I could make sure that we're passing in `UPLOAD_SENTRY_SOURCEMAPS` in CI, but since I assume we'll generally want to upload the source maps always, doing so by default seems more natural.

MNTOR-3494: Upload Sentry source maps by default

---

src/scripts/cronjobs/emailBreachAlerts.tsx
src/scripts/cronjobs/firstDataBrokerRemovalFixed.tsx
src/scripts/cronjobs/monthlyActivityFree.tsx
src/scripts/cronjobs/monthlyActivityPlus.tsx
src/utils/email.test.ts
src/utils/email.ts

Jira: MNTOR-3606
This closes the SMTP pool at the end of the cron job. Together with https://github.com/mozilla/blurts-server/pull/5257 and https://github.com/mozilla/blurts-server/pull/5254, this at least makes the cron job terminate immediately once it finishes locally for me, and hopefully on stage as well.

Close the SMTP connection pool when done

---

src/app/functions/server/glean.ts
src/app/functions/server/logging.ts

The `gcpdev` env isn't really in use yet according to @rhelmer ("it's intended for GCP-based dev environments"), but at least locally for me, the `LoggingWinston` instantiation seems to contribute some slowdown to the termination of Node scripts, so this change ensures it's only initialised when actually used.
It might not solve the issue we're seeing where the monthly-activity-free cron job is never terminating in stage, but even then at least it saves a few resources.
Jira: MNTOR-3606

Only initialise LoggingWinston when used

---

.github/workflows/unittests.yaml

I intended to do this in 647e95ede6f61628d73c136b6eb4afb506e2c0f4 (#5155), but the `failure()` call that I remove didn't limit it to failures — it explicitly enabled it for failing jobs, where the default is to skip subsequent jobs after a failure. However, if we want a job to run after both failed and successful runs, we need the `always()` call.

Always output the coverage report

---

src/db/connect.ts
src/scripts/cronjobs/monthlyActivityFree.tsx

Jira: MNTOR-3606
Figma:
This is the riskier sibling to https://github.com/mozilla/blurts-server/pull/5254, where I'm trying to figure out what could be causing the monthly-activity-free cronjob to be hanging.
In this PR, I call `destroy()` on the connection object when it's done - but more importantly, I have every `db/tables` module re-use the same connection object, to avoid having to do this: https://github.com/mozilla/blurts-server/blob/0da029654e65dedffe2b3bd169d1160626f2c11b/src/scripts/cronjobs/emailBreachAlerts.tsx#L427-L429
I think this should be safe, and in practice, the connections should be pooled already, but there might always be unforeseen effects, so please take some time to think about potential problems and/or ways to catch any that might occur.

Use a singleton for the DB connection object

---

config/nimbus.yaml

Jira: [MNTOR-3733](https://mozilla-hub.atlassian.net/browse/MNTOR-3733)
Enable the experiment `data-broker-removal-time-estimates` by default.
1. Enable the following feature flags: `DataBrokerRemovalTimeEstimateLabel`
2. (Re)build experiments: `npm run build-nimbus`
3. Add the environment variable `DATA_BROKER_REMOVAL_ESTIMATES_DATA` to `.env.local`. The data can be found in the [JIRA ticket](https://mozilla-hub.atlassian.net/browse/MNTOR-3618) under “Data for testing”.
[MNTOR-3733]: https://mozilla-hub.atlassian.net/browse/MNTOR-3733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enable data estimated removal time experiment by default

---

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/[[...slug]]/page.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/page.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/welcome/[[...slug]]/page.tsx
src/app/(proper_react)/(redesign)/(public)/page.tsx
src/app/api/v1/user/welcome-scan/create/route.ts
src/app/functions/server/getExperiments.ts

Jira: MNTOR-3380/
The Nimbus team came up with an ADR to support enabling preview mode on specific page loads. We previously had a workaround in place that would simply enable all experiments when an HTTP parameter like `?nimbus_web_preview=true` was passed, this change really just removes that and does two things:
1. change the param name to `nimbus_preview`
2. pass the param on to the Cirrus sidecar
This will instruct Cirrus to check which experiments are in preview mode on the server, and only enable these.
See ticket. It's probably easiest to merge this to stage and test there, but we can at least verify locally that `nimbus_preview=true` is appended to the URL set in `process.env.NIMBUS_SIDECAR_URL`.

MNTOR-3380 - pass nimbus_preview param to Cirrus

---

.github/workflows/docker_build_deploy.yml
Dockerfile

Jira: MNTOR-2934
Pass `SENTRY_AUTH_TOKEN` as secret to docker build. Note that this also upgrades to the latest official Docker (Community Edition) in the GitHub Action container, so we can pass Docker secrets via environment variable (the
version of Docker that ships with the version of Ubuntu that GHA ships by default only supports files, which is a lot
more cumbersome to deal with).
See the commit history on this branch, I temporarily modified the "build and push" docker GHA to run on this branch and I see that artifacts were successfully uploaded to Sentry.

MNTOR-2934/sentry sourcemap docker secret

---

src/e2e/fixtures/basePage.ts

Ignores the incorrect linting of Playwright’s `use`.

Ignore incorrect linting of Playwright’s use

---

src/db/tables/qa_customs.ts

Jira: [MNTOR-3843](https://mozilla-hub.atlassian.net/browse/MNTOR-3843)
When a Monitor account is deleted and recreated a new OneRep profile is created during the initial broker scan. We need to make sure to update the `onerep_profile_id` in the `qa_custom_toggles` table.
1. Delete the (admin) account from the settings page
2. Recreate the account
3. Run the initial scan with the recreated account
4. Make sure that custom data brokers can still be added through the QA customs tool
[MNTOR-3843]: https://mozilla-hub.atlassian.net/browse/MNTOR-3843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make QA customs tool usable after account recreation

---

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/panels/SettingsPanelEditInfo.tsx

Jira: [MNTOR-3849](https://mozilla-hub.atlassian.net/browse/MNTOR-3849)
Show the “email resent” indicator only after initiating the sending of the email.
| Before sending | After sending |
| --- | --- |
| <img width="421" alt="image" src="https://github.com/user-attachments/assets/a30254c9-b83b-4264-b473-1622e1bddd14"> | <img width="424" alt="image" src="https://github.com/user-attachments/assets/89ddb731-0b5c-4ece-87cf-bd00b2d2a451"> |
1. Enable the feature flag `SettingsPageRedesign`
2. Visit the settings page: `/user/settings`
3. Add a new email
4. Resend a verification email
[MNTOR-3849]: https://mozilla-hub.atlassian.net/browse/MNTOR-3849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix condition for showing the email resent indicator

---

.github/workflows/docker_build_deploy.yml

Jira: MNTOR-3853
Small followup to PR #5369 - Sentry does not want to use the full path from `github.ref` as `SENTRY_RELEASE`, I think `github.ref_name` is what is intended anyway.

use the ref_name not the full ref for SENTRY_RELEASE

---

src/e2e/pages/landingPage.ts

Jira: MNTOR-3852
Increase wait time before the sign in button appears
After reproducing locally, I believe the issue is actually the page load is assumed to be completed too quickly, so the sign in button is occasionally missed, causing intermittent auth time out

MNTOR-3852: e2e test wait time for page load

---

src/db/tables/featureFlags.ts
src/e2e/pages/landingPage.ts
src/e2e/pages/settingsPage.ts
src/e2e/specs/landing/landing-content.spec.ts
src/e2e/specs/settings.spec.ts

I’ve experienced some additional flaky tests while running the E2E tests locally. These changes seem to make them run more stable.

Address flaky local E2e test failures 

---

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/automatic-remove/AutomaticRemoveView.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/dataBrokerProfiles.module.scss

Jira: [MNTOR-3884](https://mozilla-hub.atlassian.net/browse/MNTOR-3884)
Increases the visibility for the Premium plan selection CTA against the purple background.
| Before | After |
| --- | --- |
| <img width="378" alt="Screenshot 2024-12-17 at 18 29 11" src="https://github.com/user-attachments/assets/dba797f7-146b-4cc4-9aa1-1b4b6d21bba9" /> | <img width="385" alt="Screenshot 2024-12-17 at 18 28 53" src="https://github.com/user-attachments/assets/ccc2a0ad-5397-4bed-9afd-5d897b65c8fd" /> |
The change can be looked at on the `fx-monitor-storybook` deploy preview: [1e. Automatically resolve brokers](https://deploy-preview-5425--fx-monitor-storybook.netlify.app/?path=/story/pages-logged-in-guided-resolution-1e-automatically-resolve-brokers--automatic-remove-view-story).
[MNTOR-3884]: …

Increase visibility for the Premium plan selection CTA

---

src/db/tables/subscribers.ts
src/scripts/cronjobs/monthlyActivityFree.tsx

Jira: MNTOR-3857
Our cronjob container is running out of memory trying to fetch data and filter in the application side, specifically it wants to extract the country code (if present) from the [locale header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) which can be pretty complex.
We can have the database do this filtering in a much more efficient way, I think it's worth revisiting this to simplify the query but the minimally-invasive fix I could figure out is:
1. use nested `CASE / ELSE` to split the locale into `country_code`
2. use a subquery so we can do a `WHERE IN` on `country_code`
The `batchSize` is now passed as an argument to the DB function and used directly as a `LIMIT` in the query, and the list of acceptable country codes is also passed as a …

MNTOR-3857 - move locale filtering from TS to SQL for monthly free activity report

---

src/constants.ts
src/scripts/cronjobs/monthlyActivityFree.tsx

Jira: MNTOR-3857
Revert the hardcoded value for `MONTHLY_ACTIVITY_FREE_EMAIL_BATCH_SIZE` and utilize the env var if available

MNTOR-3857: rework to utilize env var if possible/correct

---

src/utils/fxa.ts

Jira: MNTOR-3920
POST call for reactivating a user's subscription via FxA

MNTOR-3920: add new reactivate endpoint wrapper

---

src/db/tables/subscribers.ts

Jira: MNTOR-3919
Figma:
These functions will be used by the cronjob to get/set churn email state for a user.

MNTOR-3919: getting setter for churn email state (Part 2)

---

src/app/functions/server/applyCoupon.ts

Jira: MNTOR-3920
Functions to check and apply churn coupon codes

MNTOR-3920: check/apply churn coupon

---

src/emails/StorybookEmailRenderer.tsx
src/emails/templates/boilerplate/BoilerplateEmail.stories.tsx
src/emails/templates/breachAlert/BreachAlertEmail.stories.tsx
src/emails/templates/firstDataBrokerRemovalFixed/FirstDataBrokerRemovalFixed.stories.tsx
src/emails/templates/monthlyActivityFree/MonthlyActivityFreeEmail.stories.tsx
src/emails/templates/monthlyActivityPlus/MonthlyActivityPlusEmail.stories.tsx
src/emails/templates/signupReport/SignupReportEmail.stories.tsx
src/emails/templates/verifyEmailAddress/VerifyEmailAddressEmail.stories.tsx

SubPlat apparently sends plaintext emails:
https://storage.googleapis.com/mozilla-storybooks-fxa/commits/d06a74b249ebfe979642fdc94f4086a3ed031312/fxa-auth-server/index.html?path=/story/subplat-emails-layout--layout-with-was-deleted
We currently don't, although technically, we easily could: we'd just have to add a `text` property [to the options object passed to `gTransporter.sendMail`](https://github.com/mozilla/blurts-server/blob/a99b0506c72bcb02570839d9426513f040b01cb2/src/utils/email.ts#L65). Since there's currently discussion about whether to send them ourselves, I figured I'd at least adopt SubPlat's style for Storybook, to make it top-of-mind that we could send them, and to make it apparent where we're not and, in case we do start sending them, to make it ease to compare and see …

Make lack of plaintext emails explicit

---

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/SettingsPage.test.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/View.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/panels/SettingsPanelEditInfo.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/panels/SettingsPanelNotifications.tsx
src/app/functions/cronjobs/unsubscribeLinks.ts
src/db/tables/subscriber_email_preferences.ts

Jira: MNTOR-3848
Figma:
Builds on https://github.com/mozilla/blurts-server/pull/5511, but addressing the root cause.
Knex's returning() API is intended for INSERT, UPDATE and DELETE calls, not SELECTs:
https://knexjs.org/guide/query-builder.html#returning
I've updated the .where() queries to replace the returning() calls, i.e. by making them select all columns.
I then also removed the type assertions, so as to not indicate that rows will always be returned even in cases where they might not be available.
Also, the type assertion pretended that the `monthly_monitor_report_free` column could only be `boolean | undefined`, even though it can be `null` too (see `addUnsubcribeTokenForSubscriber`, which sets it to `null`).
And finally, the actual root cause of the issue, the return type …

MNTOR-3848: Fix invalid assertions

---

src/app/hooks/useGlean.ts
src/app/layout.tsx
src/contextProviders/experiments.test.tsx
src/contextProviders/experiments.tsx
src/scripts/build/nimbusTypes.js
src/telemetry/metrics.yaml

This PR I'm not sure about, and it's probably wrong, but: in MNTOR-3812, @rhelmer showed an example with `Enrollments` being an array, whereas our code says that it's a single object.
I'm not sure if it actually is, and if it is, I'm not sure why and how we're supposed to handle it - in this PR, I'm just always getting the first element, but that's probably not correct. However, I figured I'd submit this PR to at least have this observation in play somewhere.

Cirrus has enrolments as an array

---

src/app/(proper_react)/(redesign)/(authenticated)/admin/emails/EmailTrigger.tsx
src/app/(proper_react)/(redesign)/(authenticated)/admin/emails/actions.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/plus-expiration/PlusExpiration.test.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/plus-expiration/page.tsx
src/app/(proper_react)/(redesign)/terms/expiration-offer/page.tsx
src/db/tables/featureFlags.ts
src/emails/templates/upcomingExpiration/UpcomingExpirationEmail.test.tsx
src/scripts/cronjobs/churnDiscount.tsx

Jira: MNTOR-3917
Figma:
Followup to https://github.com/mozilla/blurts-server/pull/5559: adds a feature flag, the admin email UI, and tests.
Use the feature flag UI and admin email UI.

MNTOR-3917: Add feature flag, admin email UI and tests for the expiration email

---

src/app/(proper_react)/(redesign)/(authenticated)/user/plus-expiration/page.tsx
src/db/tables/subscriber_churns.ts

Jira: MNTOR-4028
Figma:
We email people that their subscription is about to expire, then mark them as having received the email. We check whether we have marked someone as having received the email when collecting the list of subscribers to email, which means that we shouldn't use that list when determining whether someone can renew.
I've updated it to use a similar check, but to skip the check for `churn_prevention_email_sent_at`.
Create a `.csv` file with the following contents:
```csv
userid,customer,created,nickname,intervl,intervl_count,plan_id,product_id,current_period_end
18b8ea3c9b12427893ded71fda0cb8aa,cus_custom,2/6/2024 10:57:57,Yearly Production Pricing ($8.99 per month: $107.88),year,1,price_1Nv4ODJNcmPzuWtRoYpoFHXd,prod_OiV9RSaatywSRy,2/2/2025 13:37:00
```
Replace …

MNTOR-4028: Allow renewing after receiving an expiration email

---

locales-pending/emails-all.ftl
locales-pending/emails-plus.ftl
src/app/(proper_react)/(redesign)/(authenticated)/admin/emails/actions.tsx
src/emails/components/EmailFooter.tsx
src/emails/components/EmailHeader.stories.tsx
src/emails/components/EmailHeader.tsx
src/emails/components/RedesignedEmailFooter.stories.tsx
src/emails/templates/upcomingExpiration/UpcomingExpirationEmail.tsx
src/scripts/cronjobs/churnDiscount.tsx
src/utils/email.ts

Jira: MNTOR-3917
Figma:
I figured I'd move the plaintext version into a separate PR, since it's not crucial functionality.
You can view the version in Storybook, and the admin UI will also send both the HTML and plaintext version. Mailinator will let you inspect both.

MNTOR-3917: Add plaintext version of Plus expiration email

---

.env.local.example

See https://mozilla.slack.com/archives/C04BLQVN151/p1739285607564839?thread_ts=1739282569.423019&cid=C04BLQVN151 - this updates the example `.env` file that new contributors start with to use the correct From: email address for local development, so that sending emails actually works (assuming the stage `$STMP_URL`).

Use correct From: address for local dev

---

src/db/migrations/20250204102945_add_last_optout_at.js

This is the same as https://github.com/mozilla/blurts-server/pull/5591, with the same commit 9670eb8, but without 8748975. That one's already been approved.

Migration for last_optout_at columns

---

src/apiMocks/mockData.ts
src/app/(proper_react)/(redesign)/(authenticated)/admin/qa-customs/onerepConfig.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/DashboardPlusUsers.stories.tsx
src/app/api/mock/onerep/config/config.ts
src/app/api/v1/admin/qa-customs/onerep/route.ts
src/app/components/client/exposure_card/ExposureCard.test.tsx
src/app/components/client/exposure_card/ScanResultCard.tsx
src/app/functions/server/onerep.ts
src/db/tables/onerep_scans.ts
src/db/tables/qa_customs.ts
src/knex-tables.d.ts

Jira: MNTOR-3971
Figma: N/A
This newly-added API response property accurately reflects the last scan date (which we had incorrectly hoped the last update date to do).
Note that I'm not familiar with the QA customs tool, so I mostly followed existing patterns and added `last_optout_at` wherever I could find `optout_attempts`. I think that covers it, but it uses quite a few custom types and otherwise lives fairly separate from the rest of the codebase, so I'm not particularly confident.
Make sure the `DataBrokerRemovalAttempts` and `AdditionalRemovalStatuses` flags are on, which in Storybook you can do by [setting it to](https://deploy-preview-5591--fx-monitor-storybook.netlify.app/?path=/story/pages-logged-in-dashboard-us-user-plus--dashboard-us-premium-unresolved-scan-unres …

MNTOR-3971: Use last optout date instead of last update

---

package-lock.json
package.json
patches/collect-v8-coverage+1.0.2.patch
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/filterExposures.ts
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/FixView.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/ResolutionContainer.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/ResolutionContent.tsx
src/app/components/client/Button.tsx
src/app/components/client/ComboBox.tsx
src/app/components/client/ExposuresFilter.tsx
src/app/components/client/FixNavigation.tsx
src/app/components/client/dialog/Dialog.tsx
src/app/components/client/toolbar/UpsellBadge.tsx
src/app/components/client/toolbar/UserMenu.tsx
src/app/functions/server/dashboard.ts
src/app/functions/server/getRelevantGuidedSteps.ts
src/app/functions/universal/guidedExperienceBreaches.ts
src/app/hooks/useLocalDismissal.ts

This directly applies the following Pull Request:
https://github.com/SimenB/collect-v8-coverage/pull/235
It's not entirely clear why it's needed, but it seems reasonable
and harmless enough, and there are no signs that Jest is really
maintained anymore, so a longer-term fix does not appear to be
forthcoming. Thus, this'll at least properly unblock Node upgrades
and other annoying coverage surprises.

Workaround inaccurate Jest coverage reporting

---

src/app/(proper_react)/(redesign)/(public)/layout.tsx

Jira: MNTOR-4062
Figma:
Currently we get a separate warning in Sentry every time we get -1 from Cirrus, because it also logs the guest string, which is irrelevant for this error. Thus, I set an error message that excludes it so that Sentry can group these instances.
Not sure, I think we should just see these coming in to Sentry once it's on stage?

Dedupe Sentry logs about missing Cirrus user ID

---

src/app/(proper_react)/(redesign)/(public)/breach-details/[breachName]/BreachDetailView.tsx
src/app/(proper_react)/(redesign)/(public)/breach-details/[breachName]/BreachDetailsView.test.tsx

Jira: MNTOR-3946
Figma:
We link to breached sites, but we don't endorse or advertise them, and search engines and other agents shouldn't interpret our links to them as such. That is what [`nofollow`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#nofollow) does.
Visit a public breach page, verify that its link has a `nofollow` attribute.

MNTOR-3946: State that we don't endorse breached sites

---

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/Dashboard.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/DashboardNonUSUsers.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/DashboardPlusUsers.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/DashboardUSUsers.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/automatic-remove/AutomaticRemove.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/manual-remove/ManualRemove.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/removal-under-maintenance/RemovalUnderMaintenanceView.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/start-free-scan/StartFreeScan.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/view-data-brokers/ViewDataBrokers.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/WelcomeToPlus.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/[type]/HighRiskDataBreach.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/[type]/LeakedPasswords.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/[type]/SecurityRecommendations.stories.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/layout.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/SettingsPage.test.tsx
src/app/(proper_react)/(redesign)/(public)/LandingViewRedesign/components/TopNavBar.module.scss
src/app/(proper_react)/(redesign)/(public)/LandingViewRedesign/components/TopNavBar.tsx
src/app/(proper_react)/(redesign)/(public)/PublicShell.module.scss
src/app/(proper_react)/(redesign)/(public)/PublicShell.tsx
src/app/(proper_react)/(redesign)/(public)/TopNavBar.tsx
src/app/(proper_react)/(redesign)/MobileShell.stories.ts
src/app/(proper_react)/(redesign)/MobileShell.tsx
src/app/(proper_react)/(redesign)/Shell.tsx

Jira: MNTOR-4060
Figma:
For the redesigned landing page, we added a sign-in button to the `<TopNavBar>` component. This was used in three places:
1. in the redesigned landing page, on desktop (from within `<PublicShell>`),
2. in the regular landing page, on desktop (from `<LandingView>`), and
3. in the shell that we use for loginwalled pages and the redesigned landing page, on mobile (from within `<MobileShell>`).
I split the `<TopNavBar>` into a redesigned version and the old version, reverting the recent changes in the latter - thus, only the former has the sign-in button. I then updated 1. to use the redesigned version, and 3. to use the version depending on the experiment and flag status.
I also updated the padding in the old top nav to remove some superfluous and inconsistent …

MNTOR-4060 Remove duplicate sign-in button on mobile, and prevent logo from shrinking

---

src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/components/FlagEditor.module.scss
src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/components/FlagEditor.tsx
src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/page.module.scss
src/app/(proper_react)/(redesign)/(authenticated)/admin/feature-flags/page.tsx
src/app/api/v1/admin/feature-flags/[flagId]/route.ts
src/app/api/v1/admin/feature-flags/route.ts
src/db/migrations/20250225111207_add_feature_flag_events.js
src/db/tables/featureFlags.ts
src/knex-tables.d.ts

Jira: MNTOR-4062
Figma:
The main change here is deprecating the `feature_flags` table (I wasn't brave enough to drop it yet), and replacing it by a `feature_flag_events` table that is append-only. This will allow us to have a full audit trail of when feature flags get modified.
To keep a similar experience as the `feature_flags` table, I added a `feature_flag_view` view.  Note that I did not preserve the wait list, description, dependencies, expiration, deletion, and owner, since we haven't used those.
The feature flag UI exposes the last date a flag was modified, and who modified it - but the full history is available in the DB if we ever need it.
I also updated the feature flag API to list all enabled flags when the user is not logged in. This will allow us to compare stage's and prod's …

Make feature flags auditable

---

src/app/(proper_react)/(redesign)/(public)/breaches/BreachIndexView.module.scss
src/app/(proper_react)/(redesign)/(public)/breaches/BreachIndexView.tsx
src/app/components/server/Icons.tsx

Jira: MNTOR-3945
Figma:
Adds a search icon to the breach filter field. I wrapped the label and input in a `.control`, replaced the label contents with the icon, positioned it absolutely on the left of the control, and added padding to the input field to not have its contents behind the icon.
[Visit `/breaches`.](https://deploy-preview-5682--fx-monitor-storybook.netlify.app/?path=/story/pages-public-breach-index--breach-index-view-story)

MNTOR-3945: Add a search icon to the breach filter field

---

locales-pending/dashboard-premium.ftl
src/app/components/server/RemovalProcess.module.scss
src/app/components/server/RemovalProcess.stories.ts
src/app/components/server/RemovalProcess.tsx
src/app/components/server/StatusPill.module.scss
src/app/components/server/StatusPill.stories.ts
src/app/tokens.scss

Jira: MNTOR-4092
Figma: https://www.figma.com/design/eyMvbuBeUvjnelDNGa8Mdb/Dashboard-visualization?node-id=950-39509&m=dev
This component is going to be used for the new in-progress dashboard. Note that it's slightly different from the designs, in that the chevrons don't have rounded corners - I couldn't find a way to do that. I'm hoping that UX will be fine with that :)
@codemist I'm not sure if it makes sense to group this under "Molecules" in Storybook, but I didn't know where else to put it. Let me know if you have a better suggestion.
You can [view it in Storybook](https://deploy-preview-5702--fx-monitor-storybook.netlify.app/?path=/story/design-systems-molecules-removal-process--removal-process-story).

MNTOR-4092: Add component to illustrate the removal flow

---

src/scripts/cronjobs/monthlyActivityFree.tsx

We don't know for sure how many emails we manage to send before our cronjobs get terminated; this adds logs so that we have a better picture.
Run `kill -SIGTERM <process ID>`. I added a timeout myself so that I had enough time to run that.

SVCSE-2596: Log how many emails we've sent at a timeout

---

src/app/(proper_react)/(redesign)/Shell/ShellRedesign.tsx

PR #5701
In PR #5701, the “Set notifications” sidebar link was mistakenly updated.

Fix sidebar notifications link

---

src/app/(proper_react)/(redesign)/(authenticated)/admin/dev/UserAdmin.tsx
src/app/(proper_react)/(redesign)/(authenticated)/admin/dev/actions.tsx
src/app/(proper_react)/(redesign)/(authenticated)/admin/dev/page.tsx

Jira: [MNTOR-4297](https://mozilla-hub.atlassian.net/browse/MNTOR-4297)
This PR adds a section to the admin panel that lists existing profile scans for a subscriber as well as the ability to trigger a manual scan on demand. We need this in place for QA to confirm that https://github.com/mozilla/blurts-server/pull/5793 is working as expected without having to wait for a monthly scan to be run so some functionality on `/admin/dev` will be available on `stage` as well.
1. Enable the feature flag `EditScanProfileDetails`
2. Visit `/admin/dev` with an authenticated admin user
3. Make profile info updates to a subscriber that has a OneRep scan profile
4. Trigger a manual scan
[MNTOR-4297]: https://mozilla-hub.atlassian.net/browse/MNTOR-4297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …

Add a profile scans section to /admin/dev

---

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/panels/SettingsPanelEditInfoRedesign.tsx

Jira:
- [MNTOR-4411](https://mozilla-hub.atlassian.net/browse/MNTOR-4411)
Use the `addresses` array instead of the deprecated `city_name` and `state_code` for the profile location preview.
[MNTOR-1806]: https://mozilla-hub.atlassian.net/browse/MNTOR-1806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MNTOR-4411]: https://mozilla-hub.atlassian.net/browse/MNTOR-4411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix profile location preview

---

src/db/migrations/20250430104448_add_feature_flag_events_primary_key.js

This is supposedly necessary to have its data carry over in a backup-restore procedure.

Add a primary key on feature_flag_events

---

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/panels/SettingsPanelEditProfile/EditProfileFormInputs.tsx

Small followup for https://github.com/mozilla/blurts-server/pull/5859 — the date of birth is stored as UTC but it's displayed on the `edit-profile` screen in the local timezone, which can cause it to look off by one day.
The previous PR fixed this for the `edit-info` but not the `edit-profile` screen. It's the same one-line fix to the client JS otherwise.
Navigate to "Update scan info" on sidebar, check DoB, then press "Add details" button and check DoB. I'm seeing different values when my system is in PST.
Changing system to UTC and reloading the page causes the problem to go away.

fix: Force UTC timezone for DOB on /user/settings/edit-profile screen

---

src/e2e/pages/landingPage.ts
src/e2e/specs/landing/landing-content.spec.ts

Apparently it no longer automatically redirects to the trailing- slash version.

MNTOR-4267: Remove trailing slash from expected SubPlat URL

---

package-lock.json
package.json
src/utils/dockerflow.ts

Recreated from https://github.com/mozilla/blurts-server/pull/5882 because the preview deploy was failed and couldn't be recreated.

Make explicit that this isn't a package to install

---

src/scripts/cronjobs/deleteSubsNoFxaUid.ts

one-off script to delete all rows in the "subscribers" table where fxa_uid is null/undefined/empty
Jira: MNTOR-4475
This script deletes all rows in the "subscribers" table where fxa_uid is null/undefined/empty
`npm run build`
`node dist/scripts/cronjobs/deleteSubsNoFxaUid.js`

MNTOR-4475: del rows without fxa_uid 

---

src/app/components/client/PromptNoneAuth.tsx
src/constants.ts

Initiate the silent authentication flow with the UTM parameter `prompt=none`.
- Enable the feature flag `PromptNoneAuthFlow`
- `http://localhost:6060/?prompt=none` with and without the user authenticated with FxA

Update silent auth flow

---

locales-pending/landing-redesign-experiment.ftl
src/app/(proper_react)/(redesign)/(public)/LandingViewRedesign/index.tsx

Fixes the layout for the landing page sections and updates a bundle banner string as per [this comment](https://www.figma.com/design/KytF3NIQfR8OoWu0osldg7?node-id=10141-33178&m=dev#1264076686).

Fix landing page sections layout and update string

---

src/app/(bundle)/bundle/onboarding/BundleOnboardingView.test.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/Dashboard.test.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/automatic-remove/AutomaticRemove.test.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/manual-remove/ManualRemove.test.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/removal-under-maintenance/RemovalUnderMaintenanceView.test.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/data-broker-profiles/welcome-to-plus/WelcomeToPlus.test.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/high-risk-data-breaches/[type]/HighRiskBreachLayout.test.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/leaked-passwords/[type]/LeakedPasswordsLayout.test.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/fix/security-recommendations/[type]/SecurityRecommendations.test.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/SettingsPage.test.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/SettingsPageRedesign.test.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/plus-expiration/PlusExpiration.test.tsx
src/app/(proper_react)/(redesign)/(authenticated)/user/welcome/Onboarding.test.tsx
src/app/(proper_react)/(redesign)/(public)/LandingView.test.tsx
src/app/(proper_react)/(redesign)/(public)/LandingViewRedesign/LandingViewRedesign.test.tsx
src/app/(proper_react)/(redesign)/(public)/how-it-works/HowItWorksView.test.tsx
src/app/(proper_react)/(redesign)/MobileShell.test.tsx
src/app/(proper_react)/(redesign)/Shell/Shell.test.tsx
src/app/components/client/ComboBox.test.tsx
src/app/components/client/ExposuresFilter.test.tsx
src/app/components/client/InputField.test.tsx
src/app/components/client/ProgressCard.test.tsx
src/app/components/client/csat_survey/CsatSurvey.test.tsx
src/app/components/client/exposure_card/ExposureCard.test.tsx
src/app/components/client/toolbar/AnnouncementDialog.test.tsx
src/app/components/client/toolbar/AppPicker.test.tsx
src/app/components/client/toolbar/UserMenu.test.tsx

The axe accessibility testing suite regularly times out in CI, making the results flaky. Since it's essentially running a whole bunch of tests, allowing it to run for a bit longer than usual is fine.

Increase timeout for running axe

---

.github/workflows/preview_deploy_gcp.yml
.github/workflows/preview_deploy_gcp_cleanup.yml

Since we can't log in to the preview sites yet, they're not very useful, but take a long time to deploy. We can re-enable once we migrate to Auth.js

Disable preview deployments

---

src/scripts/cronjobs/syncBreaches.ts

Follow-up from #5942 - I forgot to convert the return statements to continue statements, so the script is exiting early on every run when it hits `17app.co`
```
> cron:db-pull-breaches
> node dist/scripts/cronjobs/syncBreaches.js
Breaches found:  887
Unique breaches based on Name + BreachDate 887
upsertBreaches {
Name: '000webhost',
Title: '000webhost',
Domain: '000webhost.com',
BreachDate: '2015-03-01',
AddedDate: '2015-10-26T23:35:45Z',
ModifiedDate: '2017-12-10T21:44:27Z',
PwnCount: 14936670,
Description: 'In approximately March 2015, the free web hosting provider <a href="http://www.troyhunt.com/2015/10/breaches-traders-plain-text-passwords.html" target="_blank" rel="noopener">000webhost suffered a major data breach</a> that exposed almost 15 million customer records. The data was …
```

fix(cronjobs): Replace return with continue in for..of loop

---

.github/dependabot.yml

It's not certain that 24.10 will be the first LTS release, but it probably won't be a non-LTS one anymore.

Try to skip Node versions 24.x until 24.10

---

src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/dashboard/Dashboard.test.tsx
src/app/components/client/toolbar/UpsellBadge.tsx

Jira: [MNTOR-4707](https://mozilla-hub.atlassian.net/browse/MNTOR-4707)
Use `router.push()` instead of `redirect()` to ensure the browser history stack is preserved.
[MNTOR-4707]: https://mozilla-hub.atlassian.net/browse/MNTOR-4707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use router.push() for redirecting to /subscription-plans

---

src/app/components/client/Button.module.scss
src/app/components/client/exposure_card/ScanResultCard.tsx

Jira: [MNTOR-4782](https://mozilla-hub.atlassian.net/browse/MNTOR-4782)
Fixes the padding for buttons with `variant="link"`.
| Before | After |
| --- | --- |
| <img width="545" height="108" alt="image" src="https://github.com/user-attachments/assets/0ba474f0-9819-4ef5-8638-6e34fc50cc04" /> | <img width="546" height="97" alt="image" src="https://github.com/user-attachments/assets/b84879e2-1c8c-4091-a8c0-bde238e9bd8f" /> |
[MNTOR-4782]: https://mozilla-hub.atlassian.net/browse/MNTOR-4782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix padding for button variant link

---

src/app/api/auth/[...nextauth]/route.ts
src/app/api/utils/auth.tsx

Revert change to error page, too late to be useful. Leave the larger comment in place for `login_required` behavior.
Jira: MNTOR-4818
Revert change to error page. I've been testing on stage and it is too late in the process to do anything helpful, so it's effectively a no-op.
The log handling part of the previous PR is still in-place but this reverts to the previous behavior (leaving the longer comment about the existing behavior in place).

MNTOR-4818 — next auth error and logging (#6037)

---

README.md
package.json

This helps avoid accidentally overwriting previous reports when uploading them to the wiki.

Add date to load test report filenames

---

src/scripts/loadtest/moscary.ts

That's already a very conservative estimate of our peak load, so no need to do double that.

Lower default number of virtual users to 10

---

functional-tests/tests/onboarding.spec.ts

Stage is working with the flag disabled, but it was failing when it was enabled, so I want to enable it again so I can debug.
The prod tests seem to fail at about 85% through the scan, so it's probably just slower than locally/on stage.

Debug functional tests not succeeding

---

functional-tests/tests/onboarding.spec.ts

On prod, it often succeedes, but sometimes literally fails at 100% progress. So five extra seconds should do it, hopefully 🤞
From the report:

Bump e2e test timeout by five more seconds
